#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 157
#define LARGE_STATE_COUNT 4
#define SYMBOL_COUNT 36
#define ALIAS_COUNT 0
#define TOKEN_COUNT 19
#define EXTERNAL_TOKEN_COUNT 6
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 5
#define PRODUCTION_ID_COUNT 1

enum ts_symbol_identifiers {
  sym_section_header = 1,
  sym_marker_task_pending = 2,
  sym_marker_task_done = 3,
  sym_marker_property_info = 4,
  sym_marker_property_label = 5,
  sym_content = 6,
  sym__line = 7,
  sym__newline = 8,
  anon_sym_BQUOTE_BQUOTE_BQUOTE_LF = 9,
  anon_sym_LF_BQUOTE_BQUOTE_BQUOTE = 10,
  anon_sym_LF = 11,
  anon_sym_LF_BQUOTE_BQUOTE_BQUOTE_LF = 12,
  sym__indent = 13,
  sym__dedent = 14,
  sym__section_in = 15,
  sym__section_out = 16,
  sym__section_sibling = 17,
  sym__eof = 18,
  sym_document = 19,
  sym_section_children = 20,
  sym_section = 21,
  sym_marker_task = 22,
  sym_marker_property = 23,
  sym_marker = 24,
  sym_body = 25,
  sym_item = 26,
  sym_children = 27,
  aux_sym__lines = 28,
  sym_code_block_language = 29,
  sym_code_block_content = 30,
  sym_code_block = 31,
  aux_sym_document_repeat1 = 32,
  aux_sym_document_repeat2 = 33,
  aux_sym_section_children_repeat1 = 34,
  aux_sym_body_repeat1 = 35,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_section_header] = "section_header",
  [sym_marker_task_pending] = "marker_task_pending",
  [sym_marker_task_done] = "marker_task_done",
  [sym_marker_property_info] = "marker_property_info",
  [sym_marker_property_label] = "marker_property_label",
  [sym_content] = "content",
  [sym__line] = "_line",
  [sym__newline] = "_newline",
  [anon_sym_BQUOTE_BQUOTE_BQUOTE_LF] = "```\n",
  [anon_sym_LF_BQUOTE_BQUOTE_BQUOTE] = "\n```",
  [anon_sym_LF] = "\n",
  [anon_sym_LF_BQUOTE_BQUOTE_BQUOTE_LF] = "\n```\n",
  [sym__indent] = "_indent",
  [sym__dedent] = "_dedent",
  [sym__section_in] = "_section_in",
  [sym__section_out] = "_section_out",
  [sym__section_sibling] = "_section_sibling",
  [sym__eof] = "_eof",
  [sym_document] = "document",
  [sym_section_children] = "section_children",
  [sym_section] = "section",
  [sym_marker_task] = "marker_task",
  [sym_marker_property] = "marker_property",
  [sym_marker] = "marker",
  [sym_body] = "body",
  [sym_item] = "item",
  [sym_children] = "children",
  [aux_sym__lines] = "_lines",
  [sym_code_block_language] = "code_block_language",
  [sym_code_block_content] = "code_block_content",
  [sym_code_block] = "code_block",
  [aux_sym_document_repeat1] = "document_repeat1",
  [aux_sym_document_repeat2] = "document_repeat2",
  [aux_sym_section_children_repeat1] = "section_children_repeat1",
  [aux_sym_body_repeat1] = "body_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_section_header] = sym_section_header,
  [sym_marker_task_pending] = sym_marker_task_pending,
  [sym_marker_task_done] = sym_marker_task_done,
  [sym_marker_property_info] = sym_marker_property_info,
  [sym_marker_property_label] = sym_marker_property_label,
  [sym_content] = sym_content,
  [sym__line] = sym__line,
  [sym__newline] = sym__newline,
  [anon_sym_BQUOTE_BQUOTE_BQUOTE_LF] = anon_sym_BQUOTE_BQUOTE_BQUOTE_LF,
  [anon_sym_LF_BQUOTE_BQUOTE_BQUOTE] = anon_sym_LF_BQUOTE_BQUOTE_BQUOTE,
  [anon_sym_LF] = anon_sym_LF,
  [anon_sym_LF_BQUOTE_BQUOTE_BQUOTE_LF] = anon_sym_LF_BQUOTE_BQUOTE_BQUOTE_LF,
  [sym__indent] = sym__indent,
  [sym__dedent] = sym__dedent,
  [sym__section_in] = sym__section_in,
  [sym__section_out] = sym__section_out,
  [sym__section_sibling] = sym__section_sibling,
  [sym__eof] = sym__eof,
  [sym_document] = sym_document,
  [sym_section_children] = sym_section_children,
  [sym_section] = sym_section,
  [sym_marker_task] = sym_marker_task,
  [sym_marker_property] = sym_marker_property,
  [sym_marker] = sym_marker,
  [sym_body] = sym_body,
  [sym_item] = sym_item,
  [sym_children] = sym_children,
  [aux_sym__lines] = aux_sym__lines,
  [sym_code_block_language] = sym_code_block_language,
  [sym_code_block_content] = sym_code_block_content,
  [sym_code_block] = sym_code_block,
  [aux_sym_document_repeat1] = aux_sym_document_repeat1,
  [aux_sym_document_repeat2] = aux_sym_document_repeat2,
  [aux_sym_section_children_repeat1] = aux_sym_section_children_repeat1,
  [aux_sym_body_repeat1] = aux_sym_body_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_section_header] = {
    .visible = true,
    .named = true,
  },
  [sym_marker_task_pending] = {
    .visible = true,
    .named = true,
  },
  [sym_marker_task_done] = {
    .visible = true,
    .named = true,
  },
  [sym_marker_property_info] = {
    .visible = true,
    .named = true,
  },
  [sym_marker_property_label] = {
    .visible = true,
    .named = true,
  },
  [sym_content] = {
    .visible = true,
    .named = true,
  },
  [sym__line] = {
    .visible = false,
    .named = true,
  },
  [sym__newline] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_BQUOTE_BQUOTE_BQUOTE_LF] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LF_BQUOTE_BQUOTE_BQUOTE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LF] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LF_BQUOTE_BQUOTE_BQUOTE_LF] = {
    .visible = true,
    .named = false,
  },
  [sym__indent] = {
    .visible = false,
    .named = true,
  },
  [sym__dedent] = {
    .visible = false,
    .named = true,
  },
  [sym__section_in] = {
    .visible = false,
    .named = true,
  },
  [sym__section_out] = {
    .visible = false,
    .named = true,
  },
  [sym__section_sibling] = {
    .visible = false,
    .named = true,
  },
  [sym__eof] = {
    .visible = false,
    .named = true,
  },
  [sym_document] = {
    .visible = true,
    .named = true,
  },
  [sym_section_children] = {
    .visible = true,
    .named = true,
  },
  [sym_section] = {
    .visible = true,
    .named = true,
  },
  [sym_marker_task] = {
    .visible = true,
    .named = true,
  },
  [sym_marker_property] = {
    .visible = true,
    .named = true,
  },
  [sym_marker] = {
    .visible = true,
    .named = true,
  },
  [sym_body] = {
    .visible = true,
    .named = true,
  },
  [sym_item] = {
    .visible = true,
    .named = true,
  },
  [sym_children] = {
    .visible = true,
    .named = true,
  },
  [aux_sym__lines] = {
    .visible = false,
    .named = false,
  },
  [sym_code_block_language] = {
    .visible = true,
    .named = true,
  },
  [sym_code_block_content] = {
    .visible = true,
    .named = true,
  },
  [sym_code_block] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_document_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_document_repeat2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_section_children_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_body_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 2,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 5,
  [9] = 4,
  [10] = 6,
  [11] = 6,
  [12] = 4,
  [13] = 5,
  [14] = 7,
  [15] = 7,
  [16] = 5,
  [17] = 6,
  [18] = 4,
  [19] = 19,
  [20] = 5,
  [21] = 4,
  [22] = 6,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 4,
  [27] = 19,
  [28] = 28,
  [29] = 25,
  [30] = 30,
  [31] = 5,
  [32] = 32,
  [33] = 28,
  [34] = 34,
  [35] = 35,
  [36] = 32,
  [37] = 37,
  [38] = 6,
  [39] = 19,
  [40] = 30,
  [41] = 7,
  [42] = 42,
  [43] = 28,
  [44] = 35,
  [45] = 19,
  [46] = 34,
  [47] = 37,
  [48] = 19,
  [49] = 28,
  [50] = 37,
  [51] = 35,
  [52] = 34,
  [53] = 35,
  [54] = 37,
  [55] = 19,
  [56] = 35,
  [57] = 34,
  [58] = 37,
  [59] = 37,
  [60] = 35,
  [61] = 61,
  [62] = 61,
  [63] = 61,
  [64] = 64,
  [65] = 64,
  [66] = 64,
  [67] = 67,
  [68] = 68,
  [69] = 61,
  [70] = 64,
  [71] = 68,
  [72] = 67,
  [73] = 68,
  [74] = 67,
  [75] = 75,
  [76] = 67,
  [77] = 68,
  [78] = 75,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 83,
  [84] = 84,
  [85] = 85,
  [86] = 86,
  [87] = 19,
  [88] = 86,
  [89] = 89,
  [90] = 90,
  [91] = 91,
  [92] = 86,
  [93] = 85,
  [94] = 86,
  [95] = 86,
  [96] = 85,
  [97] = 97,
  [98] = 85,
  [99] = 86,
  [100] = 85,
  [101] = 101,
  [102] = 85,
  [103] = 103,
  [104] = 104,
  [105] = 105,
  [106] = 89,
  [107] = 107,
  [108] = 103,
  [109] = 97,
  [110] = 110,
  [111] = 107,
  [112] = 91,
  [113] = 110,
  [114] = 90,
  [115] = 115,
  [116] = 116,
  [117] = 115,
  [118] = 115,
  [119] = 115,
  [120] = 115,
  [121] = 115,
  [122] = 122,
  [123] = 123,
  [124] = 124,
  [125] = 125,
  [126] = 126,
  [127] = 123,
  [128] = 124,
  [129] = 123,
  [130] = 126,
  [131] = 124,
  [132] = 126,
  [133] = 124,
  [134] = 124,
  [135] = 135,
  [136] = 126,
  [137] = 126,
  [138] = 135,
  [139] = 139,
  [140] = 140,
  [141] = 135,
  [142] = 142,
  [143] = 143,
  [144] = 135,
  [145] = 126,
  [146] = 146,
  [147] = 147,
  [148] = 147,
  [149] = 147,
  [150] = 147,
  [151] = 147,
  [152] = 147,
  [153] = 123,
  [154] = 154,
  [155] = 155,
  [156] = 124,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(24);
      if (lookahead == '\n') ADVANCE(54);
      if (lookahead == '#') ADVANCE(44);
      if (lookahead == '*') ADVANCE(40);
      if (lookahead == '-') ADVANCE(41);
      if (lookahead == '.') ADVANCE(42);
      if (lookahead == '[') ADVANCE(43);
      if (lookahead == '`') ADVANCE(46);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(31);
      if (lookahead != 0) ADVANCE(52);
      END_STATE();
    case 1:
      if (lookahead == '\n') ADVANCE(25);
      if (lookahead != 0) ADVANCE(1);
      END_STATE();
    case 2:
      if (lookahead == '\n') ADVANCE(55);
      if (lookahead == '*') ADVANCE(40);
      if (lookahead == '-') ADVANCE(41);
      if (lookahead == '.') ADVANCE(42);
      if (lookahead == '[') ADVANCE(43);
      if (lookahead == '`') ADVANCE(46);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(34);
      if (lookahead != 0) ADVANCE(52);
      END_STATE();
    case 3:
      if (lookahead == '\n') ADVANCE(3);
      if (lookahead == '#') ADVANCE(19);
      if (lookahead == '*') ADVANCE(15);
      if (lookahead == '-') ADVANCE(16);
      if (lookahead == '.') ADVANCE(17);
      if (lookahead == '[') ADVANCE(18);
      if (lookahead == '`') ADVANCE(21);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(4);
      END_STATE();
    case 4:
      if (lookahead == '\n') ADVANCE(3);
      if (lookahead == '#') ADVANCE(19);
      if (lookahead == '*') ADVANCE(15);
      if (lookahead == '-') ADVANCE(16);
      if (lookahead == '.') ADVANCE(17);
      if (lookahead == '[') ADVANCE(18);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(4);
      END_STATE();
    case 5:
      if (lookahead == '\n') ADVANCE(62);
      END_STATE();
    case 6:
      if (lookahead == '\n') ADVANCE(56);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(36);
      if (lookahead != 0) ADVANCE(52);
      END_STATE();
    case 7:
      if (lookahead == '\n') ADVANCE(57);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(37);
      if (lookahead != 0) ADVANCE(52);
      END_STATE();
    case 8:
      if (lookahead == '\n') SKIP(8);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(51);
      if (lookahead != 0) ADVANCE(52);
      END_STATE();
    case 9:
      if (lookahead == '\n') ADVANCE(58);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(9);
      END_STATE();
    case 10:
      if (lookahead == '\n') ADVANCE(61);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(10);
      END_STATE();
    case 11:
      if (lookahead == '\n') ADVANCE(12);
      if (lookahead == '#') ADVANCE(44);
      if (lookahead == '*') ADVANCE(40);
      if (lookahead == '-') ADVANCE(41);
      if (lookahead == '.') ADVANCE(42);
      if (lookahead == '[') ADVANCE(43);
      if (lookahead == '`') ADVANCE(46);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(38);
      if (lookahead != 0) ADVANCE(52);
      END_STATE();
    case 12:
      if (lookahead == '\n') ADVANCE(12);
      if (lookahead == '#') ADVANCE(44);
      if (lookahead == '*') ADVANCE(40);
      if (lookahead == '-') ADVANCE(41);
      if (lookahead == '.') ADVANCE(42);
      if (lookahead == '[') ADVANCE(43);
      if (lookahead == '`') ADVANCE(48);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(38);
      if (lookahead != 0) ADVANCE(52);
      END_STATE();
    case 13:
      if (lookahead == '\n') ADVANCE(14);
      if (lookahead == '*') ADVANCE(40);
      if (lookahead == '-') ADVANCE(41);
      if (lookahead == '.') ADVANCE(42);
      if (lookahead == '[') ADVANCE(43);
      if (lookahead == '`') ADVANCE(46);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(39);
      if (lookahead != 0) ADVANCE(52);
      END_STATE();
    case 14:
      if (lookahead == '\n') ADVANCE(14);
      if (lookahead == '*') ADVANCE(40);
      if (lookahead == '-') ADVANCE(41);
      if (lookahead == '.') ADVANCE(42);
      if (lookahead == '[') ADVANCE(43);
      if (lookahead == '`') ADVANCE(48);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(39);
      if (lookahead != 0) ADVANCE(52);
      END_STATE();
    case 15:
      if (lookahead == ' ') ADVANCE(28);
      END_STATE();
    case 16:
      if (lookahead == ' ') ADVANCE(26);
      END_STATE();
    case 17:
      if (lookahead == ' ') ADVANCE(27);
      END_STATE();
    case 18:
      if (lookahead == ' ') ADVANCE(29);
      END_STATE();
    case 19:
      if (lookahead == ' ') ADVANCE(22);
      if (lookahead == '#') ADVANCE(19);
      END_STATE();
    case 20:
      if (lookahead == '`') ADVANCE(5);
      END_STATE();
    case 21:
      if (lookahead == '`') ADVANCE(20);
      END_STATE();
    case 22:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(1);
      END_STATE();
    case 23:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(30);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(sym_section_header);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(sym_marker_task_pending);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(sym_marker_task_done);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(sym_marker_property_info);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(sym_marker_property_label);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(sym_content);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(30);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(sym__line);
      if (lookahead == '\n') ADVANCE(54);
      if (lookahead == '#') ADVANCE(44);
      if (lookahead == '*') ADVANCE(40);
      if (lookahead == '-') ADVANCE(41);
      if (lookahead == '.') ADVANCE(42);
      if (lookahead == '[') ADVANCE(43);
      if (lookahead == '`') ADVANCE(46);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(31);
      if (lookahead != 0) ADVANCE(52);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(sym__line);
      if (lookahead == '\n') ADVANCE(25);
      if (lookahead != 0) ADVANCE(32);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(sym__line);
      if (lookahead == '\n') ADVANCE(59);
      if (lookahead != 0) ADVANCE(52);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(sym__line);
      if (lookahead == '\n') ADVANCE(55);
      if (lookahead == '*') ADVANCE(40);
      if (lookahead == '-') ADVANCE(41);
      if (lookahead == '.') ADVANCE(42);
      if (lookahead == '[') ADVANCE(43);
      if (lookahead == '`') ADVANCE(46);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(34);
      if (lookahead != 0) ADVANCE(52);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(sym__line);
      if (lookahead == '\n') ADVANCE(62);
      if (lookahead != 0) ADVANCE(52);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(sym__line);
      if (lookahead == '\n') ADVANCE(56);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(36);
      if (lookahead != 0) ADVANCE(52);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(sym__line);
      if (lookahead == '\n') ADVANCE(57);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(37);
      if (lookahead != 0) ADVANCE(52);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(sym__line);
      if (lookahead == '\n') ADVANCE(12);
      if (lookahead == '#') ADVANCE(44);
      if (lookahead == '*') ADVANCE(40);
      if (lookahead == '-') ADVANCE(41);
      if (lookahead == '.') ADVANCE(42);
      if (lookahead == '[') ADVANCE(43);
      if (lookahead == '`') ADVANCE(46);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(38);
      if (lookahead != 0) ADVANCE(52);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(sym__line);
      if (lookahead == '\n') ADVANCE(14);
      if (lookahead == '*') ADVANCE(40);
      if (lookahead == '-') ADVANCE(41);
      if (lookahead == '.') ADVANCE(42);
      if (lookahead == '[') ADVANCE(43);
      if (lookahead == '`') ADVANCE(46);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(39);
      if (lookahead != 0) ADVANCE(52);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(sym__line);
      if (lookahead == ' ') ADVANCE(28);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(52);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(sym__line);
      if (lookahead == ' ') ADVANCE(26);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(52);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(sym__line);
      if (lookahead == ' ') ADVANCE(27);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(52);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(sym__line);
      if (lookahead == ' ') ADVANCE(29);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(52);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(sym__line);
      if (lookahead == ' ') ADVANCE(53);
      if (lookahead == '#') ADVANCE(44);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(52);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(sym__line);
      if (lookahead == '`') ADVANCE(60);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(52);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(sym__line);
      if (lookahead == '`') ADVANCE(47);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(52);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(sym__line);
      if (lookahead == '`') ADVANCE(33);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(52);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(sym__line);
      if (lookahead == '`') ADVANCE(45);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(52);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(sym__line);
      if (lookahead == '`') ADVANCE(35);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(52);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(sym__line);
      if (lookahead == '`') ADVANCE(49);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(52);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(sym__line);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(51);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(52);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(sym__line);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(52);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(sym__line);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(32);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(sym__newline);
      if (lookahead == '\n') ADVANCE(54);
      if (lookahead == '#') ADVANCE(44);
      if (lookahead == '*') ADVANCE(40);
      if (lookahead == '-') ADVANCE(41);
      if (lookahead == '.') ADVANCE(42);
      if (lookahead == '[') ADVANCE(43);
      if (lookahead == '`') ADVANCE(48);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(31);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(sym__newline);
      if (lookahead == '\n') ADVANCE(55);
      if (lookahead == '*') ADVANCE(40);
      if (lookahead == '-') ADVANCE(41);
      if (lookahead == '.') ADVANCE(42);
      if (lookahead == '[') ADVANCE(43);
      if (lookahead == '`') ADVANCE(48);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(34);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(sym__newline);
      if (lookahead == '\n') ADVANCE(56);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(36);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(sym__newline);
      if (lookahead == '\n') ADVANCE(57);
      if (lookahead == '`') ADVANCE(50);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(37);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(sym__newline);
      if (lookahead == '\n') ADVANCE(58);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(anon_sym_BQUOTE_BQUOTE_BQUOTE_LF);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(anon_sym_LF_BQUOTE_BQUOTE_BQUOTE);
      if (lookahead == '\n') ADVANCE(59);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(anon_sym_LF);
      if (lookahead == '\n') ADVANCE(61);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(anon_sym_LF_BQUOTE_BQUOTE_BQUOTE_LF);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0, .external_lex_state = 1},
  [1] = {.lex_state = 11, .external_lex_state = 2},
  [2] = {.lex_state = 13, .external_lex_state = 3},
  [3] = {.lex_state = 13, .external_lex_state = 3},
  [4] = {.lex_state = 2, .external_lex_state = 1},
  [5] = {.lex_state = 2, .external_lex_state = 1},
  [6] = {.lex_state = 2, .external_lex_state = 1},
  [7] = {.lex_state = 13, .external_lex_state = 1},
  [8] = {.lex_state = 0, .external_lex_state = 4},
  [9] = {.lex_state = 0, .external_lex_state = 4},
  [10] = {.lex_state = 0, .external_lex_state = 4},
  [11] = {.lex_state = 2, .external_lex_state = 5},
  [12] = {.lex_state = 2, .external_lex_state = 5},
  [13] = {.lex_state = 2, .external_lex_state = 5},
  [14] = {.lex_state = 13, .external_lex_state = 5},
  [15] = {.lex_state = 11, .external_lex_state = 4},
  [16] = {.lex_state = 2, .external_lex_state = 3},
  [17] = {.lex_state = 0, .external_lex_state = 6},
  [18] = {.lex_state = 0, .external_lex_state = 6},
  [19] = {.lex_state = 2, .external_lex_state = 1},
  [20] = {.lex_state = 0, .external_lex_state = 6},
  [21] = {.lex_state = 2, .external_lex_state = 3},
  [22] = {.lex_state = 2, .external_lex_state = 3},
  [23] = {.lex_state = 4, .external_lex_state = 2},
  [24] = {.lex_state = 4, .external_lex_state = 2},
  [25] = {.lex_state = 4, .external_lex_state = 3},
  [26] = {.lex_state = 0, .external_lex_state = 2},
  [27] = {.lex_state = 2, .external_lex_state = 5},
  [28] = {.lex_state = 4, .external_lex_state = 7},
  [29] = {.lex_state = 4, .external_lex_state = 3},
  [30] = {.lex_state = 4, .external_lex_state = 3},
  [31] = {.lex_state = 0, .external_lex_state = 2},
  [32] = {.lex_state = 4, .external_lex_state = 3},
  [33] = {.lex_state = 4, .external_lex_state = 7},
  [34] = {.lex_state = 4, .external_lex_state = 7},
  [35] = {.lex_state = 2, .external_lex_state = 1},
  [36] = {.lex_state = 4, .external_lex_state = 3},
  [37] = {.lex_state = 2, .external_lex_state = 1},
  [38] = {.lex_state = 0, .external_lex_state = 2},
  [39] = {.lex_state = 0, .external_lex_state = 4},
  [40] = {.lex_state = 4, .external_lex_state = 3},
  [41] = {.lex_state = 11, .external_lex_state = 6},
  [42] = {.lex_state = 4, .external_lex_state = 2},
  [43] = {.lex_state = 4, .external_lex_state = 8},
  [44] = {.lex_state = 0, .external_lex_state = 4},
  [45] = {.lex_state = 2, .external_lex_state = 3},
  [46] = {.lex_state = 4, .external_lex_state = 8},
  [47] = {.lex_state = 0, .external_lex_state = 4},
  [48] = {.lex_state = 0, .external_lex_state = 6},
  [49] = {.lex_state = 4, .external_lex_state = 8},
  [50] = {.lex_state = 2, .external_lex_state = 5},
  [51] = {.lex_state = 2, .external_lex_state = 5},
  [52] = {.lex_state = 4, .external_lex_state = 3},
  [53] = {.lex_state = 0, .external_lex_state = 6},
  [54] = {.lex_state = 0, .external_lex_state = 6},
  [55] = {.lex_state = 0, .external_lex_state = 2},
  [56] = {.lex_state = 2, .external_lex_state = 3},
  [57] = {.lex_state = 4, .external_lex_state = 2},
  [58] = {.lex_state = 2, .external_lex_state = 3},
  [59] = {.lex_state = 0, .external_lex_state = 2},
  [60] = {.lex_state = 0, .external_lex_state = 2},
  [61] = {.lex_state = 4, .external_lex_state = 1},
  [62] = {.lex_state = 4, .external_lex_state = 4},
  [63] = {.lex_state = 4, .external_lex_state = 5},
  [64] = {.lex_state = 4},
  [65] = {.lex_state = 4},
  [66] = {.lex_state = 4},
  [67] = {.lex_state = 4, .external_lex_state = 7},
  [68] = {.lex_state = 4, .external_lex_state = 7},
  [69] = {.lex_state = 4, .external_lex_state = 6},
  [70] = {.lex_state = 4},
  [71] = {.lex_state = 4, .external_lex_state = 8},
  [72] = {.lex_state = 4, .external_lex_state = 8},
  [73] = {.lex_state = 4, .external_lex_state = 3},
  [74] = {.lex_state = 4, .external_lex_state = 3},
  [75] = {.lex_state = 4, .external_lex_state = 3},
  [76] = {.lex_state = 4, .external_lex_state = 2},
  [77] = {.lex_state = 4, .external_lex_state = 2},
  [78] = {.lex_state = 4, .external_lex_state = 2},
  [79] = {.lex_state = 4, .external_lex_state = 9},
  [80] = {.lex_state = 4, .external_lex_state = 9},
  [81] = {.lex_state = 4, .external_lex_state = 2},
  [82] = {.lex_state = 4, .external_lex_state = 2},
  [83] = {.lex_state = 4, .external_lex_state = 2},
  [84] = {.lex_state = 4, .external_lex_state = 2},
  [85] = {.lex_state = 6},
  [86] = {.lex_state = 6},
  [87] = {.lex_state = 7},
  [88] = {.lex_state = 6},
  [89] = {.lex_state = 4, .external_lex_state = 9},
  [90] = {.lex_state = 4, .external_lex_state = 9},
  [91] = {.lex_state = 4, .external_lex_state = 9},
  [92] = {.lex_state = 6},
  [93] = {.lex_state = 6},
  [94] = {.lex_state = 6},
  [95] = {.lex_state = 6},
  [96] = {.lex_state = 6},
  [97] = {.lex_state = 4, .external_lex_state = 9},
  [98] = {.lex_state = 6},
  [99] = {.lex_state = 6},
  [100] = {.lex_state = 6},
  [101] = {.lex_state = 7},
  [102] = {.lex_state = 6},
  [103] = {.lex_state = 0, .external_lex_state = 9},
  [104] = {.lex_state = 4},
  [105] = {.lex_state = 4, .external_lex_state = 2},
  [106] = {.lex_state = 4, .external_lex_state = 2},
  [107] = {.lex_state = 0, .external_lex_state = 9},
  [108] = {.lex_state = 0, .external_lex_state = 9},
  [109] = {.lex_state = 4, .external_lex_state = 2},
  [110] = {.lex_state = 0, .external_lex_state = 9},
  [111] = {.lex_state = 0, .external_lex_state = 9},
  [112] = {.lex_state = 4, .external_lex_state = 2},
  [113] = {.lex_state = 0, .external_lex_state = 9},
  [114] = {.lex_state = 4, .external_lex_state = 2},
  [115] = {.lex_state = 8},
  [116] = {.lex_state = 4},
  [117] = {.lex_state = 8},
  [118] = {.lex_state = 8},
  [119] = {.lex_state = 8},
  [120] = {.lex_state = 8},
  [121] = {.lex_state = 8},
  [122] = {.lex_state = 23},
  [123] = {.lex_state = 9},
  [124] = {.lex_state = 4},
  [125] = {.lex_state = 0},
  [126] = {.lex_state = 4},
  [127] = {.lex_state = 9},
  [128] = {.lex_state = 4},
  [129] = {.lex_state = 9},
  [130] = {.lex_state = 4},
  [131] = {.lex_state = 4},
  [132] = {.lex_state = 4},
  [133] = {.lex_state = 4},
  [134] = {.lex_state = 4},
  [135] = {.lex_state = 23},
  [136] = {.lex_state = 4},
  [137] = {.lex_state = 4},
  [138] = {.lex_state = 23},
  [139] = {.lex_state = 0},
  [140] = {.lex_state = 23},
  [141] = {.lex_state = 23},
  [142] = {.lex_state = 23},
  [143] = {.lex_state = 0},
  [144] = {.lex_state = 23},
  [145] = {.lex_state = 4},
  [146] = {.lex_state = 10},
  [147] = {.lex_state = 10},
  [148] = {.lex_state = 10},
  [149] = {.lex_state = 10},
  [150] = {.lex_state = 10},
  [151] = {.lex_state = 10},
  [152] = {.lex_state = 10},
  [153] = {.lex_state = 9},
  [154] = {.lex_state = 0},
  [155] = {.lex_state = 0},
  [156] = {.lex_state = 4},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_section_header] = ACTIONS(1),
    [sym_marker_task_pending] = ACTIONS(1),
    [sym_marker_task_done] = ACTIONS(1),
    [sym_marker_property_info] = ACTIONS(1),
    [sym_marker_property_label] = ACTIONS(1),
    [sym__line] = ACTIONS(1),
    [sym__newline] = ACTIONS(1),
    [anon_sym_BQUOTE_BQUOTE_BQUOTE_LF] = ACTIONS(1),
    [anon_sym_LF_BQUOTE_BQUOTE_BQUOTE] = ACTIONS(1),
    [sym__indent] = ACTIONS(1),
    [sym__dedent] = ACTIONS(1),
    [sym__section_in] = ACTIONS(1),
    [sym__section_out] = ACTIONS(1),
    [sym__section_sibling] = ACTIONS(1),
    [sym__eof] = ACTIONS(1),
  },
  [1] = {
    [sym_document] = STATE(143),
    [sym_section] = STATE(83),
    [sym_marker_task] = STATE(122),
    [sym_marker_property] = STATE(122),
    [sym_marker] = STATE(144),
    [sym_body] = STATE(42),
    [sym_item] = STATE(24),
    [sym_code_block] = STATE(31),
    [aux_sym_document_repeat1] = STATE(24),
    [aux_sym_document_repeat2] = STATE(83),
    [sym_section_header] = ACTIONS(3),
    [sym_marker_task_pending] = ACTIONS(5),
    [sym_marker_task_done] = ACTIONS(5),
    [sym_marker_property_info] = ACTIONS(7),
    [sym_marker_property_label] = ACTIONS(7),
    [sym__line] = ACTIONS(9),
    [anon_sym_BQUOTE_BQUOTE_BQUOTE_LF] = ACTIONS(11),
    [anon_sym_LF_BQUOTE_BQUOTE_BQUOTE] = ACTIONS(13),
    [sym__section_in] = ACTIONS(15),
    [sym__eof] = ACTIONS(17),
  },
  [2] = {
    [sym_section_children] = STATE(103),
    [sym_marker_task] = STATE(122),
    [sym_marker_property] = STATE(122),
    [sym_marker] = STATE(135),
    [sym_body] = STATE(40),
    [sym_item] = STATE(25),
    [sym_code_block] = STATE(16),
    [aux_sym_document_repeat1] = STATE(25),
    [sym_marker_task_pending] = ACTIONS(5),
    [sym_marker_task_done] = ACTIONS(5),
    [sym_marker_property_info] = ACTIONS(7),
    [sym_marker_property_label] = ACTIONS(7),
    [sym__line] = ACTIONS(19),
    [anon_sym_BQUOTE_BQUOTE_BQUOTE_LF] = ACTIONS(21),
    [anon_sym_LF_BQUOTE_BQUOTE_BQUOTE] = ACTIONS(23),
    [sym__section_in] = ACTIONS(25),
    [sym__section_out] = ACTIONS(27),
    [sym__section_sibling] = ACTIONS(27),
    [sym__eof] = ACTIONS(27),
  },
  [3] = {
    [sym_section_children] = STATE(108),
    [sym_marker_task] = STATE(122),
    [sym_marker_property] = STATE(122),
    [sym_marker] = STATE(135),
    [sym_body] = STATE(30),
    [sym_item] = STATE(29),
    [sym_code_block] = STATE(16),
    [aux_sym_document_repeat1] = STATE(29),
    [sym_marker_task_pending] = ACTIONS(5),
    [sym_marker_task_done] = ACTIONS(5),
    [sym_marker_property_info] = ACTIONS(7),
    [sym_marker_property_label] = ACTIONS(7),
    [sym__line] = ACTIONS(19),
    [anon_sym_BQUOTE_BQUOTE_BQUOTE_LF] = ACTIONS(21),
    [anon_sym_LF_BQUOTE_BQUOTE_BQUOTE] = ACTIONS(23),
    [sym__section_in] = ACTIONS(25),
    [sym__section_out] = ACTIONS(29),
    [sym__section_sibling] = ACTIONS(29),
    [sym__eof] = ACTIONS(29),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 6,
    ACTIONS(35), 1,
      anon_sym_BQUOTE_BQUOTE_BQUOTE_LF,
    ACTIONS(37), 1,
      anon_sym_LF_BQUOTE_BQUOTE_BQUOTE,
    ACTIONS(33), 2,
      sym__line,
      sym__newline,
    STATE(6), 3,
      aux_sym__lines,
      sym_code_block,
      aux_sym_body_repeat1,
    ACTIONS(31), 4,
      sym_marker_task_pending,
      sym_marker_task_done,
      sym_marker_property_info,
      sym_marker_property_label,
    ACTIONS(39), 6,
      sym__indent,
      sym__dedent,
      sym__section_in,
      sym__section_out,
      sym__section_sibling,
      sym__eof,
  [30] = 6,
    ACTIONS(35), 1,
      anon_sym_BQUOTE_BQUOTE_BQUOTE_LF,
    ACTIONS(37), 1,
      anon_sym_LF_BQUOTE_BQUOTE_BQUOTE,
    ACTIONS(43), 2,
      sym__line,
      sym__newline,
    STATE(4), 3,
      aux_sym__lines,
      sym_code_block,
      aux_sym_body_repeat1,
    ACTIONS(41), 4,
      sym_marker_task_pending,
      sym_marker_task_done,
      sym_marker_property_info,
      sym_marker_property_label,
    ACTIONS(45), 6,
      sym__indent,
      sym__dedent,
      sym__section_in,
      sym__section_out,
      sym__section_sibling,
      sym__eof,
  [60] = 6,
    ACTIONS(52), 1,
      anon_sym_BQUOTE_BQUOTE_BQUOTE_LF,
    ACTIONS(55), 1,
      anon_sym_LF_BQUOTE_BQUOTE_BQUOTE,
    ACTIONS(49), 2,
      sym__line,
      sym__newline,
    STATE(6), 3,
      aux_sym__lines,
      sym_code_block,
      aux_sym_body_repeat1,
    ACTIONS(47), 4,
      sym_marker_task_pending,
      sym_marker_task_done,
      sym_marker_property_info,
      sym_marker_property_label,
    ACTIONS(58), 6,
      sym__indent,
      sym__dedent,
      sym__section_in,
      sym__section_out,
      sym__section_sibling,
      sym__eof,
  [90] = 9,
    ACTIONS(35), 1,
      anon_sym_BQUOTE_BQUOTE_BQUOTE_LF,
    ACTIONS(37), 1,
      anon_sym_LF_BQUOTE_BQUOTE_BQUOTE,
    ACTIONS(62), 1,
      sym__line,
    ACTIONS(64), 1,
      sym__indent,
    STATE(5), 1,
      sym_code_block,
    STATE(61), 1,
      sym_body,
    STATE(68), 1,
      sym_children,
    ACTIONS(60), 4,
      sym_marker_task_pending,
      sym_marker_task_done,
      sym_marker_property_info,
      sym_marker_property_label,
    ACTIONS(66), 5,
      sym__dedent,
      sym__section_in,
      sym__section_out,
      sym__section_sibling,
      sym__eof,
  [125] = 6,
    ACTIONS(70), 1,
      anon_sym_BQUOTE_BQUOTE_BQUOTE_LF,
    ACTIONS(72), 1,
      anon_sym_LF_BQUOTE_BQUOTE_BQUOTE,
    ACTIONS(68), 2,
      sym__line,
      sym__newline,
    STATE(9), 3,
      aux_sym__lines,
      sym_code_block,
      aux_sym_body_repeat1,
    ACTIONS(45), 4,
      sym__indent,
      sym__dedent,
      sym__section_in,
      sym__eof,
    ACTIONS(41), 5,
      sym_section_header,
      sym_marker_task_pending,
      sym_marker_task_done,
      sym_marker_property_info,
      sym_marker_property_label,
  [154] = 6,
    ACTIONS(70), 1,
      anon_sym_BQUOTE_BQUOTE_BQUOTE_LF,
    ACTIONS(72), 1,
      anon_sym_LF_BQUOTE_BQUOTE_BQUOTE,
    ACTIONS(74), 2,
      sym__line,
      sym__newline,
    STATE(10), 3,
      aux_sym__lines,
      sym_code_block,
      aux_sym_body_repeat1,
    ACTIONS(39), 4,
      sym__indent,
      sym__dedent,
      sym__section_in,
      sym__eof,
    ACTIONS(31), 5,
      sym_section_header,
      sym_marker_task_pending,
      sym_marker_task_done,
      sym_marker_property_info,
      sym_marker_property_label,
  [183] = 6,
    ACTIONS(79), 1,
      anon_sym_BQUOTE_BQUOTE_BQUOTE_LF,
    ACTIONS(82), 1,
      anon_sym_LF_BQUOTE_BQUOTE_BQUOTE,
    ACTIONS(76), 2,
      sym__line,
      sym__newline,
    STATE(10), 3,
      aux_sym__lines,
      sym_code_block,
      aux_sym_body_repeat1,
    ACTIONS(58), 4,
      sym__indent,
      sym__dedent,
      sym__section_in,
      sym__eof,
    ACTIONS(47), 5,
      sym_section_header,
      sym_marker_task_pending,
      sym_marker_task_done,
      sym_marker_property_info,
      sym_marker_property_label,
  [212] = 6,
    ACTIONS(88), 1,
      anon_sym_BQUOTE_BQUOTE_BQUOTE_LF,
    ACTIONS(91), 1,
      anon_sym_LF_BQUOTE_BQUOTE_BQUOTE,
    ACTIONS(85), 2,
      sym__line,
      sym__newline,
    STATE(11), 3,
      aux_sym__lines,
      sym_code_block,
      aux_sym_body_repeat1,
    ACTIONS(47), 4,
      sym_marker_task_pending,
      sym_marker_task_done,
      sym_marker_property_info,
      sym_marker_property_label,
    ACTIONS(58), 5,
      sym__indent,
      sym__section_in,
      sym__section_out,
      sym__section_sibling,
      sym__eof,
  [241] = 6,
    ACTIONS(96), 1,
      anon_sym_BQUOTE_BQUOTE_BQUOTE_LF,
    ACTIONS(98), 1,
      anon_sym_LF_BQUOTE_BQUOTE_BQUOTE,
    ACTIONS(94), 2,
      sym__line,
      sym__newline,
    STATE(11), 3,
      aux_sym__lines,
      sym_code_block,
      aux_sym_body_repeat1,
    ACTIONS(31), 4,
      sym_marker_task_pending,
      sym_marker_task_done,
      sym_marker_property_info,
      sym_marker_property_label,
    ACTIONS(39), 5,
      sym__indent,
      sym__section_in,
      sym__section_out,
      sym__section_sibling,
      sym__eof,
  [270] = 6,
    ACTIONS(96), 1,
      anon_sym_BQUOTE_BQUOTE_BQUOTE_LF,
    ACTIONS(98), 1,
      anon_sym_LF_BQUOTE_BQUOTE_BQUOTE,
    ACTIONS(100), 2,
      sym__line,
      sym__newline,
    STATE(12), 3,
      aux_sym__lines,
      sym_code_block,
      aux_sym_body_repeat1,
    ACTIONS(41), 4,
      sym_marker_task_pending,
      sym_marker_task_done,
      sym_marker_property_info,
      sym_marker_property_label,
    ACTIONS(45), 5,
      sym__indent,
      sym__section_in,
      sym__section_out,
      sym__section_sibling,
      sym__eof,
  [299] = 9,
    ACTIONS(96), 1,
      anon_sym_BQUOTE_BQUOTE_BQUOTE_LF,
    ACTIONS(98), 1,
      anon_sym_LF_BQUOTE_BQUOTE_BQUOTE,
    ACTIONS(102), 1,
      sym__line,
    ACTIONS(104), 1,
      sym__indent,
    STATE(13), 1,
      sym_code_block,
    STATE(63), 1,
      sym_body,
    STATE(73), 1,
      sym_children,
    ACTIONS(60), 4,
      sym_marker_task_pending,
      sym_marker_task_done,
      sym_marker_property_info,
      sym_marker_property_label,
    ACTIONS(66), 4,
      sym__section_in,
      sym__section_out,
      sym__section_sibling,
      sym__eof,
  [333] = 9,
    ACTIONS(70), 1,
      anon_sym_BQUOTE_BQUOTE_BQUOTE_LF,
    ACTIONS(72), 1,
      anon_sym_LF_BQUOTE_BQUOTE_BQUOTE,
    ACTIONS(106), 1,
      sym__line,
    ACTIONS(108), 1,
      sym__indent,
    STATE(8), 1,
      sym_code_block,
    STATE(62), 1,
      sym_body,
    STATE(71), 1,
      sym_children,
    ACTIONS(66), 3,
      sym__dedent,
      sym__section_in,
      sym__eof,
    ACTIONS(60), 5,
      sym_section_header,
      sym_marker_task_pending,
      sym_marker_task_done,
      sym_marker_property_info,
      sym_marker_property_label,
  [367] = 6,
    ACTIONS(21), 1,
      anon_sym_BQUOTE_BQUOTE_BQUOTE_LF,
    ACTIONS(23), 1,
      anon_sym_LF_BQUOTE_BQUOTE_BQUOTE,
    ACTIONS(110), 2,
      sym__line,
      sym__newline,
    STATE(21), 3,
      aux_sym__lines,
      sym_code_block,
      aux_sym_body_repeat1,
    ACTIONS(41), 4,
      sym_marker_task_pending,
      sym_marker_task_done,
      sym_marker_property_info,
      sym_marker_property_label,
    ACTIONS(45), 4,
      sym__section_in,
      sym__section_out,
      sym__section_sibling,
      sym__eof,
  [395] = 6,
    ACTIONS(115), 1,
      anon_sym_BQUOTE_BQUOTE_BQUOTE_LF,
    ACTIONS(118), 1,
      anon_sym_LF_BQUOTE_BQUOTE_BQUOTE,
    ACTIONS(112), 2,
      sym__line,
      sym__newline,
    ACTIONS(58), 3,
      sym__indent,
      sym__section_in,
      sym__eof,
    STATE(17), 3,
      aux_sym__lines,
      sym_code_block,
      aux_sym_body_repeat1,
    ACTIONS(47), 5,
      sym_section_header,
      sym_marker_task_pending,
      sym_marker_task_done,
      sym_marker_property_info,
      sym_marker_property_label,
  [423] = 6,
    ACTIONS(123), 1,
      anon_sym_BQUOTE_BQUOTE_BQUOTE_LF,
    ACTIONS(125), 1,
      anon_sym_LF_BQUOTE_BQUOTE_BQUOTE,
    ACTIONS(121), 2,
      sym__line,
      sym__newline,
    ACTIONS(39), 3,
      sym__indent,
      sym__section_in,
      sym__eof,
    STATE(17), 3,
      aux_sym__lines,
      sym_code_block,
      aux_sym_body_repeat1,
    ACTIONS(31), 5,
      sym_section_header,
      sym_marker_task_pending,
      sym_marker_task_done,
      sym_marker_property_info,
      sym_marker_property_label,
  [451] = 4,
    STATE(19), 1,
      aux_sym__lines,
    ACTIONS(129), 2,
      sym__line,
      sym__newline,
    ACTIONS(127), 6,
      sym_marker_task_pending,
      sym_marker_task_done,
      sym_marker_property_info,
      sym_marker_property_label,
      anon_sym_BQUOTE_BQUOTE_BQUOTE_LF,
      anon_sym_LF_BQUOTE_BQUOTE_BQUOTE,
    ACTIONS(132), 6,
      sym__indent,
      sym__dedent,
      sym__section_in,
      sym__section_out,
      sym__section_sibling,
      sym__eof,
  [475] = 6,
    ACTIONS(123), 1,
      anon_sym_BQUOTE_BQUOTE_BQUOTE_LF,
    ACTIONS(125), 1,
      anon_sym_LF_BQUOTE_BQUOTE_BQUOTE,
    ACTIONS(134), 2,
      sym__line,
      sym__newline,
    ACTIONS(45), 3,
      sym__indent,
      sym__section_in,
      sym__eof,
    STATE(18), 3,
      aux_sym__lines,
      sym_code_block,
      aux_sym_body_repeat1,
    ACTIONS(41), 5,
      sym_section_header,
      sym_marker_task_pending,
      sym_marker_task_done,
      sym_marker_property_info,
      sym_marker_property_label,
  [503] = 6,
    ACTIONS(21), 1,
      anon_sym_BQUOTE_BQUOTE_BQUOTE_LF,
    ACTIONS(23), 1,
      anon_sym_LF_BQUOTE_BQUOTE_BQUOTE,
    ACTIONS(136), 2,
      sym__line,
      sym__newline,
    STATE(22), 3,
      aux_sym__lines,
      sym_code_block,
      aux_sym_body_repeat1,
    ACTIONS(31), 4,
      sym_marker_task_pending,
      sym_marker_task_done,
      sym_marker_property_info,
      sym_marker_property_label,
    ACTIONS(39), 4,
      sym__section_in,
      sym__section_out,
      sym__section_sibling,
      sym__eof,
  [531] = 6,
    ACTIONS(141), 1,
      anon_sym_BQUOTE_BQUOTE_BQUOTE_LF,
    ACTIONS(144), 1,
      anon_sym_LF_BQUOTE_BQUOTE_BQUOTE,
    ACTIONS(138), 2,
      sym__line,
      sym__newline,
    STATE(22), 3,
      aux_sym__lines,
      sym_code_block,
      aux_sym_body_repeat1,
    ACTIONS(47), 4,
      sym_marker_task_pending,
      sym_marker_task_done,
      sym_marker_property_info,
      sym_marker_property_label,
    ACTIONS(58), 4,
      sym__section_in,
      sym__section_out,
      sym__section_sibling,
      sym__eof,
  [559] = 9,
    ACTIONS(15), 1,
      sym__section_in,
    ACTIONS(147), 1,
      sym_section_header,
    ACTIONS(153), 1,
      sym__eof,
    STATE(144), 1,
      sym_marker,
    ACTIONS(149), 2,
      sym_marker_task_pending,
      sym_marker_task_done,
    ACTIONS(151), 2,
      sym_marker_property_info,
      sym_marker_property_label,
    STATE(57), 2,
      sym_item,
      aux_sym_document_repeat1,
    STATE(82), 2,
      sym_section,
      aux_sym_document_repeat2,
    STATE(122), 2,
      sym_marker_task,
      sym_marker_property,
  [592] = 9,
    ACTIONS(15), 1,
      sym__section_in,
    ACTIONS(147), 1,
      sym_section_header,
    ACTIONS(155), 1,
      sym__eof,
    STATE(144), 1,
      sym_marker,
    ACTIONS(149), 2,
      sym_marker_task_pending,
      sym_marker_task_done,
    ACTIONS(151), 2,
      sym_marker_property_info,
      sym_marker_property_label,
    STATE(57), 2,
      sym_item,
      aux_sym_document_repeat1,
    STATE(84), 2,
      sym_section,
      aux_sym_document_repeat2,
    STATE(122), 2,
      sym_marker_task,
      sym_marker_property,
  [625] = 8,
    ACTIONS(25), 1,
      sym__section_in,
    STATE(113), 1,
      sym_section_children,
    STATE(135), 1,
      sym_marker,
    ACTIONS(149), 2,
      sym_marker_task_pending,
      sym_marker_task_done,
    ACTIONS(151), 2,
      sym_marker_property_info,
      sym_marker_property_label,
    STATE(52), 2,
      sym_item,
      aux_sym_document_repeat1,
    STATE(122), 2,
      sym_marker_task,
      sym_marker_property,
    ACTIONS(157), 3,
      sym__section_out,
      sym__section_sibling,
      sym__eof,
  [656] = 6,
    ACTIONS(11), 1,
      anon_sym_BQUOTE_BQUOTE_BQUOTE_LF,
    ACTIONS(13), 1,
      anon_sym_LF_BQUOTE_BQUOTE_BQUOTE,
    ACTIONS(39), 2,
      sym__section_in,
      sym__eof,
    ACTIONS(159), 2,
      sym__line,
      sym__newline,
    STATE(38), 3,
      aux_sym__lines,
      sym_code_block,
      aux_sym_body_repeat1,
    ACTIONS(31), 5,
      sym_section_header,
      sym_marker_task_pending,
      sym_marker_task_done,
      sym_marker_property_info,
      sym_marker_property_label,
  [683] = 4,
    STATE(27), 1,
      aux_sym__lines,
    ACTIONS(161), 2,
      sym__line,
      sym__newline,
    ACTIONS(132), 5,
      sym__indent,
      sym__section_in,
      sym__section_out,
      sym__section_sibling,
      sym__eof,
    ACTIONS(127), 6,
      sym_marker_task_pending,
      sym_marker_task_done,
      sym_marker_property_info,
      sym_marker_property_label,
      anon_sym_BQUOTE_BQUOTE_BQUOTE_LF,
      anon_sym_LF_BQUOTE_BQUOTE_BQUOTE,
  [706] = 4,
    STATE(141), 1,
      sym_marker,
    STATE(34), 2,
      sym_item,
      aux_sym_document_repeat1,
    STATE(122), 2,
      sym_marker_task,
      sym_marker_property,
    ACTIONS(164), 9,
      sym__dedent,
      sym__section_in,
      sym__section_out,
      sym__section_sibling,
      sym__eof,
      sym_marker_task_pending,
      sym_marker_task_done,
      sym_marker_property_info,
      sym_marker_property_label,
  [729] = 8,
    ACTIONS(25), 1,
      sym__section_in,
    STATE(110), 1,
      sym_section_children,
    STATE(135), 1,
      sym_marker,
    ACTIONS(149), 2,
      sym_marker_task_pending,
      sym_marker_task_done,
    ACTIONS(151), 2,
      sym_marker_property_info,
      sym_marker_property_label,
    STATE(52), 2,
      sym_item,
      aux_sym_document_repeat1,
    STATE(122), 2,
      sym_marker_task,
      sym_marker_property,
    ACTIONS(166), 3,
      sym__section_out,
      sym__section_sibling,
      sym__eof,
  [760] = 8,
    ACTIONS(25), 1,
      sym__section_in,
    STATE(110), 1,
      sym_section_children,
    STATE(135), 1,
      sym_marker,
    ACTIONS(149), 2,
      sym_marker_task_pending,
      sym_marker_task_done,
    ACTIONS(151), 2,
      sym_marker_property_info,
      sym_marker_property_label,
    STATE(32), 2,
      sym_item,
      aux_sym_document_repeat1,
    STATE(122), 2,
      sym_marker_task,
      sym_marker_property,
    ACTIONS(166), 3,
      sym__section_out,
      sym__section_sibling,
      sym__eof,
  [791] = 6,
    ACTIONS(11), 1,
      anon_sym_BQUOTE_BQUOTE_BQUOTE_LF,
    ACTIONS(13), 1,
      anon_sym_LF_BQUOTE_BQUOTE_BQUOTE,
    ACTIONS(45), 2,
      sym__section_in,
      sym__eof,
    ACTIONS(168), 2,
      sym__line,
      sym__newline,
    STATE(26), 3,
      aux_sym__lines,
      sym_code_block,
      aux_sym_body_repeat1,
    ACTIONS(41), 5,
      sym_section_header,
      sym_marker_task_pending,
      sym_marker_task_done,
      sym_marker_property_info,
      sym_marker_property_label,
  [818] = 8,
    ACTIONS(25), 1,
      sym__section_in,
    STATE(111), 1,
      sym_section_children,
    STATE(135), 1,
      sym_marker,
    ACTIONS(149), 2,
      sym_marker_task_pending,
      sym_marker_task_done,
    ACTIONS(151), 2,
      sym_marker_property_info,
      sym_marker_property_label,
    STATE(52), 2,
      sym_item,
      aux_sym_document_repeat1,
    STATE(122), 2,
      sym_marker_task,
      sym_marker_property,
    ACTIONS(170), 3,
      sym__section_out,
      sym__section_sibling,
      sym__eof,
  [849] = 5,
    ACTIONS(172), 1,
      sym__dedent,
    STATE(141), 1,
      sym_marker,
    STATE(34), 2,
      sym_item,
      aux_sym_document_repeat1,
    STATE(122), 2,
      sym_marker_task,
      sym_marker_property,
    ACTIONS(164), 8,
      sym__section_in,
      sym__section_out,
      sym__section_sibling,
      sym__eof,
      sym_marker_task_pending,
      sym_marker_task_done,
      sym_marker_property_info,
      sym_marker_property_label,
  [874] = 6,
    STATE(141), 1,
      sym_marker,
    ACTIONS(174), 2,
      sym_marker_task_pending,
      sym_marker_task_done,
    ACTIONS(177), 2,
      sym_marker_property_info,
      sym_marker_property_label,
    STATE(34), 2,
      sym_item,
      aux_sym_document_repeat1,
    STATE(122), 2,
      sym_marker_task,
      sym_marker_property,
    ACTIONS(180), 5,
      sym__dedent,
      sym__section_in,
      sym__section_out,
      sym__section_sibling,
      sym__eof,
  [901] = 2,
    ACTIONS(184), 6,
      sym__indent,
      sym__dedent,
      sym__section_in,
      sym__section_out,
      sym__section_sibling,
      sym__eof,
    ACTIONS(182), 8,
      sym_marker_task_pending,
      sym_marker_task_done,
      sym_marker_property_info,
      sym_marker_property_label,
      sym__line,
      sym__newline,
      anon_sym_BQUOTE_BQUOTE_BQUOTE_LF,
      anon_sym_LF_BQUOTE_BQUOTE_BQUOTE,
  [920] = 8,
    ACTIONS(25), 1,
      sym__section_in,
    STATE(107), 1,
      sym_section_children,
    STATE(135), 1,
      sym_marker,
    ACTIONS(149), 2,
      sym_marker_task_pending,
      sym_marker_task_done,
    ACTIONS(151), 2,
      sym_marker_property_info,
      sym_marker_property_label,
    STATE(52), 2,
      sym_item,
      aux_sym_document_repeat1,
    STATE(122), 2,
      sym_marker_task,
      sym_marker_property,
    ACTIONS(186), 3,
      sym__section_out,
      sym__section_sibling,
      sym__eof,
  [951] = 2,
    ACTIONS(190), 6,
      sym__indent,
      sym__dedent,
      sym__section_in,
      sym__section_out,
      sym__section_sibling,
      sym__eof,
    ACTIONS(188), 8,
      sym_marker_task_pending,
      sym_marker_task_done,
      sym_marker_property_info,
      sym_marker_property_label,
      sym__line,
      sym__newline,
      anon_sym_BQUOTE_BQUOTE_BQUOTE_LF,
      anon_sym_LF_BQUOTE_BQUOTE_BQUOTE,
  [970] = 6,
    ACTIONS(195), 1,
      anon_sym_BQUOTE_BQUOTE_BQUOTE_LF,
    ACTIONS(198), 1,
      anon_sym_LF_BQUOTE_BQUOTE_BQUOTE,
    ACTIONS(58), 2,
      sym__section_in,
      sym__eof,
    ACTIONS(192), 2,
      sym__line,
      sym__newline,
    STATE(38), 3,
      aux_sym__lines,
      sym_code_block,
      aux_sym_body_repeat1,
    ACTIONS(47), 5,
      sym_section_header,
      sym_marker_task_pending,
      sym_marker_task_done,
      sym_marker_property_info,
      sym_marker_property_label,
  [997] = 4,
    STATE(39), 1,
      aux_sym__lines,
    ACTIONS(201), 2,
      sym__line,
      sym__newline,
    ACTIONS(132), 4,
      sym__indent,
      sym__dedent,
      sym__section_in,
      sym__eof,
    ACTIONS(127), 7,
      sym_section_header,
      sym_marker_task_pending,
      sym_marker_task_done,
      sym_marker_property_info,
      sym_marker_property_label,
      anon_sym_BQUOTE_BQUOTE_BQUOTE_LF,
      anon_sym_LF_BQUOTE_BQUOTE_BQUOTE,
  [1020] = 8,
    ACTIONS(25), 1,
      sym__section_in,
    STATE(113), 1,
      sym_section_children,
    STATE(135), 1,
      sym_marker,
    ACTIONS(149), 2,
      sym_marker_task_pending,
      sym_marker_task_done,
    ACTIONS(151), 2,
      sym_marker_property_info,
      sym_marker_property_label,
    STATE(36), 2,
      sym_item,
      aux_sym_document_repeat1,
    STATE(122), 2,
      sym_marker_task,
      sym_marker_property,
    ACTIONS(157), 3,
      sym__section_out,
      sym__section_sibling,
      sym__eof,
  [1051] = 9,
    ACTIONS(123), 1,
      anon_sym_BQUOTE_BQUOTE_BQUOTE_LF,
    ACTIONS(125), 1,
      anon_sym_LF_BQUOTE_BQUOTE_BQUOTE,
    ACTIONS(204), 1,
      sym__line,
    ACTIONS(206), 1,
      sym__indent,
    STATE(20), 1,
      sym_code_block,
    STATE(69), 1,
      sym_body,
    STATE(77), 1,
      sym_children,
    ACTIONS(66), 2,
      sym__section_in,
      sym__eof,
    ACTIONS(60), 5,
      sym_section_header,
      sym_marker_task_pending,
      sym_marker_task_done,
      sym_marker_property_info,
      sym_marker_property_label,
  [1084] = 9,
    ACTIONS(15), 1,
      sym__section_in,
    ACTIONS(147), 1,
      sym_section_header,
    ACTIONS(155), 1,
      sym__eof,
    STATE(144), 1,
      sym_marker,
    ACTIONS(149), 2,
      sym_marker_task_pending,
      sym_marker_task_done,
    ACTIONS(151), 2,
      sym_marker_property_info,
      sym_marker_property_label,
    STATE(23), 2,
      sym_item,
      aux_sym_document_repeat1,
    STATE(84), 2,
      sym_section,
      aux_sym_document_repeat2,
    STATE(122), 2,
      sym_marker_task,
      sym_marker_property,
  [1117] = 4,
    STATE(138), 1,
      sym_marker,
    STATE(46), 2,
      sym_item,
      aux_sym_document_repeat1,
    STATE(122), 2,
      sym_marker_task,
      sym_marker_property,
    ACTIONS(164), 8,
      sym__dedent,
      sym__section_in,
      sym__eof,
      sym_section_header,
      sym_marker_task_pending,
      sym_marker_task_done,
      sym_marker_property_info,
      sym_marker_property_label,
  [1139] = 2,
    ACTIONS(184), 4,
      sym__indent,
      sym__dedent,
      sym__section_in,
      sym__eof,
    ACTIONS(182), 9,
      sym_section_header,
      sym_marker_task_pending,
      sym_marker_task_done,
      sym_marker_property_info,
      sym_marker_property_label,
      sym__line,
      sym__newline,
      anon_sym_BQUOTE_BQUOTE_BQUOTE_LF,
      anon_sym_LF_BQUOTE_BQUOTE_BQUOTE,
  [1157] = 4,
    STATE(45), 1,
      aux_sym__lines,
    ACTIONS(208), 2,
      sym__line,
      sym__newline,
    ACTIONS(132), 4,
      sym__section_in,
      sym__section_out,
      sym__section_sibling,
      sym__eof,
    ACTIONS(127), 6,
      sym_marker_task_pending,
      sym_marker_task_done,
      sym_marker_property_info,
      sym_marker_property_label,
      anon_sym_BQUOTE_BQUOTE_BQUOTE_LF,
      anon_sym_LF_BQUOTE_BQUOTE_BQUOTE,
  [1179] = 6,
    STATE(138), 1,
      sym_marker,
    ACTIONS(174), 2,
      sym_marker_task_pending,
      sym_marker_task_done,
    ACTIONS(177), 2,
      sym_marker_property_info,
      sym_marker_property_label,
    STATE(46), 2,
      sym_item,
      aux_sym_document_repeat1,
    STATE(122), 2,
      sym_marker_task,
      sym_marker_property,
    ACTIONS(180), 4,
      sym__dedent,
      sym__section_in,
      sym__eof,
      sym_section_header,
  [1205] = 2,
    ACTIONS(190), 4,
      sym__indent,
      sym__dedent,
      sym__section_in,
      sym__eof,
    ACTIONS(188), 9,
      sym_section_header,
      sym_marker_task_pending,
      sym_marker_task_done,
      sym_marker_property_info,
      sym_marker_property_label,
      sym__line,
      sym__newline,
      anon_sym_BQUOTE_BQUOTE_BQUOTE_LF,
      anon_sym_LF_BQUOTE_BQUOTE_BQUOTE,
  [1223] = 4,
    STATE(48), 1,
      aux_sym__lines,
    ACTIONS(211), 2,
      sym__line,
      sym__newline,
    ACTIONS(132), 3,
      sym__indent,
      sym__section_in,
      sym__eof,
    ACTIONS(127), 7,
      sym_section_header,
      sym_marker_task_pending,
      sym_marker_task_done,
      sym_marker_property_info,
      sym_marker_property_label,
      anon_sym_BQUOTE_BQUOTE_BQUOTE_LF,
      anon_sym_LF_BQUOTE_BQUOTE_BQUOTE,
  [1245] = 5,
    ACTIONS(214), 1,
      sym__dedent,
    STATE(138), 1,
      sym_marker,
    STATE(46), 2,
      sym_item,
      aux_sym_document_repeat1,
    STATE(122), 2,
      sym_marker_task,
      sym_marker_property,
    ACTIONS(164), 7,
      sym__section_in,
      sym__eof,
      sym_section_header,
      sym_marker_task_pending,
      sym_marker_task_done,
      sym_marker_property_info,
      sym_marker_property_label,
  [1269] = 2,
    ACTIONS(190), 5,
      sym__indent,
      sym__section_in,
      sym__section_out,
      sym__section_sibling,
      sym__eof,
    ACTIONS(188), 8,
      sym_marker_task_pending,
      sym_marker_task_done,
      sym_marker_property_info,
      sym_marker_property_label,
      sym__line,
      sym__newline,
      anon_sym_BQUOTE_BQUOTE_BQUOTE_LF,
      anon_sym_LF_BQUOTE_BQUOTE_BQUOTE,
  [1287] = 2,
    ACTIONS(184), 5,
      sym__indent,
      sym__section_in,
      sym__section_out,
      sym__section_sibling,
      sym__eof,
    ACTIONS(182), 8,
      sym_marker_task_pending,
      sym_marker_task_done,
      sym_marker_property_info,
      sym_marker_property_label,
      sym__line,
      sym__newline,
      anon_sym_BQUOTE_BQUOTE_BQUOTE_LF,
      anon_sym_LF_BQUOTE_BQUOTE_BQUOTE,
  [1305] = 6,
    STATE(135), 1,
      sym_marker,
    ACTIONS(174), 2,
      sym_marker_task_pending,
      sym_marker_task_done,
    ACTIONS(177), 2,
      sym_marker_property_info,
      sym_marker_property_label,
    STATE(52), 2,
      sym_item,
      aux_sym_document_repeat1,
    STATE(122), 2,
      sym_marker_task,
      sym_marker_property,
    ACTIONS(180), 4,
      sym__section_in,
      sym__section_out,
      sym__section_sibling,
      sym__eof,
  [1331] = 2,
    ACTIONS(184), 3,
      sym__indent,
      sym__section_in,
      sym__eof,
    ACTIONS(182), 9,
      sym_section_header,
      sym_marker_task_pending,
      sym_marker_task_done,
      sym_marker_property_info,
      sym_marker_property_label,
      sym__line,
      sym__newline,
      anon_sym_BQUOTE_BQUOTE_BQUOTE_LF,
      anon_sym_LF_BQUOTE_BQUOTE_BQUOTE,
  [1348] = 2,
    ACTIONS(190), 3,
      sym__indent,
      sym__section_in,
      sym__eof,
    ACTIONS(188), 9,
      sym_section_header,
      sym_marker_task_pending,
      sym_marker_task_done,
      sym_marker_property_info,
      sym_marker_property_label,
      sym__line,
      sym__newline,
      anon_sym_BQUOTE_BQUOTE_BQUOTE_LF,
      anon_sym_LF_BQUOTE_BQUOTE_BQUOTE,
  [1365] = 4,
    STATE(55), 1,
      aux_sym__lines,
    ACTIONS(132), 2,
      sym__section_in,
      sym__eof,
    ACTIONS(216), 2,
      sym__line,
      sym__newline,
    ACTIONS(127), 7,
      sym_section_header,
      sym_marker_task_pending,
      sym_marker_task_done,
      sym_marker_property_info,
      sym_marker_property_label,
      anon_sym_BQUOTE_BQUOTE_BQUOTE_LF,
      anon_sym_LF_BQUOTE_BQUOTE_BQUOTE,
  [1386] = 2,
    ACTIONS(184), 4,
      sym__section_in,
      sym__section_out,
      sym__section_sibling,
      sym__eof,
    ACTIONS(182), 8,
      sym_marker_task_pending,
      sym_marker_task_done,
      sym_marker_property_info,
      sym_marker_property_label,
      sym__line,
      sym__newline,
      anon_sym_BQUOTE_BQUOTE_BQUOTE_LF,
      anon_sym_LF_BQUOTE_BQUOTE_BQUOTE,
  [1403] = 6,
    STATE(144), 1,
      sym_marker,
    ACTIONS(174), 2,
      sym_marker_task_pending,
      sym_marker_task_done,
    ACTIONS(177), 2,
      sym_marker_property_info,
      sym_marker_property_label,
    STATE(57), 2,
      sym_item,
      aux_sym_document_repeat1,
    STATE(122), 2,
      sym_marker_task,
      sym_marker_property,
    ACTIONS(180), 3,
      sym__section_in,
      sym__eof,
      sym_section_header,
  [1428] = 2,
    ACTIONS(190), 4,
      sym__section_in,
      sym__section_out,
      sym__section_sibling,
      sym__eof,
    ACTIONS(188), 8,
      sym_marker_task_pending,
      sym_marker_task_done,
      sym_marker_property_info,
      sym_marker_property_label,
      sym__line,
      sym__newline,
      anon_sym_BQUOTE_BQUOTE_BQUOTE_LF,
      anon_sym_LF_BQUOTE_BQUOTE_BQUOTE,
  [1445] = 2,
    ACTIONS(190), 2,
      sym__section_in,
      sym__eof,
    ACTIONS(188), 9,
      sym_section_header,
      sym_marker_task_pending,
      sym_marker_task_done,
      sym_marker_property_info,
      sym_marker_property_label,
      sym__line,
      sym__newline,
      anon_sym_BQUOTE_BQUOTE_BQUOTE_LF,
      anon_sym_LF_BQUOTE_BQUOTE_BQUOTE,
  [1461] = 2,
    ACTIONS(184), 2,
      sym__section_in,
      sym__eof,
    ACTIONS(182), 9,
      sym_section_header,
      sym_marker_task_pending,
      sym_marker_task_done,
      sym_marker_property_info,
      sym_marker_property_label,
      sym__line,
      sym__newline,
      anon_sym_BQUOTE_BQUOTE_BQUOTE_LF,
      anon_sym_LF_BQUOTE_BQUOTE_BQUOTE,
  [1477] = 3,
    ACTIONS(64), 1,
      sym__indent,
    STATE(67), 1,
      sym_children,
    ACTIONS(219), 9,
      sym__dedent,
      sym__section_in,
      sym__section_out,
      sym__section_sibling,
      sym__eof,
      sym_marker_task_pending,
      sym_marker_task_done,
      sym_marker_property_info,
      sym_marker_property_label,
  [1495] = 3,
    ACTIONS(108), 1,
      sym__indent,
    STATE(72), 1,
      sym_children,
    ACTIONS(219), 8,
      sym__dedent,
      sym__section_in,
      sym__eof,
      sym_section_header,
      sym_marker_task_pending,
      sym_marker_task_done,
      sym_marker_property_info,
      sym_marker_property_label,
  [1512] = 3,
    ACTIONS(104), 1,
      sym__indent,
    STATE(74), 1,
      sym_children,
    ACTIONS(219), 8,
      sym__section_in,
      sym__section_out,
      sym__section_sibling,
      sym__eof,
      sym_marker_task_pending,
      sym_marker_task_done,
      sym_marker_property_info,
      sym_marker_property_label,
  [1529] = 5,
    STATE(141), 1,
      sym_marker,
    ACTIONS(149), 2,
      sym_marker_task_pending,
      sym_marker_task_done,
    ACTIONS(151), 2,
      sym_marker_property_info,
      sym_marker_property_label,
    STATE(28), 2,
      sym_item,
      aux_sym_document_repeat1,
    STATE(122), 2,
      sym_marker_task,
      sym_marker_property,
  [1549] = 5,
    STATE(138), 1,
      sym_marker,
    ACTIONS(149), 2,
      sym_marker_task_pending,
      sym_marker_task_done,
    ACTIONS(151), 2,
      sym_marker_property_info,
      sym_marker_property_label,
    STATE(43), 2,
      sym_item,
      aux_sym_document_repeat1,
    STATE(122), 2,
      sym_marker_task,
      sym_marker_property,
  [1569] = 5,
    STATE(141), 1,
      sym_marker,
    ACTIONS(149), 2,
      sym_marker_task_pending,
      sym_marker_task_done,
    ACTIONS(151), 2,
      sym_marker_property_info,
      sym_marker_property_label,
    STATE(33), 2,
      sym_item,
      aux_sym_document_repeat1,
    STATE(122), 2,
      sym_marker_task,
      sym_marker_property,
  [1589] = 1,
    ACTIONS(221), 9,
      sym__dedent,
      sym__section_in,
      sym__section_out,
      sym__section_sibling,
      sym__eof,
      sym_marker_task_pending,
      sym_marker_task_done,
      sym_marker_property_info,
      sym_marker_property_label,
  [1601] = 1,
    ACTIONS(219), 9,
      sym__dedent,
      sym__section_in,
      sym__section_out,
      sym__section_sibling,
      sym__eof,
      sym_marker_task_pending,
      sym_marker_task_done,
      sym_marker_property_info,
      sym_marker_property_label,
  [1613] = 3,
    ACTIONS(206), 1,
      sym__indent,
    STATE(76), 1,
      sym_children,
    ACTIONS(219), 7,
      sym__section_in,
      sym__eof,
      sym_section_header,
      sym_marker_task_pending,
      sym_marker_task_done,
      sym_marker_property_info,
      sym_marker_property_label,
  [1629] = 5,
    STATE(138), 1,
      sym_marker,
    ACTIONS(149), 2,
      sym_marker_task_pending,
      sym_marker_task_done,
    ACTIONS(151), 2,
      sym_marker_property_info,
      sym_marker_property_label,
    STATE(49), 2,
      sym_item,
      aux_sym_document_repeat1,
    STATE(122), 2,
      sym_marker_task,
      sym_marker_property,
  [1649] = 1,
    ACTIONS(219), 8,
      sym__dedent,
      sym__section_in,
      sym__eof,
      sym_section_header,
      sym_marker_task_pending,
      sym_marker_task_done,
      sym_marker_property_info,
      sym_marker_property_label,
  [1660] = 1,
    ACTIONS(221), 8,
      sym__dedent,
      sym__section_in,
      sym__eof,
      sym_section_header,
      sym_marker_task_pending,
      sym_marker_task_done,
      sym_marker_property_info,
      sym_marker_property_label,
  [1671] = 1,
    ACTIONS(219), 8,
      sym__section_in,
      sym__section_out,
      sym__section_sibling,
      sym__eof,
      sym_marker_task_pending,
      sym_marker_task_done,
      sym_marker_property_info,
      sym_marker_property_label,
  [1682] = 1,
    ACTIONS(221), 8,
      sym__section_in,
      sym__section_out,
      sym__section_sibling,
      sym__eof,
      sym_marker_task_pending,
      sym_marker_task_done,
      sym_marker_property_info,
      sym_marker_property_label,
  [1693] = 1,
    ACTIONS(223), 8,
      sym__section_in,
      sym__section_out,
      sym__section_sibling,
      sym__eof,
      sym_marker_task_pending,
      sym_marker_task_done,
      sym_marker_property_info,
      sym_marker_property_label,
  [1704] = 1,
    ACTIONS(221), 7,
      sym__section_in,
      sym__eof,
      sym_section_header,
      sym_marker_task_pending,
      sym_marker_task_done,
      sym_marker_property_info,
      sym_marker_property_label,
  [1714] = 1,
    ACTIONS(219), 7,
      sym__section_in,
      sym__eof,
      sym_section_header,
      sym_marker_task_pending,
      sym_marker_task_done,
      sym_marker_property_info,
      sym_marker_property_label,
  [1724] = 1,
    ACTIONS(223), 7,
      sym__section_in,
      sym__eof,
      sym_section_header,
      sym_marker_task_pending,
      sym_marker_task_done,
      sym_marker_property_info,
      sym_marker_property_label,
  [1734] = 3,
    ACTIONS(225), 1,
      sym_section_header,
    STATE(80), 2,
      sym_section,
      aux_sym_section_children_repeat1,
    ACTIONS(227), 3,
      sym__section_out,
      sym__section_sibling,
      sym__eof,
  [1747] = 3,
    ACTIONS(229), 1,
      sym_section_header,
    STATE(80), 2,
      sym_section,
      aux_sym_section_children_repeat1,
    ACTIONS(232), 3,
      sym__section_out,
      sym__section_sibling,
      sym__eof,
  [1760] = 4,
    ACTIONS(234), 1,
      sym_section_header,
    ACTIONS(237), 1,
      sym__section_in,
    ACTIONS(240), 1,
      sym__eof,
    STATE(81), 2,
      sym_section,
      aux_sym_document_repeat2,
  [1774] = 4,
    ACTIONS(15), 1,
      sym__section_in,
    ACTIONS(147), 1,
      sym_section_header,
    ACTIONS(242), 1,
      sym__eof,
    STATE(81), 2,
      sym_section,
      aux_sym_document_repeat2,
  [1788] = 4,
    ACTIONS(15), 1,
      sym__section_in,
    ACTIONS(147), 1,
      sym_section_header,
    ACTIONS(155), 1,
      sym__eof,
    STATE(81), 2,
      sym_section,
      aux_sym_document_repeat2,
  [1802] = 4,
    ACTIONS(15), 1,
      sym__section_in,
    ACTIONS(147), 1,
      sym_section_header,
    ACTIONS(153), 1,
      sym__eof,
    STATE(81), 2,
      sym_section,
      aux_sym_document_repeat2,
  [1816] = 3,
    STATE(101), 1,
      aux_sym__lines,
    STATE(156), 1,
      sym_code_block_content,
    ACTIONS(244), 2,
      sym__line,
      sym__newline,
  [1827] = 3,
    STATE(101), 1,
      aux_sym__lines,
    STATE(136), 1,
      sym_code_block_content,
    ACTIONS(244), 2,
      sym__line,
      sym__newline,
  [1838] = 3,
    ACTIONS(127), 1,
      anon_sym_LF_BQUOTE_BQUOTE_BQUOTE_LF,
    STATE(87), 1,
      aux_sym__lines,
    ACTIONS(246), 2,
      sym__line,
      sym__newline,
  [1849] = 3,
    STATE(101), 1,
      aux_sym__lines,
    STATE(130), 1,
      sym_code_block_content,
    ACTIONS(244), 2,
      sym__line,
      sym__newline,
  [1860] = 1,
    ACTIONS(249), 4,
      sym__section_out,
      sym__section_sibling,
      sym__eof,
      sym_section_header,
  [1867] = 1,
    ACTIONS(251), 4,
      sym__section_out,
      sym__section_sibling,
      sym__eof,
      sym_section_header,
  [1874] = 1,
    ACTIONS(253), 4,
      sym__section_out,
      sym__section_sibling,
      sym__eof,
      sym_section_header,
  [1881] = 3,
    STATE(101), 1,
      aux_sym__lines,
    STATE(137), 1,
      sym_code_block_content,
    ACTIONS(244), 2,
      sym__line,
      sym__newline,
  [1892] = 3,
    STATE(101), 1,
      aux_sym__lines,
    STATE(124), 1,
      sym_code_block_content,
    ACTIONS(244), 2,
      sym__line,
      sym__newline,
  [1903] = 3,
    STATE(101), 1,
      aux_sym__lines,
    STATE(126), 1,
      sym_code_block_content,
    ACTIONS(244), 2,
      sym__line,
      sym__newline,
  [1914] = 3,
    STATE(101), 1,
      aux_sym__lines,
    STATE(145), 1,
      sym_code_block_content,
    ACTIONS(244), 2,
      sym__line,
      sym__newline,
  [1925] = 3,
    STATE(101), 1,
      aux_sym__lines,
    STATE(128), 1,
      sym_code_block_content,
    ACTIONS(244), 2,
      sym__line,
      sym__newline,
  [1936] = 1,
    ACTIONS(255), 4,
      sym__section_out,
      sym__section_sibling,
      sym__eof,
      sym_section_header,
  [1943] = 3,
    STATE(101), 1,
      aux_sym__lines,
    STATE(133), 1,
      sym_code_block_content,
    ACTIONS(244), 2,
      sym__line,
      sym__newline,
  [1954] = 3,
    STATE(101), 1,
      aux_sym__lines,
    STATE(132), 1,
      sym_code_block_content,
    ACTIONS(244), 2,
      sym__line,
      sym__newline,
  [1965] = 3,
    STATE(101), 1,
      aux_sym__lines,
    STATE(131), 1,
      sym_code_block_content,
    ACTIONS(244), 2,
      sym__line,
      sym__newline,
  [1976] = 3,
    ACTIONS(259), 1,
      anon_sym_LF_BQUOTE_BQUOTE_BQUOTE_LF,
    STATE(87), 1,
      aux_sym__lines,
    ACTIONS(257), 2,
      sym__line,
      sym__newline,
  [1987] = 3,
    STATE(101), 1,
      aux_sym__lines,
    STATE(134), 1,
      sym_code_block_content,
    ACTIONS(244), 2,
      sym__line,
      sym__newline,
  [1998] = 1,
    ACTIONS(157), 3,
      sym__section_out,
      sym__section_sibling,
      sym__eof,
  [2004] = 2,
    ACTIONS(225), 1,
      sym_section_header,
    STATE(79), 2,
      sym_section,
      aux_sym_section_children_repeat1,
  [2012] = 1,
    ACTIONS(240), 3,
      sym__section_in,
      sym__eof,
      sym_section_header,
  [2018] = 1,
    ACTIONS(249), 3,
      sym__section_in,
      sym__eof,
      sym_section_header,
  [2024] = 1,
    ACTIONS(261), 3,
      sym__section_out,
      sym__section_sibling,
      sym__eof,
  [2030] = 1,
    ACTIONS(166), 3,
      sym__section_out,
      sym__section_sibling,
      sym__eof,
  [2036] = 1,
    ACTIONS(255), 3,
      sym__section_in,
      sym__eof,
      sym_section_header,
  [2042] = 1,
    ACTIONS(170), 3,
      sym__section_out,
      sym__section_sibling,
      sym__eof,
  [2048] = 1,
    ACTIONS(263), 3,
      sym__section_out,
      sym__section_sibling,
      sym__eof,
  [2054] = 1,
    ACTIONS(253), 3,
      sym__section_in,
      sym__eof,
      sym_section_header,
  [2060] = 1,
    ACTIONS(186), 3,
      sym__section_out,
      sym__section_sibling,
      sym__eof,
  [2066] = 1,
    ACTIONS(251), 3,
      sym__section_in,
      sym__eof,
      sym_section_header,
  [2072] = 2,
    ACTIONS(265), 1,
      sym__line,
    STATE(150), 1,
      sym_code_block_language,
  [2079] = 2,
    ACTIONS(147), 1,
      sym_section_header,
    STATE(105), 1,
      sym_section,
  [2086] = 2,
    ACTIONS(265), 1,
      sym__line,
    STATE(152), 1,
      sym_code_block_language,
  [2093] = 2,
    ACTIONS(265), 1,
      sym__line,
    STATE(147), 1,
      sym_code_block_language,
  [2100] = 2,
    ACTIONS(265), 1,
      sym__line,
    STATE(148), 1,
      sym_code_block_language,
  [2107] = 2,
    ACTIONS(265), 1,
      sym__line,
    STATE(151), 1,
      sym_code_block_language,
  [2114] = 2,
    ACTIONS(265), 1,
      sym__line,
    STATE(149), 1,
      sym_code_block_language,
  [2121] = 1,
    ACTIONS(267), 1,
      sym_content,
  [2125] = 1,
    ACTIONS(269), 1,
      sym__newline,
  [2129] = 1,
    ACTIONS(271), 1,
      anon_sym_LF_BQUOTE_BQUOTE_BQUOTE_LF,
  [2133] = 1,
    ACTIONS(273), 1,
      ts_builtin_sym_end,
  [2137] = 1,
    ACTIONS(275), 1,
      anon_sym_LF_BQUOTE_BQUOTE_BQUOTE_LF,
  [2141] = 1,
    ACTIONS(277), 1,
      sym__newline,
  [2145] = 1,
    ACTIONS(279), 1,
      anon_sym_LF_BQUOTE_BQUOTE_BQUOTE_LF,
  [2149] = 1,
    ACTIONS(281), 1,
      sym__newline,
  [2153] = 1,
    ACTIONS(283), 1,
      anon_sym_LF_BQUOTE_BQUOTE_BQUOTE_LF,
  [2157] = 1,
    ACTIONS(285), 1,
      anon_sym_LF_BQUOTE_BQUOTE_BQUOTE_LF,
  [2161] = 1,
    ACTIONS(287), 1,
      anon_sym_LF_BQUOTE_BQUOTE_BQUOTE_LF,
  [2165] = 1,
    ACTIONS(289), 1,
      anon_sym_LF_BQUOTE_BQUOTE_BQUOTE_LF,
  [2169] = 1,
    ACTIONS(291), 1,
      anon_sym_LF_BQUOTE_BQUOTE_BQUOTE_LF,
  [2173] = 1,
    ACTIONS(293), 1,
      sym_content,
  [2177] = 1,
    ACTIONS(295), 1,
      anon_sym_LF_BQUOTE_BQUOTE_BQUOTE_LF,
  [2181] = 1,
    ACTIONS(297), 1,
      anon_sym_LF_BQUOTE_BQUOTE_BQUOTE_LF,
  [2185] = 1,
    ACTIONS(299), 1,
      sym_content,
  [2189] = 1,
    ACTIONS(301), 1,
      ts_builtin_sym_end,
  [2193] = 1,
    ACTIONS(303), 1,
      sym_content,
  [2197] = 1,
    ACTIONS(305), 1,
      sym_content,
  [2201] = 1,
    ACTIONS(307), 1,
      sym_content,
  [2205] = 1,
    ACTIONS(309), 1,
      ts_builtin_sym_end,
  [2209] = 1,
    ACTIONS(311), 1,
      sym_content,
  [2213] = 1,
    ACTIONS(313), 1,
      anon_sym_LF_BQUOTE_BQUOTE_BQUOTE_LF,
  [2217] = 1,
    ACTIONS(315), 1,
      anon_sym_LF,
  [2221] = 1,
    ACTIONS(317), 1,
      anon_sym_LF,
  [2225] = 1,
    ACTIONS(319), 1,
      anon_sym_LF,
  [2229] = 1,
    ACTIONS(321), 1,
      anon_sym_LF,
  [2233] = 1,
    ACTIONS(323), 1,
      anon_sym_LF,
  [2237] = 1,
    ACTIONS(325), 1,
      anon_sym_LF,
  [2241] = 1,
    ACTIONS(327), 1,
      anon_sym_LF,
  [2245] = 1,
    ACTIONS(329), 1,
      sym__newline,
  [2249] = 1,
    ACTIONS(331), 1,
      ts_builtin_sym_end,
  [2253] = 1,
    ACTIONS(333), 1,
      ts_builtin_sym_end,
  [2257] = 1,
    ACTIONS(335), 1,
      anon_sym_LF_BQUOTE_BQUOTE_BQUOTE_LF,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(4)] = 0,
  [SMALL_STATE(5)] = 30,
  [SMALL_STATE(6)] = 60,
  [SMALL_STATE(7)] = 90,
  [SMALL_STATE(8)] = 125,
  [SMALL_STATE(9)] = 154,
  [SMALL_STATE(10)] = 183,
  [SMALL_STATE(11)] = 212,
  [SMALL_STATE(12)] = 241,
  [SMALL_STATE(13)] = 270,
  [SMALL_STATE(14)] = 299,
  [SMALL_STATE(15)] = 333,
  [SMALL_STATE(16)] = 367,
  [SMALL_STATE(17)] = 395,
  [SMALL_STATE(18)] = 423,
  [SMALL_STATE(19)] = 451,
  [SMALL_STATE(20)] = 475,
  [SMALL_STATE(21)] = 503,
  [SMALL_STATE(22)] = 531,
  [SMALL_STATE(23)] = 559,
  [SMALL_STATE(24)] = 592,
  [SMALL_STATE(25)] = 625,
  [SMALL_STATE(26)] = 656,
  [SMALL_STATE(27)] = 683,
  [SMALL_STATE(28)] = 706,
  [SMALL_STATE(29)] = 729,
  [SMALL_STATE(30)] = 760,
  [SMALL_STATE(31)] = 791,
  [SMALL_STATE(32)] = 818,
  [SMALL_STATE(33)] = 849,
  [SMALL_STATE(34)] = 874,
  [SMALL_STATE(35)] = 901,
  [SMALL_STATE(36)] = 920,
  [SMALL_STATE(37)] = 951,
  [SMALL_STATE(38)] = 970,
  [SMALL_STATE(39)] = 997,
  [SMALL_STATE(40)] = 1020,
  [SMALL_STATE(41)] = 1051,
  [SMALL_STATE(42)] = 1084,
  [SMALL_STATE(43)] = 1117,
  [SMALL_STATE(44)] = 1139,
  [SMALL_STATE(45)] = 1157,
  [SMALL_STATE(46)] = 1179,
  [SMALL_STATE(47)] = 1205,
  [SMALL_STATE(48)] = 1223,
  [SMALL_STATE(49)] = 1245,
  [SMALL_STATE(50)] = 1269,
  [SMALL_STATE(51)] = 1287,
  [SMALL_STATE(52)] = 1305,
  [SMALL_STATE(53)] = 1331,
  [SMALL_STATE(54)] = 1348,
  [SMALL_STATE(55)] = 1365,
  [SMALL_STATE(56)] = 1386,
  [SMALL_STATE(57)] = 1403,
  [SMALL_STATE(58)] = 1428,
  [SMALL_STATE(59)] = 1445,
  [SMALL_STATE(60)] = 1461,
  [SMALL_STATE(61)] = 1477,
  [SMALL_STATE(62)] = 1495,
  [SMALL_STATE(63)] = 1512,
  [SMALL_STATE(64)] = 1529,
  [SMALL_STATE(65)] = 1549,
  [SMALL_STATE(66)] = 1569,
  [SMALL_STATE(67)] = 1589,
  [SMALL_STATE(68)] = 1601,
  [SMALL_STATE(69)] = 1613,
  [SMALL_STATE(70)] = 1629,
  [SMALL_STATE(71)] = 1649,
  [SMALL_STATE(72)] = 1660,
  [SMALL_STATE(73)] = 1671,
  [SMALL_STATE(74)] = 1682,
  [SMALL_STATE(75)] = 1693,
  [SMALL_STATE(76)] = 1704,
  [SMALL_STATE(77)] = 1714,
  [SMALL_STATE(78)] = 1724,
  [SMALL_STATE(79)] = 1734,
  [SMALL_STATE(80)] = 1747,
  [SMALL_STATE(81)] = 1760,
  [SMALL_STATE(82)] = 1774,
  [SMALL_STATE(83)] = 1788,
  [SMALL_STATE(84)] = 1802,
  [SMALL_STATE(85)] = 1816,
  [SMALL_STATE(86)] = 1827,
  [SMALL_STATE(87)] = 1838,
  [SMALL_STATE(88)] = 1849,
  [SMALL_STATE(89)] = 1860,
  [SMALL_STATE(90)] = 1867,
  [SMALL_STATE(91)] = 1874,
  [SMALL_STATE(92)] = 1881,
  [SMALL_STATE(93)] = 1892,
  [SMALL_STATE(94)] = 1903,
  [SMALL_STATE(95)] = 1914,
  [SMALL_STATE(96)] = 1925,
  [SMALL_STATE(97)] = 1936,
  [SMALL_STATE(98)] = 1943,
  [SMALL_STATE(99)] = 1954,
  [SMALL_STATE(100)] = 1965,
  [SMALL_STATE(101)] = 1976,
  [SMALL_STATE(102)] = 1987,
  [SMALL_STATE(103)] = 1998,
  [SMALL_STATE(104)] = 2004,
  [SMALL_STATE(105)] = 2012,
  [SMALL_STATE(106)] = 2018,
  [SMALL_STATE(107)] = 2024,
  [SMALL_STATE(108)] = 2030,
  [SMALL_STATE(109)] = 2036,
  [SMALL_STATE(110)] = 2042,
  [SMALL_STATE(111)] = 2048,
  [SMALL_STATE(112)] = 2054,
  [SMALL_STATE(113)] = 2060,
  [SMALL_STATE(114)] = 2066,
  [SMALL_STATE(115)] = 2072,
  [SMALL_STATE(116)] = 2079,
  [SMALL_STATE(117)] = 2086,
  [SMALL_STATE(118)] = 2093,
  [SMALL_STATE(119)] = 2100,
  [SMALL_STATE(120)] = 2107,
  [SMALL_STATE(121)] = 2114,
  [SMALL_STATE(122)] = 2121,
  [SMALL_STATE(123)] = 2125,
  [SMALL_STATE(124)] = 2129,
  [SMALL_STATE(125)] = 2133,
  [SMALL_STATE(126)] = 2137,
  [SMALL_STATE(127)] = 2141,
  [SMALL_STATE(128)] = 2145,
  [SMALL_STATE(129)] = 2149,
  [SMALL_STATE(130)] = 2153,
  [SMALL_STATE(131)] = 2157,
  [SMALL_STATE(132)] = 2161,
  [SMALL_STATE(133)] = 2165,
  [SMALL_STATE(134)] = 2169,
  [SMALL_STATE(135)] = 2173,
  [SMALL_STATE(136)] = 2177,
  [SMALL_STATE(137)] = 2181,
  [SMALL_STATE(138)] = 2185,
  [SMALL_STATE(139)] = 2189,
  [SMALL_STATE(140)] = 2193,
  [SMALL_STATE(141)] = 2197,
  [SMALL_STATE(142)] = 2201,
  [SMALL_STATE(143)] = 2205,
  [SMALL_STATE(144)] = 2209,
  [SMALL_STATE(145)] = 2213,
  [SMALL_STATE(146)] = 2217,
  [SMALL_STATE(147)] = 2221,
  [SMALL_STATE(148)] = 2225,
  [SMALL_STATE(149)] = 2229,
  [SMALL_STATE(150)] = 2233,
  [SMALL_STATE(151)] = 2237,
  [SMALL_STATE(152)] = 2241,
  [SMALL_STATE(153)] = 2245,
  [SMALL_STATE(154)] = 2249,
  [SMALL_STATE(155)] = 2253,
  [SMALL_STATE(156)] = 2257,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = false}}, SHIFT(2),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT(140),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(142),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(31),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(95),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(117),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(116),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(125),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(16),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(86),
  [23] = {.entry = {.count = 1, .reusable = false}}, SHIFT(118),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(104),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(106),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(89),
  [31] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_body, 2, 0, 0),
  [33] = {.entry = {.count = 1, .reusable = false}}, SHIFT(6),
  [35] = {.entry = {.count = 1, .reusable = false}}, SHIFT(99),
  [37] = {.entry = {.count = 1, .reusable = false}}, SHIFT(120),
  [39] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_body, 2, 0, 0),
  [41] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_body, 1, 0, 0),
  [43] = {.entry = {.count = 1, .reusable = false}}, SHIFT(4),
  [45] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_body, 1, 0, 0),
  [47] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_body_repeat1, 2, 0, 0),
  [49] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_body_repeat1, 2, 0, 0), SHIFT_REPEAT(6),
  [52] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_body_repeat1, 2, 0, 0), SHIFT_REPEAT(99),
  [55] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_body_repeat1, 2, 0, 0), SHIFT_REPEAT(120),
  [58] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_body_repeat1, 2, 0, 0),
  [60] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_item, 3, 0, 0),
  [62] = {.entry = {.count = 1, .reusable = false}}, SHIFT(5),
  [64] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [66] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_item, 3, 0, 0),
  [68] = {.entry = {.count = 1, .reusable = false}}, SHIFT(9),
  [70] = {.entry = {.count = 1, .reusable = false}}, SHIFT(88),
  [72] = {.entry = {.count = 1, .reusable = false}}, SHIFT(115),
  [74] = {.entry = {.count = 1, .reusable = false}}, SHIFT(10),
  [76] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_body_repeat1, 2, 0, 0), SHIFT_REPEAT(10),
  [79] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_body_repeat1, 2, 0, 0), SHIFT_REPEAT(88),
  [82] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_body_repeat1, 2, 0, 0), SHIFT_REPEAT(115),
  [85] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_body_repeat1, 2, 0, 0), SHIFT_REPEAT(11),
  [88] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_body_repeat1, 2, 0, 0), SHIFT_REPEAT(94),
  [91] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_body_repeat1, 2, 0, 0), SHIFT_REPEAT(121),
  [94] = {.entry = {.count = 1, .reusable = false}}, SHIFT(11),
  [96] = {.entry = {.count = 1, .reusable = false}}, SHIFT(94),
  [98] = {.entry = {.count = 1, .reusable = false}}, SHIFT(121),
  [100] = {.entry = {.count = 1, .reusable = false}}, SHIFT(12),
  [102] = {.entry = {.count = 1, .reusable = false}}, SHIFT(13),
  [104] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [106] = {.entry = {.count = 1, .reusable = false}}, SHIFT(8),
  [108] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [110] = {.entry = {.count = 1, .reusable = false}}, SHIFT(21),
  [112] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_body_repeat1, 2, 0, 0), SHIFT_REPEAT(17),
  [115] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_body_repeat1, 2, 0, 0), SHIFT_REPEAT(92),
  [118] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_body_repeat1, 2, 0, 0), SHIFT_REPEAT(119),
  [121] = {.entry = {.count = 1, .reusable = false}}, SHIFT(17),
  [123] = {.entry = {.count = 1, .reusable = false}}, SHIFT(92),
  [125] = {.entry = {.count = 1, .reusable = false}}, SHIFT(119),
  [127] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym__lines, 2, 0, 0),
  [129] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__lines, 2, 0, 0), SHIFT_REPEAT(19),
  [132] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__lines, 2, 0, 0),
  [134] = {.entry = {.count = 1, .reusable = false}}, SHIFT(18),
  [136] = {.entry = {.count = 1, .reusable = false}}, SHIFT(22),
  [138] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_body_repeat1, 2, 0, 0), SHIFT_REPEAT(22),
  [141] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_body_repeat1, 2, 0, 0), SHIFT_REPEAT(86),
  [144] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_body_repeat1, 2, 0, 0), SHIFT_REPEAT(118),
  [147] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [149] = {.entry = {.count = 1, .reusable = true}}, SHIFT(140),
  [151] = {.entry = {.count = 1, .reusable = true}}, SHIFT(142),
  [153] = {.entry = {.count = 1, .reusable = true}}, SHIFT(155),
  [155] = {.entry = {.count = 1, .reusable = true}}, SHIFT(154),
  [157] = {.entry = {.count = 1, .reusable = true}}, SHIFT(112),
  [159] = {.entry = {.count = 1, .reusable = false}}, SHIFT(38),
  [161] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__lines, 2, 0, 0), SHIFT_REPEAT(27),
  [164] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_children, 2, 0, 0),
  [166] = {.entry = {.count = 1, .reusable = true}}, SHIFT(91),
  [168] = {.entry = {.count = 1, .reusable = false}}, SHIFT(26),
  [170] = {.entry = {.count = 1, .reusable = true}}, SHIFT(90),
  [172] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [174] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(140),
  [177] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(142),
  [180] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0),
  [182] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_code_block, 5, 0, 0),
  [184] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_code_block, 5, 0, 0),
  [186] = {.entry = {.count = 1, .reusable = true}}, SHIFT(114),
  [188] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_code_block, 3, 0, 0),
  [190] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_code_block, 3, 0, 0),
  [192] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_body_repeat1, 2, 0, 0), SHIFT_REPEAT(38),
  [195] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_body_repeat1, 2, 0, 0), SHIFT_REPEAT(95),
  [198] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_body_repeat1, 2, 0, 0), SHIFT_REPEAT(117),
  [201] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__lines, 2, 0, 0), SHIFT_REPEAT(39),
  [204] = {.entry = {.count = 1, .reusable = false}}, SHIFT(20),
  [206] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [208] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__lines, 2, 0, 0), SHIFT_REPEAT(45),
  [211] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__lines, 2, 0, 0), SHIFT_REPEAT(48),
  [214] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [216] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__lines, 2, 0, 0), SHIFT_REPEAT(55),
  [219] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_item, 4, 0, 0),
  [221] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_item, 5, 0, 0),
  [223] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_children, 3, 0, 0),
  [225] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [227] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_section_children, 2, 0, 0),
  [229] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_section_children_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [232] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_section_children_repeat1, 2, 0, 0),
  [234] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat2, 2, 0, 0), SHIFT_REPEAT(2),
  [237] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat2, 2, 0, 0), SHIFT_REPEAT(116),
  [240] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_document_repeat2, 2, 0, 0),
  [242] = {.entry = {.count = 1, .reusable = true}}, SHIFT(139),
  [244] = {.entry = {.count = 1, .reusable = false}}, SHIFT(101),
  [246] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__lines, 2, 0, 0), SHIFT_REPEAT(87),
  [249] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_section, 2, 0, 0),
  [251] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_section, 4, 0, 0),
  [253] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_section, 3, 0, 0),
  [255] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_section, 5, 0, 0),
  [257] = {.entry = {.count = 1, .reusable = false}}, SHIFT(87),
  [259] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_code_block_content, 1, 0, 0),
  [261] = {.entry = {.count = 1, .reusable = true}}, SHIFT(109),
  [263] = {.entry = {.count = 1, .reusable = true}}, SHIFT(97),
  [265] = {.entry = {.count = 1, .reusable = true}}, SHIFT(146),
  [267] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_marker, 1, 0, 0),
  [269] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [271] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [273] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 1, 0, 0),
  [275] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [277] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [279] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [281] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [283] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [285] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [287] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [289] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [291] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [293] = {.entry = {.count = 1, .reusable = true}}, SHIFT(129),
  [295] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [297] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [299] = {.entry = {.count = 1, .reusable = true}}, SHIFT(123),
  [301] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 4, 0, 0),
  [303] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_marker_task, 1, 0, 0),
  [305] = {.entry = {.count = 1, .reusable = true}}, SHIFT(127),
  [307] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_marker_property, 1, 0, 0),
  [309] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [311] = {.entry = {.count = 1, .reusable = true}}, SHIFT(153),
  [313] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [315] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_code_block_language, 1, 0, 0),
  [317] = {.entry = {.count = 1, .reusable = true}}, SHIFT(102),
  [319] = {.entry = {.count = 1, .reusable = true}}, SHIFT(93),
  [321] = {.entry = {.count = 1, .reusable = true}}, SHIFT(96),
  [323] = {.entry = {.count = 1, .reusable = true}}, SHIFT(100),
  [325] = {.entry = {.count = 1, .reusable = true}}, SHIFT(98),
  [327] = {.entry = {.count = 1, .reusable = true}}, SHIFT(85),
  [329] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [331] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 2, 0, 0),
  [333] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 3, 0, 0),
  [335] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
};

enum ts_external_scanner_symbol_identifiers {
  ts_external_token__indent = 0,
  ts_external_token__dedent = 1,
  ts_external_token__section_in = 2,
  ts_external_token__section_out = 3,
  ts_external_token__section_sibling = 4,
  ts_external_token__eof = 5,
};

static const TSSymbol ts_external_scanner_symbol_map[EXTERNAL_TOKEN_COUNT] = {
  [ts_external_token__indent] = sym__indent,
  [ts_external_token__dedent] = sym__dedent,
  [ts_external_token__section_in] = sym__section_in,
  [ts_external_token__section_out] = sym__section_out,
  [ts_external_token__section_sibling] = sym__section_sibling,
  [ts_external_token__eof] = sym__eof,
};

static const bool ts_external_scanner_states[10][EXTERNAL_TOKEN_COUNT] = {
  [1] = {
    [ts_external_token__indent] = true,
    [ts_external_token__dedent] = true,
    [ts_external_token__section_in] = true,
    [ts_external_token__section_out] = true,
    [ts_external_token__section_sibling] = true,
    [ts_external_token__eof] = true,
  },
  [2] = {
    [ts_external_token__section_in] = true,
    [ts_external_token__eof] = true,
  },
  [3] = {
    [ts_external_token__section_in] = true,
    [ts_external_token__section_out] = true,
    [ts_external_token__section_sibling] = true,
    [ts_external_token__eof] = true,
  },
  [4] = {
    [ts_external_token__indent] = true,
    [ts_external_token__dedent] = true,
    [ts_external_token__section_in] = true,
    [ts_external_token__eof] = true,
  },
  [5] = {
    [ts_external_token__indent] = true,
    [ts_external_token__section_in] = true,
    [ts_external_token__section_out] = true,
    [ts_external_token__section_sibling] = true,
    [ts_external_token__eof] = true,
  },
  [6] = {
    [ts_external_token__indent] = true,
    [ts_external_token__section_in] = true,
    [ts_external_token__eof] = true,
  },
  [7] = {
    [ts_external_token__dedent] = true,
    [ts_external_token__section_in] = true,
    [ts_external_token__section_out] = true,
    [ts_external_token__section_sibling] = true,
    [ts_external_token__eof] = true,
  },
  [8] = {
    [ts_external_token__dedent] = true,
    [ts_external_token__section_in] = true,
    [ts_external_token__eof] = true,
  },
  [9] = {
    [ts_external_token__section_out] = true,
    [ts_external_token__section_sibling] = true,
    [ts_external_token__eof] = true,
  },
};

#ifdef __cplusplus
extern "C" {
#endif
void *tree_sitter_note_external_scanner_create(void);
void tree_sitter_note_external_scanner_destroy(void *);
bool tree_sitter_note_external_scanner_scan(void *, TSLexer *, const bool *);
unsigned tree_sitter_note_external_scanner_serialize(void *, char *);
void tree_sitter_note_external_scanner_deserialize(void *, const char *, unsigned);

#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_note(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .external_scanner = {
      &ts_external_scanner_states[0][0],
      ts_external_scanner_symbol_map,
      tree_sitter_note_external_scanner_create,
      tree_sitter_note_external_scanner_destroy,
      tree_sitter_note_external_scanner_scan,
      tree_sitter_note_external_scanner_serialize,
      tree_sitter_note_external_scanner_deserialize,
    },
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
