#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 151
#define LARGE_STATE_COUNT 4
#define SYMBOL_COUNT 33
#define ALIAS_COUNT 0
#define TOKEN_COUNT 15
#define EXTERNAL_TOKEN_COUNT 6
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 6
#define PRODUCTION_ID_COUNT 1

enum ts_symbol_identifiers {
  sym_section_header = 1,
  sym_marker_task_pending = 2,
  sym_marker_task_done = 3,
  sym_marker_property_info = 4,
  sym_marker_property_label = 5,
  sym__line = 6,
  sym__newline = 7,
  anon_sym_BQUOTE_BQUOTE_BQUOTE = 8,
  sym__indent = 9,
  sym__dedent = 10,
  sym__section_in = 11,
  sym__section_out = 12,
  sym__section_sibling = 13,
  sym__eof = 14,
  sym_document = 15,
  sym_section_children = 16,
  sym_section = 17,
  sym_marker_task = 18,
  sym_marker_property = 19,
  sym_marker = 20,
  sym_content = 21,
  sym_body = 22,
  sym_item = 23,
  sym_children = 24,
  aux_sym__lines = 25,
  sym_code_block_language = 26,
  sym_code_block_content = 27,
  sym_code_block = 28,
  aux_sym_document_repeat1 = 29,
  aux_sym_document_repeat2 = 30,
  aux_sym_section_children_repeat1 = 31,
  aux_sym_body_repeat1 = 32,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_section_header] = "section_header",
  [sym_marker_task_pending] = "marker_task_pending",
  [sym_marker_task_done] = "marker_task_done",
  [sym_marker_property_info] = "marker_property_info",
  [sym_marker_property_label] = "marker_property_label",
  [sym__line] = "_line",
  [sym__newline] = "_newline",
  [anon_sym_BQUOTE_BQUOTE_BQUOTE] = "```",
  [sym__indent] = "_indent",
  [sym__dedent] = "_dedent",
  [sym__section_in] = "_section_in",
  [sym__section_out] = "_section_out",
  [sym__section_sibling] = "_section_sibling",
  [sym__eof] = "_eof",
  [sym_document] = "document",
  [sym_section_children] = "section_children",
  [sym_section] = "section",
  [sym_marker_task] = "marker_task",
  [sym_marker_property] = "marker_property",
  [sym_marker] = "marker",
  [sym_content] = "content",
  [sym_body] = "body",
  [sym_item] = "item",
  [sym_children] = "children",
  [aux_sym__lines] = "_lines",
  [sym_code_block_language] = "code_block_language",
  [sym_code_block_content] = "code_block_content",
  [sym_code_block] = "code_block",
  [aux_sym_document_repeat1] = "document_repeat1",
  [aux_sym_document_repeat2] = "document_repeat2",
  [aux_sym_section_children_repeat1] = "section_children_repeat1",
  [aux_sym_body_repeat1] = "body_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_section_header] = sym_section_header,
  [sym_marker_task_pending] = sym_marker_task_pending,
  [sym_marker_task_done] = sym_marker_task_done,
  [sym_marker_property_info] = sym_marker_property_info,
  [sym_marker_property_label] = sym_marker_property_label,
  [sym__line] = sym__line,
  [sym__newline] = sym__newline,
  [anon_sym_BQUOTE_BQUOTE_BQUOTE] = anon_sym_BQUOTE_BQUOTE_BQUOTE,
  [sym__indent] = sym__indent,
  [sym__dedent] = sym__dedent,
  [sym__section_in] = sym__section_in,
  [sym__section_out] = sym__section_out,
  [sym__section_sibling] = sym__section_sibling,
  [sym__eof] = sym__eof,
  [sym_document] = sym_document,
  [sym_section_children] = sym_section_children,
  [sym_section] = sym_section,
  [sym_marker_task] = sym_marker_task,
  [sym_marker_property] = sym_marker_property,
  [sym_marker] = sym_marker,
  [sym_content] = sym_content,
  [sym_body] = sym_body,
  [sym_item] = sym_item,
  [sym_children] = sym_children,
  [aux_sym__lines] = aux_sym__lines,
  [sym_code_block_language] = sym_code_block_language,
  [sym_code_block_content] = sym_code_block_content,
  [sym_code_block] = sym_code_block,
  [aux_sym_document_repeat1] = aux_sym_document_repeat1,
  [aux_sym_document_repeat2] = aux_sym_document_repeat2,
  [aux_sym_section_children_repeat1] = aux_sym_section_children_repeat1,
  [aux_sym_body_repeat1] = aux_sym_body_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_section_header] = {
    .visible = true,
    .named = true,
  },
  [sym_marker_task_pending] = {
    .visible = true,
    .named = true,
  },
  [sym_marker_task_done] = {
    .visible = true,
    .named = true,
  },
  [sym_marker_property_info] = {
    .visible = true,
    .named = true,
  },
  [sym_marker_property_label] = {
    .visible = true,
    .named = true,
  },
  [sym__line] = {
    .visible = false,
    .named = true,
  },
  [sym__newline] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_BQUOTE_BQUOTE_BQUOTE] = {
    .visible = true,
    .named = false,
  },
  [sym__indent] = {
    .visible = false,
    .named = true,
  },
  [sym__dedent] = {
    .visible = false,
    .named = true,
  },
  [sym__section_in] = {
    .visible = false,
    .named = true,
  },
  [sym__section_out] = {
    .visible = false,
    .named = true,
  },
  [sym__section_sibling] = {
    .visible = false,
    .named = true,
  },
  [sym__eof] = {
    .visible = false,
    .named = true,
  },
  [sym_document] = {
    .visible = true,
    .named = true,
  },
  [sym_section_children] = {
    .visible = true,
    .named = true,
  },
  [sym_section] = {
    .visible = true,
    .named = true,
  },
  [sym_marker_task] = {
    .visible = true,
    .named = true,
  },
  [sym_marker_property] = {
    .visible = true,
    .named = true,
  },
  [sym_marker] = {
    .visible = true,
    .named = true,
  },
  [sym_content] = {
    .visible = true,
    .named = true,
  },
  [sym_body] = {
    .visible = true,
    .named = true,
  },
  [sym_item] = {
    .visible = true,
    .named = true,
  },
  [sym_children] = {
    .visible = true,
    .named = true,
  },
  [aux_sym__lines] = {
    .visible = false,
    .named = false,
  },
  [sym_code_block_language] = {
    .visible = true,
    .named = true,
  },
  [sym_code_block_content] = {
    .visible = true,
    .named = true,
  },
  [sym_code_block] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_document_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_document_repeat2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_section_children_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_body_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 2,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 6,
  [8] = 4,
  [9] = 5,
  [10] = 10,
  [11] = 6,
  [12] = 4,
  [13] = 5,
  [14] = 14,
  [15] = 14,
  [16] = 16,
  [17] = 4,
  [18] = 18,
  [19] = 10,
  [20] = 5,
  [21] = 10,
  [22] = 6,
  [23] = 6,
  [24] = 24,
  [25] = 24,
  [26] = 18,
  [27] = 5,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 16,
  [32] = 4,
  [33] = 28,
  [34] = 34,
  [35] = 10,
  [36] = 29,
  [37] = 28,
  [38] = 29,
  [39] = 39,
  [40] = 16,
  [41] = 16,
  [42] = 29,
  [43] = 34,
  [44] = 34,
  [45] = 45,
  [46] = 39,
  [47] = 39,
  [48] = 28,
  [49] = 28,
  [50] = 34,
  [51] = 51,
  [52] = 39,
  [53] = 34,
  [54] = 45,
  [55] = 39,
  [56] = 45,
  [57] = 45,
  [58] = 51,
  [59] = 51,
  [60] = 60,
  [61] = 51,
  [62] = 60,
  [63] = 63,
  [64] = 64,
  [65] = 60,
  [66] = 60,
  [67] = 63,
  [68] = 64,
  [69] = 69,
  [70] = 64,
  [71] = 63,
  [72] = 69,
  [73] = 63,
  [74] = 64,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 80,
  [84] = 84,
  [85] = 80,
  [86] = 86,
  [87] = 84,
  [88] = 84,
  [89] = 80,
  [90] = 80,
  [91] = 91,
  [92] = 84,
  [93] = 84,
  [94] = 94,
  [95] = 86,
  [96] = 96,
  [97] = 82,
  [98] = 98,
  [99] = 81,
  [100] = 96,
  [101] = 101,
  [102] = 102,
  [103] = 96,
  [104] = 102,
  [105] = 98,
  [106] = 106,
  [107] = 101,
  [108] = 28,
  [109] = 96,
  [110] = 91,
  [111] = 96,
  [112] = 112,
  [113] = 113,
  [114] = 113,
  [115] = 115,
  [116] = 113,
  [117] = 113,
  [118] = 118,
  [119] = 119,
  [120] = 120,
  [121] = 121,
  [122] = 122,
  [123] = 120,
  [124] = 121,
  [125] = 120,
  [126] = 121,
  [127] = 127,
  [128] = 118,
  [129] = 127,
  [130] = 118,
  [131] = 127,
  [132] = 120,
  [133] = 127,
  [134] = 118,
  [135] = 135,
  [136] = 136,
  [137] = 137,
  [138] = 138,
  [139] = 121,
  [140] = 121,
  [141] = 118,
  [142] = 120,
  [143] = 127,
  [144] = 144,
  [145] = 145,
  [146] = 144,
  [147] = 144,
  [148] = 144,
  [149] = 149,
  [150] = 144,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(17);
      if (lookahead == '\n') ADVANCE(39);
      if (lookahead == '#') ADVANCE(31);
      if (lookahead == '*') ADVANCE(27);
      if (lookahead == '-') ADVANCE(28);
      if (lookahead == '.') ADVANCE(29);
      if (lookahead == '[') ADVANCE(30);
      if (lookahead == '`') ADVANCE(35);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(23);
      if (lookahead != 0) ADVANCE(37);
      END_STATE();
    case 1:
      if (lookahead == '\n') ADVANCE(18);
      if (lookahead != 0) ADVANCE(1);
      END_STATE();
    case 2:
      if (lookahead == '\n') SKIP(2);
      if (lookahead == '*') ADVANCE(27);
      if (lookahead == '-') ADVANCE(28);
      if (lookahead == '.') ADVANCE(29);
      if (lookahead == '[') ADVANCE(30);
      if (lookahead == '`') ADVANCE(35);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(33);
      if (lookahead != 0) ADVANCE(37);
      END_STATE();
    case 3:
      if (lookahead == '\n') ADVANCE(40);
      if (lookahead == '*') ADVANCE(27);
      if (lookahead == '-') ADVANCE(28);
      if (lookahead == '.') ADVANCE(29);
      if (lookahead == '[') ADVANCE(30);
      if (lookahead == '`') ADVANCE(35);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(25);
      if (lookahead != 0) ADVANCE(37);
      END_STATE();
    case 4:
      if (lookahead == '\n') SKIP(4);
      if (lookahead == '#') ADVANCE(31);
      if (lookahead == '*') ADVANCE(27);
      if (lookahead == '-') ADVANCE(28);
      if (lookahead == '.') ADVANCE(29);
      if (lookahead == '[') ADVANCE(30);
      if (lookahead == '`') ADVANCE(35);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(32);
      if (lookahead != 0) ADVANCE(37);
      END_STATE();
    case 5:
      if (lookahead == '\n') ADVANCE(41);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(26);
      if (lookahead != 0) ADVANCE(37);
      END_STATE();
    case 6:
      if (lookahead == '\n') SKIP(6);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(36);
      if (lookahead != 0) ADVANCE(37);
      END_STATE();
    case 7:
      if (lookahead == '\n') ADVANCE(42);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(7);
      END_STATE();
    case 8:
      if (lookahead == ' ') ADVANCE(21);
      END_STATE();
    case 9:
      if (lookahead == ' ') ADVANCE(19);
      END_STATE();
    case 10:
      if (lookahead == ' ') ADVANCE(20);
      END_STATE();
    case 11:
      if (lookahead == ' ') ADVANCE(22);
      END_STATE();
    case 12:
      if (lookahead == ' ') ADVANCE(16);
      if (lookahead == '#') ADVANCE(12);
      END_STATE();
    case 13:
      if (lookahead == '#') ADVANCE(12);
      if (lookahead == '*') ADVANCE(8);
      if (lookahead == '-') ADVANCE(9);
      if (lookahead == '.') ADVANCE(10);
      if (lookahead == '[') ADVANCE(11);
      if (lookahead == '`') ADVANCE(15);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(13);
      END_STATE();
    case 14:
      if (lookahead == '`') ADVANCE(43);
      END_STATE();
    case 15:
      if (lookahead == '`') ADVANCE(14);
      END_STATE();
    case 16:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(1);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(sym_section_header);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(sym_marker_task_pending);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(sym_marker_task_done);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(sym_marker_property_info);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(sym_marker_property_label);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(sym__line);
      if (lookahead == '\n') ADVANCE(39);
      if (lookahead == '#') ADVANCE(31);
      if (lookahead == '*') ADVANCE(27);
      if (lookahead == '-') ADVANCE(28);
      if (lookahead == '.') ADVANCE(29);
      if (lookahead == '[') ADVANCE(30);
      if (lookahead == '`') ADVANCE(35);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(23);
      if (lookahead != 0) ADVANCE(37);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(sym__line);
      if (lookahead == '\n') ADVANCE(18);
      if (lookahead != 0) ADVANCE(24);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(sym__line);
      if (lookahead == '\n') ADVANCE(40);
      if (lookahead == '*') ADVANCE(27);
      if (lookahead == '-') ADVANCE(28);
      if (lookahead == '.') ADVANCE(29);
      if (lookahead == '[') ADVANCE(30);
      if (lookahead == '`') ADVANCE(35);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(25);
      if (lookahead != 0) ADVANCE(37);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(sym__line);
      if (lookahead == '\n') ADVANCE(41);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(26);
      if (lookahead != 0) ADVANCE(37);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(sym__line);
      if (lookahead == ' ') ADVANCE(21);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(37);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(sym__line);
      if (lookahead == ' ') ADVANCE(19);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(37);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(sym__line);
      if (lookahead == ' ') ADVANCE(20);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(37);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(sym__line);
      if (lookahead == ' ') ADVANCE(22);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(37);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(sym__line);
      if (lookahead == ' ') ADVANCE(38);
      if (lookahead == '#') ADVANCE(31);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(37);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(sym__line);
      if (lookahead == '#') ADVANCE(31);
      if (lookahead == '*') ADVANCE(27);
      if (lookahead == '-') ADVANCE(28);
      if (lookahead == '.') ADVANCE(29);
      if (lookahead == '[') ADVANCE(30);
      if (lookahead == '`') ADVANCE(35);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(32);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(37);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(sym__line);
      if (lookahead == '*') ADVANCE(27);
      if (lookahead == '-') ADVANCE(28);
      if (lookahead == '.') ADVANCE(29);
      if (lookahead == '[') ADVANCE(30);
      if (lookahead == '`') ADVANCE(35);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(33);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(37);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(sym__line);
      if (lookahead == '`') ADVANCE(43);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(37);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(sym__line);
      if (lookahead == '`') ADVANCE(34);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(37);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(sym__line);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(36);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(37);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(sym__line);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(37);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(sym__line);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(24);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(sym__newline);
      if (lookahead == '\n') ADVANCE(39);
      if (lookahead == '#') ADVANCE(31);
      if (lookahead == '*') ADVANCE(27);
      if (lookahead == '-') ADVANCE(28);
      if (lookahead == '.') ADVANCE(29);
      if (lookahead == '[') ADVANCE(30);
      if (lookahead == '`') ADVANCE(35);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(23);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(sym__newline);
      if (lookahead == '\n') ADVANCE(40);
      if (lookahead == '*') ADVANCE(27);
      if (lookahead == '-') ADVANCE(28);
      if (lookahead == '.') ADVANCE(29);
      if (lookahead == '[') ADVANCE(30);
      if (lookahead == '`') ADVANCE(35);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(25);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(sym__newline);
      if (lookahead == '\n') ADVANCE(41);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(26);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(sym__newline);
      if (lookahead == '\n') ADVANCE(42);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(anon_sym_BQUOTE_BQUOTE_BQUOTE);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0, .external_lex_state = 1},
  [1] = {.lex_state = 13, .external_lex_state = 2},
  [2] = {.lex_state = 2, .external_lex_state = 3},
  [3] = {.lex_state = 2, .external_lex_state = 3},
  [4] = {.lex_state = 3, .external_lex_state = 1},
  [5] = {.lex_state = 3, .external_lex_state = 1},
  [6] = {.lex_state = 3, .external_lex_state = 1},
  [7] = {.lex_state = 3, .external_lex_state = 4},
  [8] = {.lex_state = 0, .external_lex_state = 5},
  [9] = {.lex_state = 0, .external_lex_state = 5},
  [10] = {.lex_state = 2, .external_lex_state = 1},
  [11] = {.lex_state = 0, .external_lex_state = 5},
  [12] = {.lex_state = 3, .external_lex_state = 4},
  [13] = {.lex_state = 3, .external_lex_state = 4},
  [14] = {.lex_state = 13, .external_lex_state = 3},
  [15] = {.lex_state = 13, .external_lex_state = 3},
  [16] = {.lex_state = 13, .external_lex_state = 6},
  [17] = {.lex_state = 0, .external_lex_state = 7},
  [18] = {.lex_state = 13, .external_lex_state = 3},
  [19] = {.lex_state = 4, .external_lex_state = 5},
  [20] = {.lex_state = 0, .external_lex_state = 7},
  [21] = {.lex_state = 2, .external_lex_state = 4},
  [22] = {.lex_state = 3, .external_lex_state = 3},
  [23] = {.lex_state = 0, .external_lex_state = 7},
  [24] = {.lex_state = 13, .external_lex_state = 3},
  [25] = {.lex_state = 13, .external_lex_state = 3},
  [26] = {.lex_state = 13, .external_lex_state = 3},
  [27] = {.lex_state = 3, .external_lex_state = 3},
  [28] = {.lex_state = 3, .external_lex_state = 1},
  [29] = {.lex_state = 13, .external_lex_state = 6},
  [30] = {.lex_state = 13, .external_lex_state = 2},
  [31] = {.lex_state = 13, .external_lex_state = 6},
  [32] = {.lex_state = 3, .external_lex_state = 3},
  [33] = {.lex_state = 3, .external_lex_state = 4},
  [34] = {.lex_state = 3, .external_lex_state = 1},
  [35] = {.lex_state = 4, .external_lex_state = 7},
  [36] = {.lex_state = 13, .external_lex_state = 3},
  [37] = {.lex_state = 0, .external_lex_state = 5},
  [38] = {.lex_state = 13, .external_lex_state = 8},
  [39] = {.lex_state = 3, .external_lex_state = 1},
  [40] = {.lex_state = 13, .external_lex_state = 8},
  [41] = {.lex_state = 13, .external_lex_state = 8},
  [42] = {.lex_state = 13, .external_lex_state = 2},
  [43] = {.lex_state = 0, .external_lex_state = 5},
  [44] = {.lex_state = 3, .external_lex_state = 4},
  [45] = {.lex_state = 2, .external_lex_state = 1},
  [46] = {.lex_state = 3, .external_lex_state = 4},
  [47] = {.lex_state = 0, .external_lex_state = 5},
  [48] = {.lex_state = 0, .external_lex_state = 7},
  [49] = {.lex_state = 3, .external_lex_state = 3},
  [50] = {.lex_state = 0, .external_lex_state = 7},
  [51] = {.lex_state = 13, .external_lex_state = 1},
  [52] = {.lex_state = 0, .external_lex_state = 7},
  [53] = {.lex_state = 3, .external_lex_state = 3},
  [54] = {.lex_state = 4, .external_lex_state = 5},
  [55] = {.lex_state = 3, .external_lex_state = 3},
  [56] = {.lex_state = 2, .external_lex_state = 4},
  [57] = {.lex_state = 4, .external_lex_state = 7},
  [58] = {.lex_state = 13, .external_lex_state = 4},
  [59] = {.lex_state = 13, .external_lex_state = 5},
  [60] = {.lex_state = 13},
  [61] = {.lex_state = 13, .external_lex_state = 7},
  [62] = {.lex_state = 13},
  [63] = {.lex_state = 13, .external_lex_state = 6},
  [64] = {.lex_state = 13, .external_lex_state = 6},
  [65] = {.lex_state = 13},
  [66] = {.lex_state = 13},
  [67] = {.lex_state = 13, .external_lex_state = 3},
  [68] = {.lex_state = 13, .external_lex_state = 8},
  [69] = {.lex_state = 13, .external_lex_state = 3},
  [70] = {.lex_state = 13, .external_lex_state = 3},
  [71] = {.lex_state = 13, .external_lex_state = 8},
  [72] = {.lex_state = 13, .external_lex_state = 2},
  [73] = {.lex_state = 13, .external_lex_state = 2},
  [74] = {.lex_state = 13, .external_lex_state = 2},
  [75] = {.lex_state = 13, .external_lex_state = 9},
  [76] = {.lex_state = 13, .external_lex_state = 9},
  [77] = {.lex_state = 13, .external_lex_state = 2},
  [78] = {.lex_state = 13, .external_lex_state = 2},
  [79] = {.lex_state = 13, .external_lex_state = 2},
  [80] = {.lex_state = 5},
  [81] = {.lex_state = 13, .external_lex_state = 9},
  [82] = {.lex_state = 13, .external_lex_state = 9},
  [83] = {.lex_state = 5},
  [84] = {.lex_state = 5},
  [85] = {.lex_state = 5},
  [86] = {.lex_state = 13, .external_lex_state = 9},
  [87] = {.lex_state = 5},
  [88] = {.lex_state = 5},
  [89] = {.lex_state = 5},
  [90] = {.lex_state = 5},
  [91] = {.lex_state = 13, .external_lex_state = 9},
  [92] = {.lex_state = 5},
  [93] = {.lex_state = 5},
  [94] = {.lex_state = 5},
  [95] = {.lex_state = 13, .external_lex_state = 2},
  [96] = {.lex_state = 5},
  [97] = {.lex_state = 13, .external_lex_state = 2},
  [98] = {.lex_state = 0, .external_lex_state = 9},
  [99] = {.lex_state = 13, .external_lex_state = 2},
  [100] = {.lex_state = 5},
  [101] = {.lex_state = 0, .external_lex_state = 9},
  [102] = {.lex_state = 0, .external_lex_state = 9},
  [103] = {.lex_state = 5},
  [104] = {.lex_state = 0, .external_lex_state = 9},
  [105] = {.lex_state = 0, .external_lex_state = 9},
  [106] = {.lex_state = 13, .external_lex_state = 2},
  [107] = {.lex_state = 0, .external_lex_state = 9},
  [108] = {.lex_state = 5},
  [109] = {.lex_state = 5},
  [110] = {.lex_state = 13, .external_lex_state = 2},
  [111] = {.lex_state = 5},
  [112] = {.lex_state = 13},
  [113] = {.lex_state = 6},
  [114] = {.lex_state = 6},
  [115] = {.lex_state = 13},
  [116] = {.lex_state = 6},
  [117] = {.lex_state = 6},
  [118] = {.lex_state = 7},
  [119] = {.lex_state = 6},
  [120] = {.lex_state = 13},
  [121] = {.lex_state = 13},
  [122] = {.lex_state = 0},
  [123] = {.lex_state = 13},
  [124] = {.lex_state = 13},
  [125] = {.lex_state = 13},
  [126] = {.lex_state = 13},
  [127] = {.lex_state = 7},
  [128] = {.lex_state = 7},
  [129] = {.lex_state = 7},
  [130] = {.lex_state = 7},
  [131] = {.lex_state = 7},
  [132] = {.lex_state = 13},
  [133] = {.lex_state = 7},
  [134] = {.lex_state = 7},
  [135] = {.lex_state = 6},
  [136] = {.lex_state = 0},
  [137] = {.lex_state = 6},
  [138] = {.lex_state = 0},
  [139] = {.lex_state = 13},
  [140] = {.lex_state = 13},
  [141] = {.lex_state = 7},
  [142] = {.lex_state = 13},
  [143] = {.lex_state = 7},
  [144] = {.lex_state = 7},
  [145] = {.lex_state = 0},
  [146] = {.lex_state = 7},
  [147] = {.lex_state = 7},
  [148] = {.lex_state = 7},
  [149] = {.lex_state = 7},
  [150] = {.lex_state = 7},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_section_header] = ACTIONS(1),
    [sym_marker_task_pending] = ACTIONS(1),
    [sym_marker_task_done] = ACTIONS(1),
    [sym_marker_property_info] = ACTIONS(1),
    [sym_marker_property_label] = ACTIONS(1),
    [sym__line] = ACTIONS(1),
    [sym__newline] = ACTIONS(1),
    [anon_sym_BQUOTE_BQUOTE_BQUOTE] = ACTIONS(1),
    [sym__indent] = ACTIONS(1),
    [sym__dedent] = ACTIONS(1),
    [sym__section_in] = ACTIONS(1),
    [sym__section_out] = ACTIONS(1),
    [sym__section_sibling] = ACTIONS(1),
    [sym__eof] = ACTIONS(1),
  },
  [1] = {
    [sym_document] = STATE(122),
    [sym_section] = STATE(79),
    [sym_marker_task] = STATE(135),
    [sym_marker_property] = STATE(135),
    [sym_marker] = STATE(116),
    [sym_item] = STATE(30),
    [aux_sym_document_repeat1] = STATE(30),
    [aux_sym_document_repeat2] = STATE(79),
    [sym_section_header] = ACTIONS(3),
    [sym_marker_task_pending] = ACTIONS(5),
    [sym_marker_task_done] = ACTIONS(5),
    [sym_marker_property_info] = ACTIONS(7),
    [sym_marker_property_label] = ACTIONS(7),
    [sym__section_in] = ACTIONS(9),
    [sym__eof] = ACTIONS(11),
  },
  [2] = {
    [sym_section_children] = STATE(102),
    [sym_marker_task] = STATE(135),
    [sym_marker_property] = STATE(135),
    [sym_marker] = STATE(117),
    [sym_body] = STATE(26),
    [sym_item] = STATE(25),
    [sym_code_block] = STATE(22),
    [aux_sym_document_repeat1] = STATE(25),
    [sym_marker_task_pending] = ACTIONS(13),
    [sym_marker_task_done] = ACTIONS(13),
    [sym_marker_property_info] = ACTIONS(15),
    [sym_marker_property_label] = ACTIONS(15),
    [sym__line] = ACTIONS(17),
    [anon_sym_BQUOTE_BQUOTE_BQUOTE] = ACTIONS(19),
    [sym__section_in] = ACTIONS(21),
    [sym__section_out] = ACTIONS(23),
    [sym__section_sibling] = ACTIONS(23),
    [sym__eof] = ACTIONS(23),
  },
  [3] = {
    [sym_section_children] = STATE(104),
    [sym_marker_task] = STATE(135),
    [sym_marker_property] = STATE(135),
    [sym_marker] = STATE(117),
    [sym_body] = STATE(18),
    [sym_item] = STATE(24),
    [sym_code_block] = STATE(22),
    [aux_sym_document_repeat1] = STATE(24),
    [sym_marker_task_pending] = ACTIONS(13),
    [sym_marker_task_done] = ACTIONS(13),
    [sym_marker_property_info] = ACTIONS(15),
    [sym_marker_property_label] = ACTIONS(15),
    [sym__line] = ACTIONS(17),
    [anon_sym_BQUOTE_BQUOTE_BQUOTE] = ACTIONS(19),
    [sym__section_in] = ACTIONS(21),
    [sym__section_out] = ACTIONS(25),
    [sym__section_sibling] = ACTIONS(25),
    [sym__eof] = ACTIONS(25),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 5,
    ACTIONS(32), 1,
      anon_sym_BQUOTE_BQUOTE_BQUOTE,
    ACTIONS(29), 2,
      sym__line,
      sym__newline,
    STATE(4), 3,
      aux_sym__lines,
      sym_code_block,
      aux_sym_body_repeat1,
    ACTIONS(27), 4,
      sym_marker_task_pending,
      sym_marker_task_done,
      sym_marker_property_info,
      sym_marker_property_label,
    ACTIONS(35), 6,
      sym__indent,
      sym__dedent,
      sym__section_in,
      sym__section_out,
      sym__section_sibling,
      sym__eof,
  [27] = 5,
    ACTIONS(41), 1,
      anon_sym_BQUOTE_BQUOTE_BQUOTE,
    ACTIONS(39), 2,
      sym__line,
      sym__newline,
    STATE(4), 3,
      aux_sym__lines,
      sym_code_block,
      aux_sym_body_repeat1,
    ACTIONS(37), 4,
      sym_marker_task_pending,
      sym_marker_task_done,
      sym_marker_property_info,
      sym_marker_property_label,
    ACTIONS(43), 6,
      sym__indent,
      sym__dedent,
      sym__section_in,
      sym__section_out,
      sym__section_sibling,
      sym__eof,
  [54] = 5,
    ACTIONS(41), 1,
      anon_sym_BQUOTE_BQUOTE_BQUOTE,
    ACTIONS(47), 2,
      sym__line,
      sym__newline,
    STATE(5), 3,
      aux_sym__lines,
      sym_code_block,
      aux_sym_body_repeat1,
    ACTIONS(45), 4,
      sym_marker_task_pending,
      sym_marker_task_done,
      sym_marker_property_info,
      sym_marker_property_label,
    ACTIONS(49), 6,
      sym__indent,
      sym__dedent,
      sym__section_in,
      sym__section_out,
      sym__section_sibling,
      sym__eof,
  [81] = 5,
    ACTIONS(53), 1,
      anon_sym_BQUOTE_BQUOTE_BQUOTE,
    ACTIONS(51), 2,
      sym__line,
      sym__newline,
    STATE(13), 3,
      aux_sym__lines,
      sym_code_block,
      aux_sym_body_repeat1,
    ACTIONS(45), 4,
      sym_marker_task_pending,
      sym_marker_task_done,
      sym_marker_property_info,
      sym_marker_property_label,
    ACTIONS(49), 5,
      sym__indent,
      sym__section_in,
      sym__section_out,
      sym__section_sibling,
      sym__eof,
  [107] = 5,
    ACTIONS(58), 1,
      anon_sym_BQUOTE_BQUOTE_BQUOTE,
    ACTIONS(55), 2,
      sym__line,
      sym__newline,
    STATE(8), 3,
      aux_sym__lines,
      sym_code_block,
      aux_sym_body_repeat1,
    ACTIONS(35), 4,
      sym__indent,
      sym__dedent,
      sym__section_in,
      sym__eof,
    ACTIONS(27), 5,
      sym_section_header,
      sym_marker_task_pending,
      sym_marker_task_done,
      sym_marker_property_info,
      sym_marker_property_label,
  [133] = 5,
    ACTIONS(63), 1,
      anon_sym_BQUOTE_BQUOTE_BQUOTE,
    ACTIONS(61), 2,
      sym__line,
      sym__newline,
    STATE(8), 3,
      aux_sym__lines,
      sym_code_block,
      aux_sym_body_repeat1,
    ACTIONS(43), 4,
      sym__indent,
      sym__dedent,
      sym__section_in,
      sym__eof,
    ACTIONS(37), 5,
      sym_section_header,
      sym_marker_task_pending,
      sym_marker_task_done,
      sym_marker_property_info,
      sym_marker_property_label,
  [159] = 8,
    ACTIONS(41), 1,
      anon_sym_BQUOTE_BQUOTE_BQUOTE,
    ACTIONS(67), 1,
      sym__line,
    ACTIONS(69), 1,
      sym__indent,
    STATE(6), 1,
      sym_code_block,
    STATE(51), 1,
      sym_body,
    STATE(63), 1,
      sym_children,
    ACTIONS(65), 4,
      sym_marker_task_pending,
      sym_marker_task_done,
      sym_marker_property_info,
      sym_marker_property_label,
    ACTIONS(71), 5,
      sym__dedent,
      sym__section_in,
      sym__section_out,
      sym__section_sibling,
      sym__eof,
  [191] = 5,
    ACTIONS(63), 1,
      anon_sym_BQUOTE_BQUOTE_BQUOTE,
    ACTIONS(73), 2,
      sym__line,
      sym__newline,
    STATE(9), 3,
      aux_sym__lines,
      sym_code_block,
      aux_sym_body_repeat1,
    ACTIONS(49), 4,
      sym__indent,
      sym__dedent,
      sym__section_in,
      sym__eof,
    ACTIONS(45), 5,
      sym_section_header,
      sym_marker_task_pending,
      sym_marker_task_done,
      sym_marker_property_info,
      sym_marker_property_label,
  [217] = 5,
    ACTIONS(78), 1,
      anon_sym_BQUOTE_BQUOTE_BQUOTE,
    ACTIONS(75), 2,
      sym__line,
      sym__newline,
    STATE(12), 3,
      aux_sym__lines,
      sym_code_block,
      aux_sym_body_repeat1,
    ACTIONS(27), 4,
      sym_marker_task_pending,
      sym_marker_task_done,
      sym_marker_property_info,
      sym_marker_property_label,
    ACTIONS(35), 5,
      sym__indent,
      sym__section_in,
      sym__section_out,
      sym__section_sibling,
      sym__eof,
  [243] = 5,
    ACTIONS(53), 1,
      anon_sym_BQUOTE_BQUOTE_BQUOTE,
    ACTIONS(81), 2,
      sym__line,
      sym__newline,
    STATE(12), 3,
      aux_sym__lines,
      sym_code_block,
      aux_sym_body_repeat1,
    ACTIONS(37), 4,
      sym_marker_task_pending,
      sym_marker_task_done,
      sym_marker_property_info,
      sym_marker_property_label,
    ACTIONS(43), 5,
      sym__indent,
      sym__section_in,
      sym__section_out,
      sym__section_sibling,
      sym__eof,
  [269] = 8,
    ACTIONS(21), 1,
      sym__section_in,
    STATE(107), 1,
      sym_section_children,
    STATE(117), 1,
      sym_marker,
    ACTIONS(5), 2,
      sym_marker_task_pending,
      sym_marker_task_done,
    ACTIONS(7), 2,
      sym_marker_property_info,
      sym_marker_property_label,
    STATE(36), 2,
      sym_item,
      aux_sym_document_repeat1,
    STATE(135), 2,
      sym_marker_task,
      sym_marker_property,
    ACTIONS(83), 3,
      sym__section_out,
      sym__section_sibling,
      sym__eof,
  [300] = 8,
    ACTIONS(21), 1,
      sym__section_in,
    STATE(101), 1,
      sym_section_children,
    STATE(117), 1,
      sym_marker,
    ACTIONS(5), 2,
      sym_marker_task_pending,
      sym_marker_task_done,
    ACTIONS(7), 2,
      sym_marker_property_info,
      sym_marker_property_label,
    STATE(36), 2,
      sym_item,
      aux_sym_document_repeat1,
    STATE(135), 2,
      sym_marker_task,
      sym_marker_property,
    ACTIONS(85), 3,
      sym__section_out,
      sym__section_sibling,
      sym__eof,
  [331] = 5,
    ACTIONS(89), 1,
      sym__dedent,
    STATE(114), 1,
      sym_marker,
    STATE(29), 2,
      sym_item,
      aux_sym_document_repeat1,
    STATE(135), 2,
      sym_marker_task,
      sym_marker_property,
    ACTIONS(87), 8,
      sym__section_in,
      sym__section_out,
      sym__section_sibling,
      sym__eof,
      sym_marker_task_pending,
      sym_marker_task_done,
      sym_marker_property_info,
      sym_marker_property_label,
  [356] = 5,
    ACTIONS(94), 1,
      anon_sym_BQUOTE_BQUOTE_BQUOTE,
    ACTIONS(91), 2,
      sym__line,
      sym__newline,
    ACTIONS(35), 3,
      sym__indent,
      sym__section_in,
      sym__eof,
    STATE(17), 3,
      aux_sym__lines,
      sym_code_block,
      aux_sym_body_repeat1,
    ACTIONS(27), 5,
      sym_section_header,
      sym_marker_task_pending,
      sym_marker_task_done,
      sym_marker_property_info,
      sym_marker_property_label,
  [381] = 8,
    ACTIONS(21), 1,
      sym__section_in,
    STATE(98), 1,
      sym_section_children,
    STATE(117), 1,
      sym_marker,
    ACTIONS(5), 2,
      sym_marker_task_pending,
      sym_marker_task_done,
    ACTIONS(7), 2,
      sym_marker_property_info,
      sym_marker_property_label,
    STATE(15), 2,
      sym_item,
      aux_sym_document_repeat1,
    STATE(135), 2,
      sym_marker_task,
      sym_marker_property,
    ACTIONS(97), 3,
      sym__section_out,
      sym__section_sibling,
      sym__eof,
  [412] = 8,
    ACTIONS(63), 1,
      anon_sym_BQUOTE_BQUOTE_BQUOTE,
    ACTIONS(99), 1,
      sym__line,
    ACTIONS(101), 1,
      sym__indent,
    STATE(11), 1,
      sym_code_block,
    STATE(59), 1,
      sym_body,
    STATE(71), 1,
      sym_children,
    ACTIONS(71), 3,
      sym__dedent,
      sym__section_in,
      sym__eof,
    ACTIONS(65), 5,
      sym_section_header,
      sym_marker_task_pending,
      sym_marker_task_done,
      sym_marker_property_info,
      sym_marker_property_label,
  [443] = 5,
    ACTIONS(105), 1,
      anon_sym_BQUOTE_BQUOTE_BQUOTE,
    ACTIONS(103), 2,
      sym__line,
      sym__newline,
    ACTIONS(43), 3,
      sym__indent,
      sym__section_in,
      sym__eof,
    STATE(17), 3,
      aux_sym__lines,
      sym_code_block,
      aux_sym_body_repeat1,
    ACTIONS(37), 5,
      sym_section_header,
      sym_marker_task_pending,
      sym_marker_task_done,
      sym_marker_property_info,
      sym_marker_property_label,
  [468] = 8,
    ACTIONS(53), 1,
      anon_sym_BQUOTE_BQUOTE_BQUOTE,
    ACTIONS(107), 1,
      sym__line,
    ACTIONS(109), 1,
      sym__indent,
    STATE(7), 1,
      sym_code_block,
    STATE(58), 1,
      sym_body,
    STATE(67), 1,
      sym_children,
    ACTIONS(65), 4,
      sym_marker_task_pending,
      sym_marker_task_done,
      sym_marker_property_info,
      sym_marker_property_label,
    ACTIONS(71), 4,
      sym__section_in,
      sym__section_out,
      sym__section_sibling,
      sym__eof,
  [499] = 5,
    ACTIONS(19), 1,
      anon_sym_BQUOTE_BQUOTE_BQUOTE,
    ACTIONS(111), 2,
      sym__line,
      sym__newline,
    STATE(27), 3,
      aux_sym__lines,
      sym_code_block,
      aux_sym_body_repeat1,
    ACTIONS(45), 4,
      sym_marker_task_pending,
      sym_marker_task_done,
      sym_marker_property_info,
      sym_marker_property_label,
    ACTIONS(49), 4,
      sym__section_in,
      sym__section_out,
      sym__section_sibling,
      sym__eof,
  [524] = 5,
    ACTIONS(105), 1,
      anon_sym_BQUOTE_BQUOTE_BQUOTE,
    ACTIONS(113), 2,
      sym__line,
      sym__newline,
    ACTIONS(49), 3,
      sym__indent,
      sym__section_in,
      sym__eof,
    STATE(20), 3,
      aux_sym__lines,
      sym_code_block,
      aux_sym_body_repeat1,
    ACTIONS(45), 5,
      sym_section_header,
      sym_marker_task_pending,
      sym_marker_task_done,
      sym_marker_property_info,
      sym_marker_property_label,
  [549] = 8,
    ACTIONS(21), 1,
      sym__section_in,
    STATE(98), 1,
      sym_section_children,
    STATE(117), 1,
      sym_marker,
    ACTIONS(5), 2,
      sym_marker_task_pending,
      sym_marker_task_done,
    ACTIONS(7), 2,
      sym_marker_property_info,
      sym_marker_property_label,
    STATE(36), 2,
      sym_item,
      aux_sym_document_repeat1,
    STATE(135), 2,
      sym_marker_task,
      sym_marker_property,
    ACTIONS(97), 3,
      sym__section_out,
      sym__section_sibling,
      sym__eof,
  [580] = 8,
    ACTIONS(21), 1,
      sym__section_in,
    STATE(105), 1,
      sym_section_children,
    STATE(117), 1,
      sym_marker,
    ACTIONS(5), 2,
      sym_marker_task_pending,
      sym_marker_task_done,
    ACTIONS(7), 2,
      sym_marker_property_info,
      sym_marker_property_label,
    STATE(36), 2,
      sym_item,
      aux_sym_document_repeat1,
    STATE(135), 2,
      sym_marker_task,
      sym_marker_property,
    ACTIONS(115), 3,
      sym__section_out,
      sym__section_sibling,
      sym__eof,
  [611] = 8,
    ACTIONS(21), 1,
      sym__section_in,
    STATE(105), 1,
      sym_section_children,
    STATE(117), 1,
      sym_marker,
    ACTIONS(5), 2,
      sym_marker_task_pending,
      sym_marker_task_done,
    ACTIONS(7), 2,
      sym_marker_property_info,
      sym_marker_property_label,
    STATE(14), 2,
      sym_item,
      aux_sym_document_repeat1,
    STATE(135), 2,
      sym_marker_task,
      sym_marker_property,
    ACTIONS(115), 3,
      sym__section_out,
      sym__section_sibling,
      sym__eof,
  [642] = 5,
    ACTIONS(19), 1,
      anon_sym_BQUOTE_BQUOTE_BQUOTE,
    ACTIONS(117), 2,
      sym__line,
      sym__newline,
    STATE(32), 3,
      aux_sym__lines,
      sym_code_block,
      aux_sym_body_repeat1,
    ACTIONS(37), 4,
      sym_marker_task_pending,
      sym_marker_task_done,
      sym_marker_property_info,
      sym_marker_property_label,
    ACTIONS(43), 4,
      sym__section_in,
      sym__section_out,
      sym__section_sibling,
      sym__eof,
  [667] = 4,
    STATE(28), 1,
      aux_sym__lines,
    ACTIONS(121), 2,
      sym__line,
      sym__newline,
    ACTIONS(119), 5,
      sym_marker_task_pending,
      sym_marker_task_done,
      sym_marker_property_info,
      sym_marker_property_label,
      anon_sym_BQUOTE_BQUOTE_BQUOTE,
    ACTIONS(124), 6,
      sym__indent,
      sym__dedent,
      sym__section_in,
      sym__section_out,
      sym__section_sibling,
      sym__eof,
  [690] = 6,
    STATE(114), 1,
      sym_marker,
    ACTIONS(126), 2,
      sym_marker_task_pending,
      sym_marker_task_done,
    ACTIONS(129), 2,
      sym_marker_property_info,
      sym_marker_property_label,
    STATE(29), 2,
      sym_item,
      aux_sym_document_repeat1,
    STATE(135), 2,
      sym_marker_task,
      sym_marker_property,
    ACTIONS(132), 5,
      sym__dedent,
      sym__section_in,
      sym__section_out,
      sym__section_sibling,
      sym__eof,
  [717] = 9,
    ACTIONS(3), 1,
      sym_section_header,
    ACTIONS(9), 1,
      sym__section_in,
    ACTIONS(134), 1,
      sym__eof,
    STATE(116), 1,
      sym_marker,
    ACTIONS(5), 2,
      sym_marker_task_pending,
      sym_marker_task_done,
    ACTIONS(7), 2,
      sym_marker_property_info,
      sym_marker_property_label,
    STATE(42), 2,
      sym_item,
      aux_sym_document_repeat1,
    STATE(77), 2,
      sym_section,
      aux_sym_document_repeat2,
    STATE(135), 2,
      sym_marker_task,
      sym_marker_property,
  [750] = 4,
    STATE(114), 1,
      sym_marker,
    STATE(29), 2,
      sym_item,
      aux_sym_document_repeat1,
    STATE(135), 2,
      sym_marker_task,
      sym_marker_property,
    ACTIONS(87), 9,
      sym__dedent,
      sym__section_in,
      sym__section_out,
      sym__section_sibling,
      sym__eof,
      sym_marker_task_pending,
      sym_marker_task_done,
      sym_marker_property_info,
      sym_marker_property_label,
  [773] = 5,
    ACTIONS(139), 1,
      anon_sym_BQUOTE_BQUOTE_BQUOTE,
    ACTIONS(136), 2,
      sym__line,
      sym__newline,
    STATE(32), 3,
      aux_sym__lines,
      sym_code_block,
      aux_sym_body_repeat1,
    ACTIONS(27), 4,
      sym_marker_task_pending,
      sym_marker_task_done,
      sym_marker_property_info,
      sym_marker_property_label,
    ACTIONS(35), 4,
      sym__section_in,
      sym__section_out,
      sym__section_sibling,
      sym__eof,
  [798] = 4,
    STATE(33), 1,
      aux_sym__lines,
    ACTIONS(142), 2,
      sym__line,
      sym__newline,
    ACTIONS(119), 5,
      sym_marker_task_pending,
      sym_marker_task_done,
      sym_marker_property_info,
      sym_marker_property_label,
      anon_sym_BQUOTE_BQUOTE_BQUOTE,
    ACTIONS(124), 5,
      sym__indent,
      sym__section_in,
      sym__section_out,
      sym__section_sibling,
      sym__eof,
  [820] = 2,
    ACTIONS(147), 6,
      sym__indent,
      sym__dedent,
      sym__section_in,
      sym__section_out,
      sym__section_sibling,
      sym__eof,
    ACTIONS(145), 7,
      sym_marker_task_pending,
      sym_marker_task_done,
      sym_marker_property_info,
      sym_marker_property_label,
      sym__line,
      sym__newline,
      anon_sym_BQUOTE_BQUOTE_BQUOTE,
  [838] = 8,
    ACTIONS(105), 1,
      anon_sym_BQUOTE_BQUOTE_BQUOTE,
    ACTIONS(149), 1,
      sym__line,
    ACTIONS(151), 1,
      sym__indent,
    STATE(23), 1,
      sym_code_block,
    STATE(61), 1,
      sym_body,
    STATE(73), 1,
      sym_children,
    ACTIONS(71), 2,
      sym__section_in,
      sym__eof,
    ACTIONS(65), 5,
      sym_section_header,
      sym_marker_task_pending,
      sym_marker_task_done,
      sym_marker_property_info,
      sym_marker_property_label,
  [868] = 6,
    STATE(117), 1,
      sym_marker,
    ACTIONS(126), 2,
      sym_marker_task_pending,
      sym_marker_task_done,
    ACTIONS(129), 2,
      sym_marker_property_info,
      sym_marker_property_label,
    STATE(36), 2,
      sym_item,
      aux_sym_document_repeat1,
    STATE(135), 2,
      sym_marker_task,
      sym_marker_property,
    ACTIONS(132), 4,
      sym__section_in,
      sym__section_out,
      sym__section_sibling,
      sym__eof,
  [894] = 4,
    STATE(37), 1,
      aux_sym__lines,
    ACTIONS(153), 2,
      sym__line,
      sym__newline,
    ACTIONS(124), 4,
      sym__indent,
      sym__dedent,
      sym__section_in,
      sym__eof,
    ACTIONS(119), 6,
      sym_section_header,
      sym_marker_task_pending,
      sym_marker_task_done,
      sym_marker_property_info,
      sym_marker_property_label,
      anon_sym_BQUOTE_BQUOTE_BQUOTE,
  [916] = 6,
    STATE(113), 1,
      sym_marker,
    ACTIONS(126), 2,
      sym_marker_task_pending,
      sym_marker_task_done,
    ACTIONS(129), 2,
      sym_marker_property_info,
      sym_marker_property_label,
    STATE(38), 2,
      sym_item,
      aux_sym_document_repeat1,
    STATE(135), 2,
      sym_marker_task,
      sym_marker_property,
    ACTIONS(132), 4,
      sym__dedent,
      sym__section_in,
      sym__eof,
      sym_section_header,
  [942] = 2,
    ACTIONS(158), 6,
      sym__indent,
      sym__dedent,
      sym__section_in,
      sym__section_out,
      sym__section_sibling,
      sym__eof,
    ACTIONS(156), 7,
      sym_marker_task_pending,
      sym_marker_task_done,
      sym_marker_property_info,
      sym_marker_property_label,
      sym__line,
      sym__newline,
      anon_sym_BQUOTE_BQUOTE_BQUOTE,
  [960] = 5,
    ACTIONS(160), 1,
      sym__dedent,
    STATE(113), 1,
      sym_marker,
    STATE(38), 2,
      sym_item,
      aux_sym_document_repeat1,
    STATE(135), 2,
      sym_marker_task,
      sym_marker_property,
    ACTIONS(87), 7,
      sym__section_in,
      sym__eof,
      sym_section_header,
      sym_marker_task_pending,
      sym_marker_task_done,
      sym_marker_property_info,
      sym_marker_property_label,
  [984] = 4,
    STATE(113), 1,
      sym_marker,
    STATE(38), 2,
      sym_item,
      aux_sym_document_repeat1,
    STATE(135), 2,
      sym_marker_task,
      sym_marker_property,
    ACTIONS(87), 8,
      sym__dedent,
      sym__section_in,
      sym__eof,
      sym_section_header,
      sym_marker_task_pending,
      sym_marker_task_done,
      sym_marker_property_info,
      sym_marker_property_label,
  [1006] = 6,
    STATE(116), 1,
      sym_marker,
    ACTIONS(126), 2,
      sym_marker_task_pending,
      sym_marker_task_done,
    ACTIONS(129), 2,
      sym_marker_property_info,
      sym_marker_property_label,
    STATE(42), 2,
      sym_item,
      aux_sym_document_repeat1,
    STATE(135), 2,
      sym_marker_task,
      sym_marker_property,
    ACTIONS(132), 3,
      sym__section_in,
      sym__eof,
      sym_section_header,
  [1031] = 2,
    ACTIONS(147), 4,
      sym__indent,
      sym__dedent,
      sym__section_in,
      sym__eof,
    ACTIONS(145), 8,
      sym_section_header,
      sym_marker_task_pending,
      sym_marker_task_done,
      sym_marker_property_info,
      sym_marker_property_label,
      sym__line,
      sym__newline,
      anon_sym_BQUOTE_BQUOTE_BQUOTE,
  [1048] = 2,
    ACTIONS(147), 5,
      sym__indent,
      sym__section_in,
      sym__section_out,
      sym__section_sibling,
      sym__eof,
    ACTIONS(145), 7,
      sym_marker_task_pending,
      sym_marker_task_done,
      sym_marker_property_info,
      sym_marker_property_label,
      sym__line,
      sym__newline,
      anon_sym_BQUOTE_BQUOTE_BQUOTE,
  [1065] = 2,
    ACTIONS(162), 6,
      sym_marker_task_pending,
      sym_marker_task_done,
      sym_marker_property_info,
      sym_marker_property_label,
      sym__line,
      anon_sym_BQUOTE_BQUOTE_BQUOTE,
    ACTIONS(164), 6,
      sym__indent,
      sym__dedent,
      sym__section_in,
      sym__section_out,
      sym__section_sibling,
      sym__eof,
  [1082] = 2,
    ACTIONS(158), 5,
      sym__indent,
      sym__section_in,
      sym__section_out,
      sym__section_sibling,
      sym__eof,
    ACTIONS(156), 7,
      sym_marker_task_pending,
      sym_marker_task_done,
      sym_marker_property_info,
      sym_marker_property_label,
      sym__line,
      sym__newline,
      anon_sym_BQUOTE_BQUOTE_BQUOTE,
  [1099] = 2,
    ACTIONS(158), 4,
      sym__indent,
      sym__dedent,
      sym__section_in,
      sym__eof,
    ACTIONS(156), 8,
      sym_section_header,
      sym_marker_task_pending,
      sym_marker_task_done,
      sym_marker_property_info,
      sym_marker_property_label,
      sym__line,
      sym__newline,
      anon_sym_BQUOTE_BQUOTE_BQUOTE,
  [1116] = 4,
    STATE(48), 1,
      aux_sym__lines,
    ACTIONS(166), 2,
      sym__line,
      sym__newline,
    ACTIONS(124), 3,
      sym__indent,
      sym__section_in,
      sym__eof,
    ACTIONS(119), 6,
      sym_section_header,
      sym_marker_task_pending,
      sym_marker_task_done,
      sym_marker_property_info,
      sym_marker_property_label,
      anon_sym_BQUOTE_BQUOTE_BQUOTE,
  [1137] = 4,
    STATE(49), 1,
      aux_sym__lines,
    ACTIONS(169), 2,
      sym__line,
      sym__newline,
    ACTIONS(124), 4,
      sym__section_in,
      sym__section_out,
      sym__section_sibling,
      sym__eof,
    ACTIONS(119), 5,
      sym_marker_task_pending,
      sym_marker_task_done,
      sym_marker_property_info,
      sym_marker_property_label,
      anon_sym_BQUOTE_BQUOTE_BQUOTE,
  [1158] = 2,
    ACTIONS(147), 3,
      sym__indent,
      sym__section_in,
      sym__eof,
    ACTIONS(145), 8,
      sym_section_header,
      sym_marker_task_pending,
      sym_marker_task_done,
      sym_marker_property_info,
      sym_marker_property_label,
      sym__line,
      sym__newline,
      anon_sym_BQUOTE_BQUOTE_BQUOTE,
  [1174] = 3,
    ACTIONS(69), 1,
      sym__indent,
    STATE(64), 1,
      sym_children,
    ACTIONS(172), 9,
      sym__dedent,
      sym__section_in,
      sym__section_out,
      sym__section_sibling,
      sym__eof,
      sym_marker_task_pending,
      sym_marker_task_done,
      sym_marker_property_info,
      sym_marker_property_label,
  [1192] = 2,
    ACTIONS(158), 3,
      sym__indent,
      sym__section_in,
      sym__eof,
    ACTIONS(156), 8,
      sym_section_header,
      sym_marker_task_pending,
      sym_marker_task_done,
      sym_marker_property_info,
      sym_marker_property_label,
      sym__line,
      sym__newline,
      anon_sym_BQUOTE_BQUOTE_BQUOTE,
  [1208] = 2,
    ACTIONS(147), 4,
      sym__section_in,
      sym__section_out,
      sym__section_sibling,
      sym__eof,
    ACTIONS(145), 7,
      sym_marker_task_pending,
      sym_marker_task_done,
      sym_marker_property_info,
      sym_marker_property_label,
      sym__line,
      sym__newline,
      anon_sym_BQUOTE_BQUOTE_BQUOTE,
  [1224] = 2,
    ACTIONS(164), 4,
      sym__indent,
      sym__dedent,
      sym__section_in,
      sym__eof,
    ACTIONS(162), 7,
      sym_section_header,
      sym_marker_task_pending,
      sym_marker_task_done,
      sym_marker_property_info,
      sym_marker_property_label,
      sym__line,
      anon_sym_BQUOTE_BQUOTE_BQUOTE,
  [1240] = 2,
    ACTIONS(158), 4,
      sym__section_in,
      sym__section_out,
      sym__section_sibling,
      sym__eof,
    ACTIONS(156), 7,
      sym_marker_task_pending,
      sym_marker_task_done,
      sym_marker_property_info,
      sym_marker_property_label,
      sym__line,
      sym__newline,
      anon_sym_BQUOTE_BQUOTE_BQUOTE,
  [1256] = 2,
    ACTIONS(164), 5,
      sym__indent,
      sym__section_in,
      sym__section_out,
      sym__section_sibling,
      sym__eof,
    ACTIONS(162), 6,
      sym_marker_task_pending,
      sym_marker_task_done,
      sym_marker_property_info,
      sym_marker_property_label,
      sym__line,
      anon_sym_BQUOTE_BQUOTE_BQUOTE,
  [1272] = 2,
    ACTIONS(164), 3,
      sym__indent,
      sym__section_in,
      sym__eof,
    ACTIONS(162), 7,
      sym_section_header,
      sym_marker_task_pending,
      sym_marker_task_done,
      sym_marker_property_info,
      sym_marker_property_label,
      sym__line,
      anon_sym_BQUOTE_BQUOTE_BQUOTE,
  [1287] = 3,
    ACTIONS(109), 1,
      sym__indent,
    STATE(70), 1,
      sym_children,
    ACTIONS(172), 8,
      sym__section_in,
      sym__section_out,
      sym__section_sibling,
      sym__eof,
      sym_marker_task_pending,
      sym_marker_task_done,
      sym_marker_property_info,
      sym_marker_property_label,
  [1304] = 3,
    ACTIONS(101), 1,
      sym__indent,
    STATE(68), 1,
      sym_children,
    ACTIONS(172), 8,
      sym__dedent,
      sym__section_in,
      sym__eof,
      sym_section_header,
      sym_marker_task_pending,
      sym_marker_task_done,
      sym_marker_property_info,
      sym_marker_property_label,
  [1321] = 5,
    STATE(114), 1,
      sym_marker,
    ACTIONS(5), 2,
      sym_marker_task_pending,
      sym_marker_task_done,
    ACTIONS(7), 2,
      sym_marker_property_info,
      sym_marker_property_label,
    STATE(16), 2,
      sym_item,
      aux_sym_document_repeat1,
    STATE(135), 2,
      sym_marker_task,
      sym_marker_property,
  [1341] = 3,
    ACTIONS(151), 1,
      sym__indent,
    STATE(74), 1,
      sym_children,
    ACTIONS(172), 7,
      sym__section_in,
      sym__eof,
      sym_section_header,
      sym_marker_task_pending,
      sym_marker_task_done,
      sym_marker_property_info,
      sym_marker_property_label,
  [1357] = 5,
    STATE(113), 1,
      sym_marker,
    ACTIONS(5), 2,
      sym_marker_task_pending,
      sym_marker_task_done,
    ACTIONS(7), 2,
      sym_marker_property_info,
      sym_marker_property_label,
    STATE(40), 2,
      sym_item,
      aux_sym_document_repeat1,
    STATE(135), 2,
      sym_marker_task,
      sym_marker_property,
  [1377] = 1,
    ACTIONS(172), 9,
      sym__dedent,
      sym__section_in,
      sym__section_out,
      sym__section_sibling,
      sym__eof,
      sym_marker_task_pending,
      sym_marker_task_done,
      sym_marker_property_info,
      sym_marker_property_label,
  [1389] = 1,
    ACTIONS(174), 9,
      sym__dedent,
      sym__section_in,
      sym__section_out,
      sym__section_sibling,
      sym__eof,
      sym_marker_task_pending,
      sym_marker_task_done,
      sym_marker_property_info,
      sym_marker_property_label,
  [1401] = 5,
    STATE(113), 1,
      sym_marker,
    ACTIONS(5), 2,
      sym_marker_task_pending,
      sym_marker_task_done,
    ACTIONS(7), 2,
      sym_marker_property_info,
      sym_marker_property_label,
    STATE(41), 2,
      sym_item,
      aux_sym_document_repeat1,
    STATE(135), 2,
      sym_marker_task,
      sym_marker_property,
  [1421] = 5,
    STATE(114), 1,
      sym_marker,
    ACTIONS(5), 2,
      sym_marker_task_pending,
      sym_marker_task_done,
    ACTIONS(7), 2,
      sym_marker_property_info,
      sym_marker_property_label,
    STATE(31), 2,
      sym_item,
      aux_sym_document_repeat1,
    STATE(135), 2,
      sym_marker_task,
      sym_marker_property,
  [1441] = 1,
    ACTIONS(172), 8,
      sym__section_in,
      sym__section_out,
      sym__section_sibling,
      sym__eof,
      sym_marker_task_pending,
      sym_marker_task_done,
      sym_marker_property_info,
      sym_marker_property_label,
  [1452] = 1,
    ACTIONS(174), 8,
      sym__dedent,
      sym__section_in,
      sym__eof,
      sym_section_header,
      sym_marker_task_pending,
      sym_marker_task_done,
      sym_marker_property_info,
      sym_marker_property_label,
  [1463] = 1,
    ACTIONS(176), 8,
      sym__section_in,
      sym__section_out,
      sym__section_sibling,
      sym__eof,
      sym_marker_task_pending,
      sym_marker_task_done,
      sym_marker_property_info,
      sym_marker_property_label,
  [1474] = 1,
    ACTIONS(174), 8,
      sym__section_in,
      sym__section_out,
      sym__section_sibling,
      sym__eof,
      sym_marker_task_pending,
      sym_marker_task_done,
      sym_marker_property_info,
      sym_marker_property_label,
  [1485] = 1,
    ACTIONS(172), 8,
      sym__dedent,
      sym__section_in,
      sym__eof,
      sym_section_header,
      sym_marker_task_pending,
      sym_marker_task_done,
      sym_marker_property_info,
      sym_marker_property_label,
  [1496] = 1,
    ACTIONS(176), 7,
      sym__section_in,
      sym__eof,
      sym_section_header,
      sym_marker_task_pending,
      sym_marker_task_done,
      sym_marker_property_info,
      sym_marker_property_label,
  [1506] = 1,
    ACTIONS(172), 7,
      sym__section_in,
      sym__eof,
      sym_section_header,
      sym_marker_task_pending,
      sym_marker_task_done,
      sym_marker_property_info,
      sym_marker_property_label,
  [1516] = 1,
    ACTIONS(174), 7,
      sym__section_in,
      sym__eof,
      sym_section_header,
      sym_marker_task_pending,
      sym_marker_task_done,
      sym_marker_property_info,
      sym_marker_property_label,
  [1526] = 3,
    ACTIONS(178), 1,
      sym_section_header,
    STATE(76), 2,
      sym_section,
      aux_sym_section_children_repeat1,
    ACTIONS(180), 3,
      sym__section_out,
      sym__section_sibling,
      sym__eof,
  [1539] = 3,
    ACTIONS(182), 1,
      sym_section_header,
    STATE(76), 2,
      sym_section,
      aux_sym_section_children_repeat1,
    ACTIONS(185), 3,
      sym__section_out,
      sym__section_sibling,
      sym__eof,
  [1552] = 4,
    ACTIONS(3), 1,
      sym_section_header,
    ACTIONS(9), 1,
      sym__section_in,
    ACTIONS(187), 1,
      sym__eof,
    STATE(78), 2,
      sym_section,
      aux_sym_document_repeat2,
  [1566] = 4,
    ACTIONS(189), 1,
      sym_section_header,
    ACTIONS(192), 1,
      sym__section_in,
    ACTIONS(195), 1,
      sym__eof,
    STATE(78), 2,
      sym_section,
      aux_sym_document_repeat2,
  [1580] = 4,
    ACTIONS(3), 1,
      sym_section_header,
    ACTIONS(9), 1,
      sym__section_in,
    ACTIONS(134), 1,
      sym__eof,
    STATE(78), 2,
      sym_section,
      aux_sym_document_repeat2,
  [1594] = 3,
    STATE(94), 1,
      aux_sym__lines,
    STATE(143), 1,
      sym_code_block_content,
    ACTIONS(197), 2,
      sym__line,
      sym__newline,
  [1605] = 1,
    ACTIONS(199), 4,
      sym__section_out,
      sym__section_sibling,
      sym__eof,
      sym_section_header,
  [1612] = 1,
    ACTIONS(201), 4,
      sym__section_out,
      sym__section_sibling,
      sym__eof,
      sym_section_header,
  [1619] = 3,
    STATE(94), 1,
      aux_sym__lines,
    STATE(131), 1,
      sym_code_block_content,
    ACTIONS(197), 2,
      sym__line,
      sym__newline,
  [1630] = 3,
    STATE(94), 1,
      aux_sym__lines,
    STATE(128), 1,
      sym_code_block_content,
    ACTIONS(197), 2,
      sym__line,
      sym__newline,
  [1641] = 3,
    STATE(94), 1,
      aux_sym__lines,
    STATE(127), 1,
      sym_code_block_content,
    ACTIONS(197), 2,
      sym__line,
      sym__newline,
  [1652] = 1,
    ACTIONS(203), 4,
      sym__section_out,
      sym__section_sibling,
      sym__eof,
      sym_section_header,
  [1659] = 3,
    STATE(94), 1,
      aux_sym__lines,
    STATE(118), 1,
      sym_code_block_content,
    ACTIONS(197), 2,
      sym__line,
      sym__newline,
  [1670] = 3,
    STATE(94), 1,
      aux_sym__lines,
    STATE(130), 1,
      sym_code_block_content,
    ACTIONS(197), 2,
      sym__line,
      sym__newline,
  [1681] = 3,
    STATE(94), 1,
      aux_sym__lines,
    STATE(133), 1,
      sym_code_block_content,
    ACTIONS(197), 2,
      sym__line,
      sym__newline,
  [1692] = 3,
    STATE(94), 1,
      aux_sym__lines,
    STATE(129), 1,
      sym_code_block_content,
    ACTIONS(197), 2,
      sym__line,
      sym__newline,
  [1703] = 1,
    ACTIONS(205), 4,
      sym__section_out,
      sym__section_sibling,
      sym__eof,
      sym_section_header,
  [1710] = 3,
    STATE(94), 1,
      aux_sym__lines,
    STATE(141), 1,
      sym_code_block_content,
    ACTIONS(197), 2,
      sym__line,
      sym__newline,
  [1721] = 3,
    STATE(94), 1,
      aux_sym__lines,
    STATE(134), 1,
      sym_code_block_content,
    ACTIONS(197), 2,
      sym__line,
      sym__newline,
  [1732] = 3,
    ACTIONS(207), 1,
      sym__line,
    ACTIONS(209), 1,
      sym__newline,
    STATE(108), 1,
      aux_sym__lines,
  [1742] = 1,
    ACTIONS(203), 3,
      sym__section_in,
      sym__eof,
      sym_section_header,
  [1748] = 3,
    ACTIONS(211), 1,
      sym__line,
    ACTIONS(213), 1,
      sym__newline,
    STATE(144), 1,
      sym_code_block_language,
  [1758] = 1,
    ACTIONS(201), 3,
      sym__section_in,
      sym__eof,
      sym_section_header,
  [1764] = 1,
    ACTIONS(85), 3,
      sym__section_out,
      sym__section_sibling,
      sym__eof,
  [1770] = 1,
    ACTIONS(199), 3,
      sym__section_in,
      sym__eof,
      sym_section_header,
  [1776] = 3,
    ACTIONS(211), 1,
      sym__line,
    ACTIONS(215), 1,
      sym__newline,
    STATE(146), 1,
      sym_code_block_language,
  [1786] = 1,
    ACTIONS(217), 3,
      sym__section_out,
      sym__section_sibling,
      sym__eof,
  [1792] = 1,
    ACTIONS(115), 3,
      sym__section_out,
      sym__section_sibling,
      sym__eof,
  [1798] = 3,
    ACTIONS(211), 1,
      sym__line,
    ACTIONS(219), 1,
      sym__newline,
    STATE(148), 1,
      sym_code_block_language,
  [1808] = 1,
    ACTIONS(97), 3,
      sym__section_out,
      sym__section_sibling,
      sym__eof,
  [1814] = 1,
    ACTIONS(83), 3,
      sym__section_out,
      sym__section_sibling,
      sym__eof,
  [1820] = 1,
    ACTIONS(195), 3,
      sym__section_in,
      sym__eof,
      sym_section_header,
  [1826] = 1,
    ACTIONS(221), 3,
      sym__section_out,
      sym__section_sibling,
      sym__eof,
  [1832] = 2,
    STATE(108), 1,
      aux_sym__lines,
    ACTIONS(223), 2,
      sym__line,
      sym__newline,
  [1840] = 3,
    ACTIONS(211), 1,
      sym__line,
    ACTIONS(226), 1,
      sym__newline,
    STATE(150), 1,
      sym_code_block_language,
  [1850] = 1,
    ACTIONS(205), 3,
      sym__section_in,
      sym__eof,
      sym_section_header,
  [1856] = 3,
    ACTIONS(211), 1,
      sym__line,
    ACTIONS(228), 1,
      sym__newline,
    STATE(147), 1,
      sym_code_block_language,
  [1866] = 2,
    ACTIONS(178), 1,
      sym_section_header,
    STATE(75), 2,
      sym_section,
      aux_sym_section_children_repeat1,
  [1874] = 2,
    ACTIONS(230), 1,
      sym__line,
    STATE(19), 1,
      sym_content,
  [1881] = 2,
    ACTIONS(232), 1,
      sym__line,
    STATE(10), 1,
      sym_content,
  [1888] = 2,
    ACTIONS(3), 1,
      sym_section_header,
    STATE(106), 1,
      sym_section,
  [1895] = 2,
    ACTIONS(234), 1,
      sym__line,
    STATE(35), 1,
      sym_content,
  [1902] = 2,
    ACTIONS(236), 1,
      sym__line,
    STATE(21), 1,
      sym_content,
  [1909] = 1,
    ACTIONS(238), 1,
      sym__newline,
  [1913] = 1,
    ACTIONS(240), 1,
      sym__line,
  [1917] = 1,
    ACTIONS(242), 1,
      anon_sym_BQUOTE_BQUOTE_BQUOTE,
  [1921] = 1,
    ACTIONS(244), 1,
      anon_sym_BQUOTE_BQUOTE_BQUOTE,
  [1925] = 1,
    ACTIONS(246), 1,
      ts_builtin_sym_end,
  [1929] = 1,
    ACTIONS(248), 1,
      anon_sym_BQUOTE_BQUOTE_BQUOTE,
  [1933] = 1,
    ACTIONS(250), 1,
      anon_sym_BQUOTE_BQUOTE_BQUOTE,
  [1937] = 1,
    ACTIONS(252), 1,
      anon_sym_BQUOTE_BQUOTE_BQUOTE,
  [1941] = 1,
    ACTIONS(254), 1,
      anon_sym_BQUOTE_BQUOTE_BQUOTE,
  [1945] = 1,
    ACTIONS(256), 1,
      sym__newline,
  [1949] = 1,
    ACTIONS(258), 1,
      sym__newline,
  [1953] = 1,
    ACTIONS(260), 1,
      sym__newline,
  [1957] = 1,
    ACTIONS(262), 1,
      sym__newline,
  [1961] = 1,
    ACTIONS(264), 1,
      sym__newline,
  [1965] = 1,
    ACTIONS(266), 1,
      anon_sym_BQUOTE_BQUOTE_BQUOTE,
  [1969] = 1,
    ACTIONS(268), 1,
      sym__newline,
  [1973] = 1,
    ACTIONS(270), 1,
      sym__newline,
  [1977] = 1,
    ACTIONS(272), 1,
      sym__line,
  [1981] = 1,
    ACTIONS(274), 1,
      ts_builtin_sym_end,
  [1985] = 1,
    ACTIONS(276), 1,
      sym__line,
  [1989] = 1,
    ACTIONS(278), 1,
      ts_builtin_sym_end,
  [1993] = 1,
    ACTIONS(280), 1,
      anon_sym_BQUOTE_BQUOTE_BQUOTE,
  [1997] = 1,
    ACTIONS(282), 1,
      anon_sym_BQUOTE_BQUOTE_BQUOTE,
  [2001] = 1,
    ACTIONS(284), 1,
      sym__newline,
  [2005] = 1,
    ACTIONS(286), 1,
      anon_sym_BQUOTE_BQUOTE_BQUOTE,
  [2009] = 1,
    ACTIONS(288), 1,
      sym__newline,
  [2013] = 1,
    ACTIONS(290), 1,
      sym__newline,
  [2017] = 1,
    ACTIONS(292), 1,
      ts_builtin_sym_end,
  [2021] = 1,
    ACTIONS(294), 1,
      sym__newline,
  [2025] = 1,
    ACTIONS(296), 1,
      sym__newline,
  [2029] = 1,
    ACTIONS(298), 1,
      sym__newline,
  [2033] = 1,
    ACTIONS(300), 1,
      sym__newline,
  [2037] = 1,
    ACTIONS(302), 1,
      sym__newline,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(4)] = 0,
  [SMALL_STATE(5)] = 27,
  [SMALL_STATE(6)] = 54,
  [SMALL_STATE(7)] = 81,
  [SMALL_STATE(8)] = 107,
  [SMALL_STATE(9)] = 133,
  [SMALL_STATE(10)] = 159,
  [SMALL_STATE(11)] = 191,
  [SMALL_STATE(12)] = 217,
  [SMALL_STATE(13)] = 243,
  [SMALL_STATE(14)] = 269,
  [SMALL_STATE(15)] = 300,
  [SMALL_STATE(16)] = 331,
  [SMALL_STATE(17)] = 356,
  [SMALL_STATE(18)] = 381,
  [SMALL_STATE(19)] = 412,
  [SMALL_STATE(20)] = 443,
  [SMALL_STATE(21)] = 468,
  [SMALL_STATE(22)] = 499,
  [SMALL_STATE(23)] = 524,
  [SMALL_STATE(24)] = 549,
  [SMALL_STATE(25)] = 580,
  [SMALL_STATE(26)] = 611,
  [SMALL_STATE(27)] = 642,
  [SMALL_STATE(28)] = 667,
  [SMALL_STATE(29)] = 690,
  [SMALL_STATE(30)] = 717,
  [SMALL_STATE(31)] = 750,
  [SMALL_STATE(32)] = 773,
  [SMALL_STATE(33)] = 798,
  [SMALL_STATE(34)] = 820,
  [SMALL_STATE(35)] = 838,
  [SMALL_STATE(36)] = 868,
  [SMALL_STATE(37)] = 894,
  [SMALL_STATE(38)] = 916,
  [SMALL_STATE(39)] = 942,
  [SMALL_STATE(40)] = 960,
  [SMALL_STATE(41)] = 984,
  [SMALL_STATE(42)] = 1006,
  [SMALL_STATE(43)] = 1031,
  [SMALL_STATE(44)] = 1048,
  [SMALL_STATE(45)] = 1065,
  [SMALL_STATE(46)] = 1082,
  [SMALL_STATE(47)] = 1099,
  [SMALL_STATE(48)] = 1116,
  [SMALL_STATE(49)] = 1137,
  [SMALL_STATE(50)] = 1158,
  [SMALL_STATE(51)] = 1174,
  [SMALL_STATE(52)] = 1192,
  [SMALL_STATE(53)] = 1208,
  [SMALL_STATE(54)] = 1224,
  [SMALL_STATE(55)] = 1240,
  [SMALL_STATE(56)] = 1256,
  [SMALL_STATE(57)] = 1272,
  [SMALL_STATE(58)] = 1287,
  [SMALL_STATE(59)] = 1304,
  [SMALL_STATE(60)] = 1321,
  [SMALL_STATE(61)] = 1341,
  [SMALL_STATE(62)] = 1357,
  [SMALL_STATE(63)] = 1377,
  [SMALL_STATE(64)] = 1389,
  [SMALL_STATE(65)] = 1401,
  [SMALL_STATE(66)] = 1421,
  [SMALL_STATE(67)] = 1441,
  [SMALL_STATE(68)] = 1452,
  [SMALL_STATE(69)] = 1463,
  [SMALL_STATE(70)] = 1474,
  [SMALL_STATE(71)] = 1485,
  [SMALL_STATE(72)] = 1496,
  [SMALL_STATE(73)] = 1506,
  [SMALL_STATE(74)] = 1516,
  [SMALL_STATE(75)] = 1526,
  [SMALL_STATE(76)] = 1539,
  [SMALL_STATE(77)] = 1552,
  [SMALL_STATE(78)] = 1566,
  [SMALL_STATE(79)] = 1580,
  [SMALL_STATE(80)] = 1594,
  [SMALL_STATE(81)] = 1605,
  [SMALL_STATE(82)] = 1612,
  [SMALL_STATE(83)] = 1619,
  [SMALL_STATE(84)] = 1630,
  [SMALL_STATE(85)] = 1641,
  [SMALL_STATE(86)] = 1652,
  [SMALL_STATE(87)] = 1659,
  [SMALL_STATE(88)] = 1670,
  [SMALL_STATE(89)] = 1681,
  [SMALL_STATE(90)] = 1692,
  [SMALL_STATE(91)] = 1703,
  [SMALL_STATE(92)] = 1710,
  [SMALL_STATE(93)] = 1721,
  [SMALL_STATE(94)] = 1732,
  [SMALL_STATE(95)] = 1742,
  [SMALL_STATE(96)] = 1748,
  [SMALL_STATE(97)] = 1758,
  [SMALL_STATE(98)] = 1764,
  [SMALL_STATE(99)] = 1770,
  [SMALL_STATE(100)] = 1776,
  [SMALL_STATE(101)] = 1786,
  [SMALL_STATE(102)] = 1792,
  [SMALL_STATE(103)] = 1798,
  [SMALL_STATE(104)] = 1808,
  [SMALL_STATE(105)] = 1814,
  [SMALL_STATE(106)] = 1820,
  [SMALL_STATE(107)] = 1826,
  [SMALL_STATE(108)] = 1832,
  [SMALL_STATE(109)] = 1840,
  [SMALL_STATE(110)] = 1850,
  [SMALL_STATE(111)] = 1856,
  [SMALL_STATE(112)] = 1866,
  [SMALL_STATE(113)] = 1874,
  [SMALL_STATE(114)] = 1881,
  [SMALL_STATE(115)] = 1888,
  [SMALL_STATE(116)] = 1895,
  [SMALL_STATE(117)] = 1902,
  [SMALL_STATE(118)] = 1909,
  [SMALL_STATE(119)] = 1913,
  [SMALL_STATE(120)] = 1917,
  [SMALL_STATE(121)] = 1921,
  [SMALL_STATE(122)] = 1925,
  [SMALL_STATE(123)] = 1929,
  [SMALL_STATE(124)] = 1933,
  [SMALL_STATE(125)] = 1937,
  [SMALL_STATE(126)] = 1941,
  [SMALL_STATE(127)] = 1945,
  [SMALL_STATE(128)] = 1949,
  [SMALL_STATE(129)] = 1953,
  [SMALL_STATE(130)] = 1957,
  [SMALL_STATE(131)] = 1961,
  [SMALL_STATE(132)] = 1965,
  [SMALL_STATE(133)] = 1969,
  [SMALL_STATE(134)] = 1973,
  [SMALL_STATE(135)] = 1977,
  [SMALL_STATE(136)] = 1981,
  [SMALL_STATE(137)] = 1985,
  [SMALL_STATE(138)] = 1989,
  [SMALL_STATE(139)] = 1993,
  [SMALL_STATE(140)] = 1997,
  [SMALL_STATE(141)] = 2001,
  [SMALL_STATE(142)] = 2005,
  [SMALL_STATE(143)] = 2009,
  [SMALL_STATE(144)] = 2013,
  [SMALL_STATE(145)] = 2017,
  [SMALL_STATE(146)] = 2021,
  [SMALL_STATE(147)] = 2025,
  [SMALL_STATE(148)] = 2029,
  [SMALL_STATE(149)] = 2033,
  [SMALL_STATE(150)] = 2037,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(137),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(119),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(115),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(136),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(137),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(119),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(22),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(111),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(112),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(82),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(97),
  [27] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_body_repeat1, 2, 0, 0),
  [29] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_body_repeat1, 2, 0, 0), SHIFT_REPEAT(4),
  [32] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_body_repeat1, 2, 0, 0), SHIFT_REPEAT(109),
  [35] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_body_repeat1, 2, 0, 0),
  [37] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_body, 2, 0, 0),
  [39] = {.entry = {.count = 1, .reusable = false}}, SHIFT(4),
  [41] = {.entry = {.count = 1, .reusable = false}}, SHIFT(109),
  [43] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_body, 2, 0, 0),
  [45] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_body, 1, 0, 0),
  [47] = {.entry = {.count = 1, .reusable = false}}, SHIFT(5),
  [49] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_body, 1, 0, 0),
  [51] = {.entry = {.count = 1, .reusable = false}}, SHIFT(13),
  [53] = {.entry = {.count = 1, .reusable = false}}, SHIFT(100),
  [55] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_body_repeat1, 2, 0, 0), SHIFT_REPEAT(8),
  [58] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_body_repeat1, 2, 0, 0), SHIFT_REPEAT(103),
  [61] = {.entry = {.count = 1, .reusable = false}}, SHIFT(8),
  [63] = {.entry = {.count = 1, .reusable = false}}, SHIFT(103),
  [65] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_item, 2, 0, 0),
  [67] = {.entry = {.count = 1, .reusable = false}}, SHIFT(6),
  [69] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [71] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_item, 2, 0, 0),
  [73] = {.entry = {.count = 1, .reusable = false}}, SHIFT(9),
  [75] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_body_repeat1, 2, 0, 0), SHIFT_REPEAT(12),
  [78] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_body_repeat1, 2, 0, 0), SHIFT_REPEAT(100),
  [81] = {.entry = {.count = 1, .reusable = false}}, SHIFT(12),
  [83] = {.entry = {.count = 1, .reusable = true}}, SHIFT(86),
  [85] = {.entry = {.count = 1, .reusable = true}}, SHIFT(95),
  [87] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_children, 2, 0, 0),
  [89] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [91] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_body_repeat1, 2, 0, 0), SHIFT_REPEAT(17),
  [94] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_body_repeat1, 2, 0, 0), SHIFT_REPEAT(96),
  [97] = {.entry = {.count = 1, .reusable = true}}, SHIFT(99),
  [99] = {.entry = {.count = 1, .reusable = false}}, SHIFT(11),
  [101] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [103] = {.entry = {.count = 1, .reusable = false}}, SHIFT(17),
  [105] = {.entry = {.count = 1, .reusable = false}}, SHIFT(96),
  [107] = {.entry = {.count = 1, .reusable = false}}, SHIFT(7),
  [109] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [111] = {.entry = {.count = 1, .reusable = false}}, SHIFT(27),
  [113] = {.entry = {.count = 1, .reusable = false}}, SHIFT(20),
  [115] = {.entry = {.count = 1, .reusable = true}}, SHIFT(81),
  [117] = {.entry = {.count = 1, .reusable = false}}, SHIFT(32),
  [119] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym__lines, 2, 0, 0),
  [121] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__lines, 2, 0, 0), SHIFT_REPEAT(28),
  [124] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__lines, 2, 0, 0),
  [126] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(137),
  [129] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(119),
  [132] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0),
  [134] = {.entry = {.count = 1, .reusable = true}}, SHIFT(138),
  [136] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_body_repeat1, 2, 0, 0), SHIFT_REPEAT(32),
  [139] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_body_repeat1, 2, 0, 0), SHIFT_REPEAT(111),
  [142] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__lines, 2, 0, 0), SHIFT_REPEAT(33),
  [145] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_code_block, 5, 0, 0),
  [147] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_code_block, 5, 0, 0),
  [149] = {.entry = {.count = 1, .reusable = false}}, SHIFT(23),
  [151] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [153] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__lines, 2, 0, 0), SHIFT_REPEAT(37),
  [156] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_code_block, 6, 0, 0),
  [158] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_code_block, 6, 0, 0),
  [160] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [162] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_content, 1, 0, 0),
  [164] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_content, 1, 0, 0),
  [166] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__lines, 2, 0, 0), SHIFT_REPEAT(48),
  [169] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__lines, 2, 0, 0), SHIFT_REPEAT(49),
  [172] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_item, 3, 0, 0),
  [174] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_item, 4, 0, 0),
  [176] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_children, 3, 0, 0),
  [178] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [180] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_section_children, 2, 0, 0),
  [182] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_section_children_repeat1, 2, 0, 0), SHIFT_REPEAT(2),
  [185] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_section_children_repeat1, 2, 0, 0),
  [187] = {.entry = {.count = 1, .reusable = true}}, SHIFT(145),
  [189] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat2, 2, 0, 0), SHIFT_REPEAT(3),
  [192] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat2, 2, 0, 0), SHIFT_REPEAT(115),
  [195] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_document_repeat2, 2, 0, 0),
  [197] = {.entry = {.count = 1, .reusable = false}}, SHIFT(94),
  [199] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_section, 3, 0, 0),
  [201] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_section, 2, 0, 0),
  [203] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_section, 4, 0, 0),
  [205] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_section, 5, 0, 0),
  [207] = {.entry = {.count = 1, .reusable = false}}, SHIFT(108),
  [209] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_code_block_content, 1, 0, 0),
  [211] = {.entry = {.count = 1, .reusable = false}}, SHIFT(149),
  [213] = {.entry = {.count = 1, .reusable = false}}, SHIFT(85),
  [215] = {.entry = {.count = 1, .reusable = false}}, SHIFT(90),
  [217] = {.entry = {.count = 1, .reusable = true}}, SHIFT(110),
  [219] = {.entry = {.count = 1, .reusable = false}}, SHIFT(83),
  [221] = {.entry = {.count = 1, .reusable = true}}, SHIFT(91),
  [223] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__lines, 2, 0, 0), SHIFT_REPEAT(108),
  [226] = {.entry = {.count = 1, .reusable = false}}, SHIFT(89),
  [228] = {.entry = {.count = 1, .reusable = false}}, SHIFT(80),
  [230] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [232] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [234] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [236] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [238] = {.entry = {.count = 1, .reusable = true}}, SHIFT(124),
  [240] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_marker_property, 1, 0, 0),
  [242] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [244] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [246] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [248] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [250] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [252] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [254] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [256] = {.entry = {.count = 1, .reusable = true}}, SHIFT(132),
  [258] = {.entry = {.count = 1, .reusable = true}}, SHIFT(139),
  [260] = {.entry = {.count = 1, .reusable = true}}, SHIFT(120),
  [262] = {.entry = {.count = 1, .reusable = true}}, SHIFT(121),
  [264] = {.entry = {.count = 1, .reusable = true}}, SHIFT(123),
  [266] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [268] = {.entry = {.count = 1, .reusable = true}}, SHIFT(125),
  [270] = {.entry = {.count = 1, .reusable = true}}, SHIFT(126),
  [272] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_marker, 1, 0, 0),
  [274] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 1, 0, 0),
  [276] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_marker_task, 1, 0, 0),
  [278] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 2, 0, 0),
  [280] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [282] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [284] = {.entry = {.count = 1, .reusable = true}}, SHIFT(140),
  [286] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [288] = {.entry = {.count = 1, .reusable = true}}, SHIFT(142),
  [290] = {.entry = {.count = 1, .reusable = true}}, SHIFT(84),
  [292] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 3, 0, 0),
  [294] = {.entry = {.count = 1, .reusable = true}}, SHIFT(88),
  [296] = {.entry = {.count = 1, .reusable = true}}, SHIFT(92),
  [298] = {.entry = {.count = 1, .reusable = true}}, SHIFT(87),
  [300] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_code_block_language, 1, 0, 0),
  [302] = {.entry = {.count = 1, .reusable = true}}, SHIFT(93),
};

enum ts_external_scanner_symbol_identifiers {
  ts_external_token__indent = 0,
  ts_external_token__dedent = 1,
  ts_external_token__section_in = 2,
  ts_external_token__section_out = 3,
  ts_external_token__section_sibling = 4,
  ts_external_token__eof = 5,
};

static const TSSymbol ts_external_scanner_symbol_map[EXTERNAL_TOKEN_COUNT] = {
  [ts_external_token__indent] = sym__indent,
  [ts_external_token__dedent] = sym__dedent,
  [ts_external_token__section_in] = sym__section_in,
  [ts_external_token__section_out] = sym__section_out,
  [ts_external_token__section_sibling] = sym__section_sibling,
  [ts_external_token__eof] = sym__eof,
};

static const bool ts_external_scanner_states[10][EXTERNAL_TOKEN_COUNT] = {
  [1] = {
    [ts_external_token__indent] = true,
    [ts_external_token__dedent] = true,
    [ts_external_token__section_in] = true,
    [ts_external_token__section_out] = true,
    [ts_external_token__section_sibling] = true,
    [ts_external_token__eof] = true,
  },
  [2] = {
    [ts_external_token__section_in] = true,
    [ts_external_token__eof] = true,
  },
  [3] = {
    [ts_external_token__section_in] = true,
    [ts_external_token__section_out] = true,
    [ts_external_token__section_sibling] = true,
    [ts_external_token__eof] = true,
  },
  [4] = {
    [ts_external_token__indent] = true,
    [ts_external_token__section_in] = true,
    [ts_external_token__section_out] = true,
    [ts_external_token__section_sibling] = true,
    [ts_external_token__eof] = true,
  },
  [5] = {
    [ts_external_token__indent] = true,
    [ts_external_token__dedent] = true,
    [ts_external_token__section_in] = true,
    [ts_external_token__eof] = true,
  },
  [6] = {
    [ts_external_token__dedent] = true,
    [ts_external_token__section_in] = true,
    [ts_external_token__section_out] = true,
    [ts_external_token__section_sibling] = true,
    [ts_external_token__eof] = true,
  },
  [7] = {
    [ts_external_token__indent] = true,
    [ts_external_token__section_in] = true,
    [ts_external_token__eof] = true,
  },
  [8] = {
    [ts_external_token__dedent] = true,
    [ts_external_token__section_in] = true,
    [ts_external_token__eof] = true,
  },
  [9] = {
    [ts_external_token__section_out] = true,
    [ts_external_token__section_sibling] = true,
    [ts_external_token__eof] = true,
  },
};

#ifdef __cplusplus
extern "C" {
#endif
void *tree_sitter_note_external_scanner_create(void);
void tree_sitter_note_external_scanner_destroy(void *);
bool tree_sitter_note_external_scanner_scan(void *, TSLexer *, const bool *);
unsigned tree_sitter_note_external_scanner_serialize(void *, char *);
void tree_sitter_note_external_scanner_deserialize(void *, const char *, unsigned);

#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_note(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .external_scanner = {
      &ts_external_scanner_states[0][0],
      ts_external_scanner_symbol_map,
      tree_sitter_note_external_scanner_create,
      tree_sitter_note_external_scanner_destroy,
      tree_sitter_note_external_scanner_scan,
      tree_sitter_note_external_scanner_serialize,
      tree_sitter_note_external_scanner_deserialize,
    },
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
