#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 141
#define LARGE_STATE_COUNT 4
#define SYMBOL_COUNT 36
#define ALIAS_COUNT 0
#define TOKEN_COUNT 18
#define EXTERNAL_TOKEN_COUNT 6
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 5
#define PRODUCTION_ID_COUNT 1

enum ts_symbol_identifiers {
  sym_section_header = 1,
  sym_marker_task_pending = 2,
  sym_marker_task_done = 3,
  sym_marker_property_info = 4,
  sym_marker_property_label = 5,
  sym__line = 6,
  sym__newline = 7,
  anon_sym_BQUOTE_BQUOTE_BQUOTE_LF = 8,
  anon_sym_LF_BQUOTE_BQUOTE_BQUOTE = 9,
  anon_sym_LF = 10,
  anon_sym_LF_BQUOTE_BQUOTE_BQUOTE_LF = 11,
  sym__indent = 12,
  sym__dedent = 13,
  sym__section_in = 14,
  sym__section_out = 15,
  sym__section_sibling = 16,
  sym__eof = 17,
  sym_document = 18,
  sym_section_children = 19,
  sym_section = 20,
  sym_marker_task = 21,
  sym_marker_property = 22,
  sym_marker = 23,
  sym_content = 24,
  sym_body = 25,
  sym_item = 26,
  sym_children = 27,
  aux_sym__lines = 28,
  sym_code_block_language = 29,
  sym_code_block_content = 30,
  sym_code_block = 31,
  aux_sym_document_repeat1 = 32,
  aux_sym_document_repeat2 = 33,
  aux_sym_section_children_repeat1 = 34,
  aux_sym_body_repeat1 = 35,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_section_header] = "section_header",
  [sym_marker_task_pending] = "marker_task_pending",
  [sym_marker_task_done] = "marker_task_done",
  [sym_marker_property_info] = "marker_property_info",
  [sym_marker_property_label] = "marker_property_label",
  [sym__line] = "_line",
  [sym__newline] = "_newline",
  [anon_sym_BQUOTE_BQUOTE_BQUOTE_LF] = "```\n",
  [anon_sym_LF_BQUOTE_BQUOTE_BQUOTE] = "\n```",
  [anon_sym_LF] = "\n",
  [anon_sym_LF_BQUOTE_BQUOTE_BQUOTE_LF] = "\n```\n",
  [sym__indent] = "_indent",
  [sym__dedent] = "_dedent",
  [sym__section_in] = "_section_in",
  [sym__section_out] = "_section_out",
  [sym__section_sibling] = "_section_sibling",
  [sym__eof] = "_eof",
  [sym_document] = "document",
  [sym_section_children] = "section_children",
  [sym_section] = "section",
  [sym_marker_task] = "marker_task",
  [sym_marker_property] = "marker_property",
  [sym_marker] = "marker",
  [sym_content] = "content",
  [sym_body] = "body",
  [sym_item] = "item",
  [sym_children] = "children",
  [aux_sym__lines] = "_lines",
  [sym_code_block_language] = "code_block_language",
  [sym_code_block_content] = "code_block_content",
  [sym_code_block] = "code_block",
  [aux_sym_document_repeat1] = "document_repeat1",
  [aux_sym_document_repeat2] = "document_repeat2",
  [aux_sym_section_children_repeat1] = "section_children_repeat1",
  [aux_sym_body_repeat1] = "body_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_section_header] = sym_section_header,
  [sym_marker_task_pending] = sym_marker_task_pending,
  [sym_marker_task_done] = sym_marker_task_done,
  [sym_marker_property_info] = sym_marker_property_info,
  [sym_marker_property_label] = sym_marker_property_label,
  [sym__line] = sym__line,
  [sym__newline] = sym__newline,
  [anon_sym_BQUOTE_BQUOTE_BQUOTE_LF] = anon_sym_BQUOTE_BQUOTE_BQUOTE_LF,
  [anon_sym_LF_BQUOTE_BQUOTE_BQUOTE] = anon_sym_LF_BQUOTE_BQUOTE_BQUOTE,
  [anon_sym_LF] = anon_sym_LF,
  [anon_sym_LF_BQUOTE_BQUOTE_BQUOTE_LF] = anon_sym_LF_BQUOTE_BQUOTE_BQUOTE_LF,
  [sym__indent] = sym__indent,
  [sym__dedent] = sym__dedent,
  [sym__section_in] = sym__section_in,
  [sym__section_out] = sym__section_out,
  [sym__section_sibling] = sym__section_sibling,
  [sym__eof] = sym__eof,
  [sym_document] = sym_document,
  [sym_section_children] = sym_section_children,
  [sym_section] = sym_section,
  [sym_marker_task] = sym_marker_task,
  [sym_marker_property] = sym_marker_property,
  [sym_marker] = sym_marker,
  [sym_content] = sym_content,
  [sym_body] = sym_body,
  [sym_item] = sym_item,
  [sym_children] = sym_children,
  [aux_sym__lines] = aux_sym__lines,
  [sym_code_block_language] = sym_code_block_language,
  [sym_code_block_content] = sym_code_block_content,
  [sym_code_block] = sym_code_block,
  [aux_sym_document_repeat1] = aux_sym_document_repeat1,
  [aux_sym_document_repeat2] = aux_sym_document_repeat2,
  [aux_sym_section_children_repeat1] = aux_sym_section_children_repeat1,
  [aux_sym_body_repeat1] = aux_sym_body_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_section_header] = {
    .visible = true,
    .named = true,
  },
  [sym_marker_task_pending] = {
    .visible = true,
    .named = true,
  },
  [sym_marker_task_done] = {
    .visible = true,
    .named = true,
  },
  [sym_marker_property_info] = {
    .visible = true,
    .named = true,
  },
  [sym_marker_property_label] = {
    .visible = true,
    .named = true,
  },
  [sym__line] = {
    .visible = false,
    .named = true,
  },
  [sym__newline] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_BQUOTE_BQUOTE_BQUOTE_LF] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LF_BQUOTE_BQUOTE_BQUOTE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LF] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LF_BQUOTE_BQUOTE_BQUOTE_LF] = {
    .visible = true,
    .named = false,
  },
  [sym__indent] = {
    .visible = false,
    .named = true,
  },
  [sym__dedent] = {
    .visible = false,
    .named = true,
  },
  [sym__section_in] = {
    .visible = false,
    .named = true,
  },
  [sym__section_out] = {
    .visible = false,
    .named = true,
  },
  [sym__section_sibling] = {
    .visible = false,
    .named = true,
  },
  [sym__eof] = {
    .visible = false,
    .named = true,
  },
  [sym_document] = {
    .visible = true,
    .named = true,
  },
  [sym_section_children] = {
    .visible = true,
    .named = true,
  },
  [sym_section] = {
    .visible = true,
    .named = true,
  },
  [sym_marker_task] = {
    .visible = true,
    .named = true,
  },
  [sym_marker_property] = {
    .visible = true,
    .named = true,
  },
  [sym_marker] = {
    .visible = true,
    .named = true,
  },
  [sym_content] = {
    .visible = true,
    .named = true,
  },
  [sym_body] = {
    .visible = true,
    .named = true,
  },
  [sym_item] = {
    .visible = true,
    .named = true,
  },
  [sym_children] = {
    .visible = true,
    .named = true,
  },
  [aux_sym__lines] = {
    .visible = false,
    .named = false,
  },
  [sym_code_block_language] = {
    .visible = true,
    .named = true,
  },
  [sym_code_block_content] = {
    .visible = true,
    .named = true,
  },
  [sym_code_block] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_document_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_document_repeat2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_section_children_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_body_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 2,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 4,
  [8] = 6,
  [9] = 5,
  [10] = 4,
  [11] = 11,
  [12] = 6,
  [13] = 5,
  [14] = 11,
  [15] = 5,
  [16] = 4,
  [17] = 5,
  [18] = 18,
  [19] = 4,
  [20] = 6,
  [21] = 11,
  [22] = 6,
  [23] = 18,
  [24] = 24,
  [25] = 11,
  [26] = 18,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 27,
  [34] = 34,
  [35] = 24,
  [36] = 28,
  [37] = 31,
  [38] = 38,
  [39] = 18,
  [40] = 18,
  [41] = 28,
  [42] = 32,
  [43] = 29,
  [44] = 34,
  [45] = 28,
  [46] = 34,
  [47] = 29,
  [48] = 32,
  [49] = 38,
  [50] = 34,
  [51] = 34,
  [52] = 32,
  [53] = 32,
  [54] = 38,
  [55] = 29,
  [56] = 38,
  [57] = 57,
  [58] = 57,
  [59] = 57,
  [60] = 60,
  [61] = 57,
  [62] = 62,
  [63] = 63,
  [64] = 60,
  [65] = 60,
  [66] = 60,
  [67] = 67,
  [68] = 63,
  [69] = 63,
  [70] = 62,
  [71] = 62,
  [72] = 67,
  [73] = 62,
  [74] = 63,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 81,
  [83] = 80,
  [84] = 18,
  [85] = 80,
  [86] = 81,
  [87] = 80,
  [88] = 81,
  [89] = 89,
  [90] = 90,
  [91] = 91,
  [92] = 92,
  [93] = 81,
  [94] = 80,
  [95] = 95,
  [96] = 96,
  [97] = 97,
  [98] = 89,
  [99] = 99,
  [100] = 92,
  [101] = 101,
  [102] = 102,
  [103] = 90,
  [104] = 97,
  [105] = 95,
  [106] = 101,
  [107] = 102,
  [108] = 108,
  [109] = 109,
  [110] = 109,
  [111] = 109,
  [112] = 109,
  [113] = 109,
  [114] = 108,
  [115] = 108,
  [116] = 108,
  [117] = 117,
  [118] = 118,
  [119] = 119,
  [120] = 120,
  [121] = 121,
  [122] = 122,
  [123] = 120,
  [124] = 122,
  [125] = 125,
  [126] = 126,
  [127] = 120,
  [128] = 128,
  [129] = 122,
  [130] = 130,
  [131] = 122,
  [132] = 120,
  [133] = 118,
  [134] = 118,
  [135] = 118,
  [136] = 118,
  [137] = 122,
  [138] = 138,
  [139] = 139,
  [140] = 120,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(22);
      if (lookahead == '\n') ADVANCE(51);
      if (lookahead == '#') ADVANCE(41);
      if (lookahead == '*') ADVANCE(37);
      if (lookahead == '-') ADVANCE(38);
      if (lookahead == '.') ADVANCE(39);
      if (lookahead == '[') ADVANCE(40);
      if (lookahead == '`') ADVANCE(43);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(28);
      if (lookahead != 0) ADVANCE(49);
      END_STATE();
    case 1:
      if (lookahead == '\n') ADVANCE(23);
      if (lookahead != 0) ADVANCE(1);
      END_STATE();
    case 2:
      if (lookahead == '\n') ADVANCE(2);
      if (lookahead == '#') ADVANCE(18);
      if (lookahead == '*') ADVANCE(14);
      if (lookahead == '-') ADVANCE(15);
      if (lookahead == '.') ADVANCE(16);
      if (lookahead == '[') ADVANCE(17);
      if (lookahead == '`') ADVANCE(20);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(3);
      END_STATE();
    case 3:
      if (lookahead == '\n') ADVANCE(2);
      if (lookahead == '#') ADVANCE(18);
      if (lookahead == '*') ADVANCE(14);
      if (lookahead == '-') ADVANCE(15);
      if (lookahead == '.') ADVANCE(16);
      if (lookahead == '[') ADVANCE(17);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(3);
      END_STATE();
    case 4:
      if (lookahead == '\n') ADVANCE(58);
      END_STATE();
    case 5:
      if (lookahead == '\n') ADVANCE(52);
      if (lookahead == '*') ADVANCE(37);
      if (lookahead == '-') ADVANCE(38);
      if (lookahead == '.') ADVANCE(39);
      if (lookahead == '[') ADVANCE(40);
      if (lookahead == '`') ADVANCE(43);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(32);
      if (lookahead != 0) ADVANCE(49);
      END_STATE();
    case 6:
      if (lookahead == '\n') ADVANCE(53);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(33);
      if (lookahead != 0) ADVANCE(49);
      END_STATE();
    case 7:
      if (lookahead == '\n') ADVANCE(54);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(34);
      if (lookahead != 0) ADVANCE(49);
      END_STATE();
    case 8:
      if (lookahead == '\n') SKIP(8);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(48);
      if (lookahead != 0) ADVANCE(49);
      END_STATE();
    case 9:
      if (lookahead == '\n') ADVANCE(57);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(9);
      END_STATE();
    case 10:
      if (lookahead == '\n') ADVANCE(11);
      if (lookahead == '*') ADVANCE(37);
      if (lookahead == '-') ADVANCE(38);
      if (lookahead == '.') ADVANCE(39);
      if (lookahead == '[') ADVANCE(40);
      if (lookahead == '`') ADVANCE(43);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(35);
      if (lookahead != 0) ADVANCE(49);
      END_STATE();
    case 11:
      if (lookahead == '\n') ADVANCE(11);
      if (lookahead == '*') ADVANCE(37);
      if (lookahead == '-') ADVANCE(38);
      if (lookahead == '.') ADVANCE(39);
      if (lookahead == '[') ADVANCE(40);
      if (lookahead == '`') ADVANCE(45);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(35);
      if (lookahead != 0) ADVANCE(49);
      END_STATE();
    case 12:
      if (lookahead == '\n') ADVANCE(13);
      if (lookahead == '#') ADVANCE(41);
      if (lookahead == '*') ADVANCE(37);
      if (lookahead == '-') ADVANCE(38);
      if (lookahead == '.') ADVANCE(39);
      if (lookahead == '[') ADVANCE(40);
      if (lookahead == '`') ADVANCE(43);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(36);
      if (lookahead != 0) ADVANCE(49);
      END_STATE();
    case 13:
      if (lookahead == '\n') ADVANCE(13);
      if (lookahead == '#') ADVANCE(41);
      if (lookahead == '*') ADVANCE(37);
      if (lookahead == '-') ADVANCE(38);
      if (lookahead == '.') ADVANCE(39);
      if (lookahead == '[') ADVANCE(40);
      if (lookahead == '`') ADVANCE(45);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(36);
      if (lookahead != 0) ADVANCE(49);
      END_STATE();
    case 14:
      if (lookahead == ' ') ADVANCE(26);
      END_STATE();
    case 15:
      if (lookahead == ' ') ADVANCE(24);
      END_STATE();
    case 16:
      if (lookahead == ' ') ADVANCE(25);
      END_STATE();
    case 17:
      if (lookahead == ' ') ADVANCE(27);
      END_STATE();
    case 18:
      if (lookahead == ' ') ADVANCE(21);
      if (lookahead == '#') ADVANCE(18);
      END_STATE();
    case 19:
      if (lookahead == '`') ADVANCE(4);
      END_STATE();
    case 20:
      if (lookahead == '`') ADVANCE(19);
      END_STATE();
    case 21:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(1);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(sym_section_header);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(sym_marker_task_pending);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(sym_marker_task_done);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(sym_marker_property_info);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(sym_marker_property_label);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(sym__line);
      if (lookahead == '\n') ADVANCE(51);
      if (lookahead == '#') ADVANCE(41);
      if (lookahead == '*') ADVANCE(37);
      if (lookahead == '-') ADVANCE(38);
      if (lookahead == '.') ADVANCE(39);
      if (lookahead == '[') ADVANCE(40);
      if (lookahead == '`') ADVANCE(43);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(28);
      if (lookahead != 0) ADVANCE(49);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(sym__line);
      if (lookahead == '\n') ADVANCE(23);
      if (lookahead != 0) ADVANCE(29);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(sym__line);
      if (lookahead == '\n') ADVANCE(55);
      if (lookahead != 0) ADVANCE(49);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(sym__line);
      if (lookahead == '\n') ADVANCE(58);
      if (lookahead != 0) ADVANCE(49);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(sym__line);
      if (lookahead == '\n') ADVANCE(52);
      if (lookahead == '*') ADVANCE(37);
      if (lookahead == '-') ADVANCE(38);
      if (lookahead == '.') ADVANCE(39);
      if (lookahead == '[') ADVANCE(40);
      if (lookahead == '`') ADVANCE(43);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(32);
      if (lookahead != 0) ADVANCE(49);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(sym__line);
      if (lookahead == '\n') ADVANCE(53);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(33);
      if (lookahead != 0) ADVANCE(49);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(sym__line);
      if (lookahead == '\n') ADVANCE(54);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(34);
      if (lookahead != 0) ADVANCE(49);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(sym__line);
      if (lookahead == '\n') ADVANCE(11);
      if (lookahead == '*') ADVANCE(37);
      if (lookahead == '-') ADVANCE(38);
      if (lookahead == '.') ADVANCE(39);
      if (lookahead == '[') ADVANCE(40);
      if (lookahead == '`') ADVANCE(43);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(35);
      if (lookahead != 0) ADVANCE(49);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(sym__line);
      if (lookahead == '\n') ADVANCE(13);
      if (lookahead == '#') ADVANCE(41);
      if (lookahead == '*') ADVANCE(37);
      if (lookahead == '-') ADVANCE(38);
      if (lookahead == '.') ADVANCE(39);
      if (lookahead == '[') ADVANCE(40);
      if (lookahead == '`') ADVANCE(43);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(36);
      if (lookahead != 0) ADVANCE(49);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(sym__line);
      if (lookahead == ' ') ADVANCE(26);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(49);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(sym__line);
      if (lookahead == ' ') ADVANCE(24);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(49);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(sym__line);
      if (lookahead == ' ') ADVANCE(25);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(49);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(sym__line);
      if (lookahead == ' ') ADVANCE(27);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(49);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(sym__line);
      if (lookahead == ' ') ADVANCE(50);
      if (lookahead == '#') ADVANCE(41);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(49);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(sym__line);
      if (lookahead == '`') ADVANCE(56);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(49);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(sym__line);
      if (lookahead == '`') ADVANCE(44);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(49);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(sym__line);
      if (lookahead == '`') ADVANCE(30);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(49);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(sym__line);
      if (lookahead == '`') ADVANCE(42);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(49);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(sym__line);
      if (lookahead == '`') ADVANCE(31);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(49);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(sym__line);
      if (lookahead == '`') ADVANCE(46);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(49);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(sym__line);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(48);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(49);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(sym__line);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(49);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(sym__line);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(29);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(sym__newline);
      if (lookahead == '\n') ADVANCE(51);
      if (lookahead == '#') ADVANCE(41);
      if (lookahead == '*') ADVANCE(37);
      if (lookahead == '-') ADVANCE(38);
      if (lookahead == '.') ADVANCE(39);
      if (lookahead == '[') ADVANCE(40);
      if (lookahead == '`') ADVANCE(45);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(28);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(sym__newline);
      if (lookahead == '\n') ADVANCE(52);
      if (lookahead == '*') ADVANCE(37);
      if (lookahead == '-') ADVANCE(38);
      if (lookahead == '.') ADVANCE(39);
      if (lookahead == '[') ADVANCE(40);
      if (lookahead == '`') ADVANCE(45);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(32);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(sym__newline);
      if (lookahead == '\n') ADVANCE(53);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(33);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(sym__newline);
      if (lookahead == '\n') ADVANCE(54);
      if (lookahead == '`') ADVANCE(47);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(34);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(anon_sym_BQUOTE_BQUOTE_BQUOTE_LF);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(anon_sym_LF_BQUOTE_BQUOTE_BQUOTE);
      if (lookahead == '\n') ADVANCE(55);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(anon_sym_LF);
      if (lookahead == '\n') ADVANCE(57);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(anon_sym_LF_BQUOTE_BQUOTE_BQUOTE_LF);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0, .external_lex_state = 1},
  [1] = {.lex_state = 3, .external_lex_state = 2},
  [2] = {.lex_state = 10, .external_lex_state = 3},
  [3] = {.lex_state = 10, .external_lex_state = 3},
  [4] = {.lex_state = 5, .external_lex_state = 1},
  [5] = {.lex_state = 5, .external_lex_state = 1},
  [6] = {.lex_state = 5, .external_lex_state = 1},
  [7] = {.lex_state = 5, .external_lex_state = 4},
  [8] = {.lex_state = 5, .external_lex_state = 4},
  [9] = {.lex_state = 5, .external_lex_state = 4},
  [10] = {.lex_state = 0, .external_lex_state = 5},
  [11] = {.lex_state = 10, .external_lex_state = 1},
  [12] = {.lex_state = 0, .external_lex_state = 5},
  [13] = {.lex_state = 0, .external_lex_state = 5},
  [14] = {.lex_state = 12, .external_lex_state = 5},
  [15] = {.lex_state = 0, .external_lex_state = 6},
  [16] = {.lex_state = 5, .external_lex_state = 3},
  [17] = {.lex_state = 5, .external_lex_state = 3},
  [18] = {.lex_state = 5, .external_lex_state = 1},
  [19] = {.lex_state = 0, .external_lex_state = 6},
  [20] = {.lex_state = 5, .external_lex_state = 3},
  [21] = {.lex_state = 10, .external_lex_state = 4},
  [22] = {.lex_state = 0, .external_lex_state = 6},
  [23] = {.lex_state = 5, .external_lex_state = 4},
  [24] = {.lex_state = 3, .external_lex_state = 3},
  [25] = {.lex_state = 12, .external_lex_state = 6},
  [26] = {.lex_state = 0, .external_lex_state = 5},
  [27] = {.lex_state = 3, .external_lex_state = 3},
  [28] = {.lex_state = 3, .external_lex_state = 7},
  [29] = {.lex_state = 3, .external_lex_state = 7},
  [30] = {.lex_state = 3, .external_lex_state = 2},
  [31] = {.lex_state = 3, .external_lex_state = 3},
  [32] = {.lex_state = 5, .external_lex_state = 1},
  [33] = {.lex_state = 3, .external_lex_state = 3},
  [34] = {.lex_state = 5, .external_lex_state = 1},
  [35] = {.lex_state = 3, .external_lex_state = 3},
  [36] = {.lex_state = 3, .external_lex_state = 7},
  [37] = {.lex_state = 3, .external_lex_state = 3},
  [38] = {.lex_state = 10, .external_lex_state = 1},
  [39] = {.lex_state = 0, .external_lex_state = 6},
  [40] = {.lex_state = 5, .external_lex_state = 3},
  [41] = {.lex_state = 3, .external_lex_state = 8},
  [42] = {.lex_state = 5, .external_lex_state = 4},
  [43] = {.lex_state = 3, .external_lex_state = 8},
  [44] = {.lex_state = 5, .external_lex_state = 4},
  [45] = {.lex_state = 3, .external_lex_state = 8},
  [46] = {.lex_state = 0, .external_lex_state = 5},
  [47] = {.lex_state = 3, .external_lex_state = 3},
  [48] = {.lex_state = 0, .external_lex_state = 5},
  [49] = {.lex_state = 12, .external_lex_state = 5},
  [50] = {.lex_state = 0, .external_lex_state = 6},
  [51] = {.lex_state = 5, .external_lex_state = 3},
  [52] = {.lex_state = 0, .external_lex_state = 6},
  [53] = {.lex_state = 5, .external_lex_state = 3},
  [54] = {.lex_state = 10, .external_lex_state = 4},
  [55] = {.lex_state = 3, .external_lex_state = 2},
  [56] = {.lex_state = 12, .external_lex_state = 6},
  [57] = {.lex_state = 3, .external_lex_state = 1},
  [58] = {.lex_state = 3, .external_lex_state = 5},
  [59] = {.lex_state = 3, .external_lex_state = 4},
  [60] = {.lex_state = 3},
  [61] = {.lex_state = 3, .external_lex_state = 6},
  [62] = {.lex_state = 3, .external_lex_state = 7},
  [63] = {.lex_state = 3, .external_lex_state = 7},
  [64] = {.lex_state = 3},
  [65] = {.lex_state = 3},
  [66] = {.lex_state = 3},
  [67] = {.lex_state = 3, .external_lex_state = 3},
  [68] = {.lex_state = 3, .external_lex_state = 8},
  [69] = {.lex_state = 3, .external_lex_state = 3},
  [70] = {.lex_state = 3, .external_lex_state = 3},
  [71] = {.lex_state = 3, .external_lex_state = 8},
  [72] = {.lex_state = 3, .external_lex_state = 2},
  [73] = {.lex_state = 3, .external_lex_state = 2},
  [74] = {.lex_state = 3, .external_lex_state = 2},
  [75] = {.lex_state = 3, .external_lex_state = 9},
  [76] = {.lex_state = 3, .external_lex_state = 9},
  [77] = {.lex_state = 3, .external_lex_state = 2},
  [78] = {.lex_state = 3, .external_lex_state = 2},
  [79] = {.lex_state = 3, .external_lex_state = 2},
  [80] = {.lex_state = 6},
  [81] = {.lex_state = 6},
  [82] = {.lex_state = 6},
  [83] = {.lex_state = 6},
  [84] = {.lex_state = 7},
  [85] = {.lex_state = 6},
  [86] = {.lex_state = 6},
  [87] = {.lex_state = 6},
  [88] = {.lex_state = 6},
  [89] = {.lex_state = 3, .external_lex_state = 9},
  [90] = {.lex_state = 3, .external_lex_state = 9},
  [91] = {.lex_state = 7},
  [92] = {.lex_state = 3, .external_lex_state = 9},
  [93] = {.lex_state = 6},
  [94] = {.lex_state = 6},
  [95] = {.lex_state = 3, .external_lex_state = 9},
  [96] = {.lex_state = 3, .external_lex_state = 2},
  [97] = {.lex_state = 0, .external_lex_state = 9},
  [98] = {.lex_state = 3, .external_lex_state = 2},
  [99] = {.lex_state = 3},
  [100] = {.lex_state = 3, .external_lex_state = 2},
  [101] = {.lex_state = 0, .external_lex_state = 9},
  [102] = {.lex_state = 0, .external_lex_state = 9},
  [103] = {.lex_state = 3, .external_lex_state = 2},
  [104] = {.lex_state = 0, .external_lex_state = 9},
  [105] = {.lex_state = 3, .external_lex_state = 2},
  [106] = {.lex_state = 0, .external_lex_state = 9},
  [107] = {.lex_state = 0, .external_lex_state = 9},
  [108] = {.lex_state = 8},
  [109] = {.lex_state = 8},
  [110] = {.lex_state = 8},
  [111] = {.lex_state = 8},
  [112] = {.lex_state = 8},
  [113] = {.lex_state = 8},
  [114] = {.lex_state = 8},
  [115] = {.lex_state = 8},
  [116] = {.lex_state = 8},
  [117] = {.lex_state = 3},
  [118] = {.lex_state = 9},
  [119] = {.lex_state = 0},
  [120] = {.lex_state = 3},
  [121] = {.lex_state = 9},
  [122] = {.lex_state = 3},
  [123] = {.lex_state = 3},
  [124] = {.lex_state = 3},
  [125] = {.lex_state = 8},
  [126] = {.lex_state = 8},
  [127] = {.lex_state = 3},
  [128] = {.lex_state = 0},
  [129] = {.lex_state = 3},
  [130] = {.lex_state = 8},
  [131] = {.lex_state = 3},
  [132] = {.lex_state = 3},
  [133] = {.lex_state = 9},
  [134] = {.lex_state = 9},
  [135] = {.lex_state = 9},
  [136] = {.lex_state = 9},
  [137] = {.lex_state = 3},
  [138] = {.lex_state = 0},
  [139] = {.lex_state = 0},
  [140] = {.lex_state = 3},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_section_header] = ACTIONS(1),
    [sym_marker_task_pending] = ACTIONS(1),
    [sym_marker_task_done] = ACTIONS(1),
    [sym_marker_property_info] = ACTIONS(1),
    [sym_marker_property_label] = ACTIONS(1),
    [sym__line] = ACTIONS(1),
    [sym__newline] = ACTIONS(1),
    [anon_sym_BQUOTE_BQUOTE_BQUOTE_LF] = ACTIONS(1),
    [anon_sym_LF_BQUOTE_BQUOTE_BQUOTE] = ACTIONS(1),
    [sym__indent] = ACTIONS(1),
    [sym__dedent] = ACTIONS(1),
    [sym__section_in] = ACTIONS(1),
    [sym__section_out] = ACTIONS(1),
    [sym__section_sibling] = ACTIONS(1),
    [sym__eof] = ACTIONS(1),
  },
  [1] = {
    [sym_document] = STATE(119),
    [sym_section] = STATE(79),
    [sym_marker_task] = STATE(130),
    [sym_marker_property] = STATE(130),
    [sym_marker] = STATE(114),
    [sym_item] = STATE(30),
    [aux_sym_document_repeat1] = STATE(30),
    [aux_sym_document_repeat2] = STATE(79),
    [sym_section_header] = ACTIONS(3),
    [sym_marker_task_pending] = ACTIONS(5),
    [sym_marker_task_done] = ACTIONS(5),
    [sym_marker_property_info] = ACTIONS(7),
    [sym_marker_property_label] = ACTIONS(7),
    [sym__section_in] = ACTIONS(9),
    [sym__eof] = ACTIONS(11),
  },
  [2] = {
    [sym_section_children] = STATE(101),
    [sym_marker_task] = STATE(130),
    [sym_marker_property] = STATE(130),
    [sym_marker] = STATE(116),
    [sym_body] = STATE(31),
    [sym_item] = STATE(24),
    [sym_code_block] = STATE(16),
    [aux_sym_document_repeat1] = STATE(24),
    [sym_marker_task_pending] = ACTIONS(13),
    [sym_marker_task_done] = ACTIONS(13),
    [sym_marker_property_info] = ACTIONS(15),
    [sym_marker_property_label] = ACTIONS(15),
    [sym__line] = ACTIONS(17),
    [anon_sym_BQUOTE_BQUOTE_BQUOTE_LF] = ACTIONS(19),
    [anon_sym_LF_BQUOTE_BQUOTE_BQUOTE] = ACTIONS(21),
    [sym__section_in] = ACTIONS(23),
    [sym__section_out] = ACTIONS(25),
    [sym__section_sibling] = ACTIONS(25),
    [sym__eof] = ACTIONS(25),
  },
  [3] = {
    [sym_section_children] = STATE(106),
    [sym_marker_task] = STATE(130),
    [sym_marker_property] = STATE(130),
    [sym_marker] = STATE(116),
    [sym_body] = STATE(37),
    [sym_item] = STATE(35),
    [sym_code_block] = STATE(16),
    [aux_sym_document_repeat1] = STATE(35),
    [sym_marker_task_pending] = ACTIONS(13),
    [sym_marker_task_done] = ACTIONS(13),
    [sym_marker_property_info] = ACTIONS(15),
    [sym_marker_property_label] = ACTIONS(15),
    [sym__line] = ACTIONS(17),
    [anon_sym_BQUOTE_BQUOTE_BQUOTE_LF] = ACTIONS(19),
    [anon_sym_LF_BQUOTE_BQUOTE_BQUOTE] = ACTIONS(21),
    [sym__section_in] = ACTIONS(23),
    [sym__section_out] = ACTIONS(27),
    [sym__section_sibling] = ACTIONS(27),
    [sym__eof] = ACTIONS(27),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 6,
    ACTIONS(33), 1,
      anon_sym_BQUOTE_BQUOTE_BQUOTE_LF,
    ACTIONS(35), 1,
      anon_sym_LF_BQUOTE_BQUOTE_BQUOTE,
    ACTIONS(31), 2,
      sym__line,
      sym__newline,
    STATE(6), 3,
      aux_sym__lines,
      sym_code_block,
      aux_sym_body_repeat1,
    ACTIONS(29), 4,
      sym_marker_task_pending,
      sym_marker_task_done,
      sym_marker_property_info,
      sym_marker_property_label,
    ACTIONS(37), 6,
      sym__indent,
      sym__dedent,
      sym__section_in,
      sym__section_out,
      sym__section_sibling,
      sym__eof,
  [30] = 6,
    ACTIONS(44), 1,
      anon_sym_BQUOTE_BQUOTE_BQUOTE_LF,
    ACTIONS(47), 1,
      anon_sym_LF_BQUOTE_BQUOTE_BQUOTE,
    ACTIONS(41), 2,
      sym__line,
      sym__newline,
    STATE(5), 3,
      aux_sym__lines,
      sym_code_block,
      aux_sym_body_repeat1,
    ACTIONS(39), 4,
      sym_marker_task_pending,
      sym_marker_task_done,
      sym_marker_property_info,
      sym_marker_property_label,
    ACTIONS(50), 6,
      sym__indent,
      sym__dedent,
      sym__section_in,
      sym__section_out,
      sym__section_sibling,
      sym__eof,
  [60] = 6,
    ACTIONS(33), 1,
      anon_sym_BQUOTE_BQUOTE_BQUOTE_LF,
    ACTIONS(35), 1,
      anon_sym_LF_BQUOTE_BQUOTE_BQUOTE,
    ACTIONS(54), 2,
      sym__line,
      sym__newline,
    STATE(5), 3,
      aux_sym__lines,
      sym_code_block,
      aux_sym_body_repeat1,
    ACTIONS(52), 4,
      sym_marker_task_pending,
      sym_marker_task_done,
      sym_marker_property_info,
      sym_marker_property_label,
    ACTIONS(56), 6,
      sym__indent,
      sym__dedent,
      sym__section_in,
      sym__section_out,
      sym__section_sibling,
      sym__eof,
  [90] = 6,
    ACTIONS(60), 1,
      anon_sym_BQUOTE_BQUOTE_BQUOTE_LF,
    ACTIONS(62), 1,
      anon_sym_LF_BQUOTE_BQUOTE_BQUOTE,
    ACTIONS(58), 2,
      sym__line,
      sym__newline,
    STATE(8), 3,
      aux_sym__lines,
      sym_code_block,
      aux_sym_body_repeat1,
    ACTIONS(29), 4,
      sym_marker_task_pending,
      sym_marker_task_done,
      sym_marker_property_info,
      sym_marker_property_label,
    ACTIONS(37), 5,
      sym__indent,
      sym__section_in,
      sym__section_out,
      sym__section_sibling,
      sym__eof,
  [119] = 6,
    ACTIONS(60), 1,
      anon_sym_BQUOTE_BQUOTE_BQUOTE_LF,
    ACTIONS(62), 1,
      anon_sym_LF_BQUOTE_BQUOTE_BQUOTE,
    ACTIONS(64), 2,
      sym__line,
      sym__newline,
    STATE(9), 3,
      aux_sym__lines,
      sym_code_block,
      aux_sym_body_repeat1,
    ACTIONS(52), 4,
      sym_marker_task_pending,
      sym_marker_task_done,
      sym_marker_property_info,
      sym_marker_property_label,
    ACTIONS(56), 5,
      sym__indent,
      sym__section_in,
      sym__section_out,
      sym__section_sibling,
      sym__eof,
  [148] = 6,
    ACTIONS(69), 1,
      anon_sym_BQUOTE_BQUOTE_BQUOTE_LF,
    ACTIONS(72), 1,
      anon_sym_LF_BQUOTE_BQUOTE_BQUOTE,
    ACTIONS(66), 2,
      sym__line,
      sym__newline,
    STATE(9), 3,
      aux_sym__lines,
      sym_code_block,
      aux_sym_body_repeat1,
    ACTIONS(39), 4,
      sym_marker_task_pending,
      sym_marker_task_done,
      sym_marker_property_info,
      sym_marker_property_label,
    ACTIONS(50), 5,
      sym__indent,
      sym__section_in,
      sym__section_out,
      sym__section_sibling,
      sym__eof,
  [177] = 6,
    ACTIONS(77), 1,
      anon_sym_BQUOTE_BQUOTE_BQUOTE_LF,
    ACTIONS(79), 1,
      anon_sym_LF_BQUOTE_BQUOTE_BQUOTE,
    ACTIONS(75), 2,
      sym__line,
      sym__newline,
    STATE(12), 3,
      aux_sym__lines,
      sym_code_block,
      aux_sym_body_repeat1,
    ACTIONS(37), 4,
      sym__indent,
      sym__dedent,
      sym__section_in,
      sym__eof,
    ACTIONS(29), 5,
      sym_section_header,
      sym_marker_task_pending,
      sym_marker_task_done,
      sym_marker_property_info,
      sym_marker_property_label,
  [206] = 9,
    ACTIONS(33), 1,
      anon_sym_BQUOTE_BQUOTE_BQUOTE_LF,
    ACTIONS(35), 1,
      anon_sym_LF_BQUOTE_BQUOTE_BQUOTE,
    ACTIONS(83), 1,
      sym__line,
    ACTIONS(85), 1,
      sym__indent,
    STATE(4), 1,
      sym_code_block,
    STATE(57), 1,
      sym_body,
    STATE(63), 1,
      sym_children,
    ACTIONS(81), 4,
      sym_marker_task_pending,
      sym_marker_task_done,
      sym_marker_property_info,
      sym_marker_property_label,
    ACTIONS(87), 5,
      sym__dedent,
      sym__section_in,
      sym__section_out,
      sym__section_sibling,
      sym__eof,
  [241] = 6,
    ACTIONS(77), 1,
      anon_sym_BQUOTE_BQUOTE_BQUOTE_LF,
    ACTIONS(79), 1,
      anon_sym_LF_BQUOTE_BQUOTE_BQUOTE,
    ACTIONS(89), 2,
      sym__line,
      sym__newline,
    STATE(13), 3,
      aux_sym__lines,
      sym_code_block,
      aux_sym_body_repeat1,
    ACTIONS(56), 4,
      sym__indent,
      sym__dedent,
      sym__section_in,
      sym__eof,
    ACTIONS(52), 5,
      sym_section_header,
      sym_marker_task_pending,
      sym_marker_task_done,
      sym_marker_property_info,
      sym_marker_property_label,
  [270] = 6,
    ACTIONS(94), 1,
      anon_sym_BQUOTE_BQUOTE_BQUOTE_LF,
    ACTIONS(97), 1,
      anon_sym_LF_BQUOTE_BQUOTE_BQUOTE,
    ACTIONS(91), 2,
      sym__line,
      sym__newline,
    STATE(13), 3,
      aux_sym__lines,
      sym_code_block,
      aux_sym_body_repeat1,
    ACTIONS(50), 4,
      sym__indent,
      sym__dedent,
      sym__section_in,
      sym__eof,
    ACTIONS(39), 5,
      sym_section_header,
      sym_marker_task_pending,
      sym_marker_task_done,
      sym_marker_property_info,
      sym_marker_property_label,
  [299] = 9,
    ACTIONS(77), 1,
      anon_sym_BQUOTE_BQUOTE_BQUOTE_LF,
    ACTIONS(79), 1,
      anon_sym_LF_BQUOTE_BQUOTE_BQUOTE,
    ACTIONS(100), 1,
      sym__line,
    ACTIONS(102), 1,
      sym__indent,
    STATE(10), 1,
      sym_code_block,
    STATE(58), 1,
      sym_body,
    STATE(68), 1,
      sym_children,
    ACTIONS(87), 3,
      sym__dedent,
      sym__section_in,
      sym__eof,
    ACTIONS(81), 5,
      sym_section_header,
      sym_marker_task_pending,
      sym_marker_task_done,
      sym_marker_property_info,
      sym_marker_property_label,
  [333] = 6,
    ACTIONS(107), 1,
      anon_sym_BQUOTE_BQUOTE_BQUOTE_LF,
    ACTIONS(110), 1,
      anon_sym_LF_BQUOTE_BQUOTE_BQUOTE,
    ACTIONS(104), 2,
      sym__line,
      sym__newline,
    ACTIONS(50), 3,
      sym__indent,
      sym__section_in,
      sym__eof,
    STATE(15), 3,
      aux_sym__lines,
      sym_code_block,
      aux_sym_body_repeat1,
    ACTIONS(39), 5,
      sym_section_header,
      sym_marker_task_pending,
      sym_marker_task_done,
      sym_marker_property_info,
      sym_marker_property_label,
  [361] = 6,
    ACTIONS(19), 1,
      anon_sym_BQUOTE_BQUOTE_BQUOTE_LF,
    ACTIONS(21), 1,
      anon_sym_LF_BQUOTE_BQUOTE_BQUOTE,
    ACTIONS(113), 2,
      sym__line,
      sym__newline,
    STATE(20), 3,
      aux_sym__lines,
      sym_code_block,
      aux_sym_body_repeat1,
    ACTIONS(29), 4,
      sym_marker_task_pending,
      sym_marker_task_done,
      sym_marker_property_info,
      sym_marker_property_label,
    ACTIONS(37), 4,
      sym__section_in,
      sym__section_out,
      sym__section_sibling,
      sym__eof,
  [389] = 6,
    ACTIONS(118), 1,
      anon_sym_BQUOTE_BQUOTE_BQUOTE_LF,
    ACTIONS(121), 1,
      anon_sym_LF_BQUOTE_BQUOTE_BQUOTE,
    ACTIONS(115), 2,
      sym__line,
      sym__newline,
    STATE(17), 3,
      aux_sym__lines,
      sym_code_block,
      aux_sym_body_repeat1,
    ACTIONS(39), 4,
      sym_marker_task_pending,
      sym_marker_task_done,
      sym_marker_property_info,
      sym_marker_property_label,
    ACTIONS(50), 4,
      sym__section_in,
      sym__section_out,
      sym__section_sibling,
      sym__eof,
  [417] = 4,
    STATE(18), 1,
      aux_sym__lines,
    ACTIONS(126), 2,
      sym__line,
      sym__newline,
    ACTIONS(124), 6,
      sym_marker_task_pending,
      sym_marker_task_done,
      sym_marker_property_info,
      sym_marker_property_label,
      anon_sym_BQUOTE_BQUOTE_BQUOTE_LF,
      anon_sym_LF_BQUOTE_BQUOTE_BQUOTE,
    ACTIONS(129), 6,
      sym__indent,
      sym__dedent,
      sym__section_in,
      sym__section_out,
      sym__section_sibling,
      sym__eof,
  [441] = 6,
    ACTIONS(133), 1,
      anon_sym_BQUOTE_BQUOTE_BQUOTE_LF,
    ACTIONS(135), 1,
      anon_sym_LF_BQUOTE_BQUOTE_BQUOTE,
    ACTIONS(131), 2,
      sym__line,
      sym__newline,
    ACTIONS(37), 3,
      sym__indent,
      sym__section_in,
      sym__eof,
    STATE(22), 3,
      aux_sym__lines,
      sym_code_block,
      aux_sym_body_repeat1,
    ACTIONS(29), 5,
      sym_section_header,
      sym_marker_task_pending,
      sym_marker_task_done,
      sym_marker_property_info,
      sym_marker_property_label,
  [469] = 6,
    ACTIONS(19), 1,
      anon_sym_BQUOTE_BQUOTE_BQUOTE_LF,
    ACTIONS(21), 1,
      anon_sym_LF_BQUOTE_BQUOTE_BQUOTE,
    ACTIONS(137), 2,
      sym__line,
      sym__newline,
    STATE(17), 3,
      aux_sym__lines,
      sym_code_block,
      aux_sym_body_repeat1,
    ACTIONS(52), 4,
      sym_marker_task_pending,
      sym_marker_task_done,
      sym_marker_property_info,
      sym_marker_property_label,
    ACTIONS(56), 4,
      sym__section_in,
      sym__section_out,
      sym__section_sibling,
      sym__eof,
  [497] = 9,
    ACTIONS(60), 1,
      anon_sym_BQUOTE_BQUOTE_BQUOTE_LF,
    ACTIONS(62), 1,
      anon_sym_LF_BQUOTE_BQUOTE_BQUOTE,
    ACTIONS(139), 1,
      sym__line,
    ACTIONS(141), 1,
      sym__indent,
    STATE(7), 1,
      sym_code_block,
    STATE(59), 1,
      sym_body,
    STATE(69), 1,
      sym_children,
    ACTIONS(81), 4,
      sym_marker_task_pending,
      sym_marker_task_done,
      sym_marker_property_info,
      sym_marker_property_label,
    ACTIONS(87), 4,
      sym__section_in,
      sym__section_out,
      sym__section_sibling,
      sym__eof,
  [531] = 6,
    ACTIONS(133), 1,
      anon_sym_BQUOTE_BQUOTE_BQUOTE_LF,
    ACTIONS(135), 1,
      anon_sym_LF_BQUOTE_BQUOTE_BQUOTE,
    ACTIONS(143), 2,
      sym__line,
      sym__newline,
    ACTIONS(56), 3,
      sym__indent,
      sym__section_in,
      sym__eof,
    STATE(15), 3,
      aux_sym__lines,
      sym_code_block,
      aux_sym_body_repeat1,
    ACTIONS(52), 5,
      sym_section_header,
      sym_marker_task_pending,
      sym_marker_task_done,
      sym_marker_property_info,
      sym_marker_property_label,
  [559] = 4,
    STATE(23), 1,
      aux_sym__lines,
    ACTIONS(145), 2,
      sym__line,
      sym__newline,
    ACTIONS(129), 5,
      sym__indent,
      sym__section_in,
      sym__section_out,
      sym__section_sibling,
      sym__eof,
    ACTIONS(124), 6,
      sym_marker_task_pending,
      sym_marker_task_done,
      sym_marker_property_info,
      sym_marker_property_label,
      anon_sym_BQUOTE_BQUOTE_BQUOTE_LF,
      anon_sym_LF_BQUOTE_BQUOTE_BQUOTE,
  [582] = 8,
    ACTIONS(23), 1,
      sym__section_in,
    STATE(104), 1,
      sym_section_children,
    STATE(116), 1,
      sym_marker,
    ACTIONS(5), 2,
      sym_marker_task_pending,
      sym_marker_task_done,
    ACTIONS(7), 2,
      sym_marker_property_info,
      sym_marker_property_label,
    STATE(47), 2,
      sym_item,
      aux_sym_document_repeat1,
    STATE(130), 2,
      sym_marker_task,
      sym_marker_property,
    ACTIONS(148), 3,
      sym__section_out,
      sym__section_sibling,
      sym__eof,
  [613] = 9,
    ACTIONS(133), 1,
      anon_sym_BQUOTE_BQUOTE_BQUOTE_LF,
    ACTIONS(135), 1,
      anon_sym_LF_BQUOTE_BQUOTE_BQUOTE,
    ACTIONS(150), 1,
      sym__line,
    ACTIONS(152), 1,
      sym__indent,
    STATE(19), 1,
      sym_code_block,
    STATE(61), 1,
      sym_body,
    STATE(74), 1,
      sym_children,
    ACTIONS(87), 2,
      sym__section_in,
      sym__eof,
    ACTIONS(81), 5,
      sym_section_header,
      sym_marker_task_pending,
      sym_marker_task_done,
      sym_marker_property_info,
      sym_marker_property_label,
  [646] = 4,
    STATE(26), 1,
      aux_sym__lines,
    ACTIONS(154), 2,
      sym__line,
      sym__newline,
    ACTIONS(129), 4,
      sym__indent,
      sym__dedent,
      sym__section_in,
      sym__eof,
    ACTIONS(124), 7,
      sym_section_header,
      sym_marker_task_pending,
      sym_marker_task_done,
      sym_marker_property_info,
      sym_marker_property_label,
      anon_sym_BQUOTE_BQUOTE_BQUOTE_LF,
      anon_sym_LF_BQUOTE_BQUOTE_BQUOTE,
  [669] = 8,
    ACTIONS(23), 1,
      sym__section_in,
    STATE(107), 1,
      sym_section_children,
    STATE(116), 1,
      sym_marker,
    ACTIONS(5), 2,
      sym_marker_task_pending,
      sym_marker_task_done,
    ACTIONS(7), 2,
      sym_marker_property_info,
      sym_marker_property_label,
    STATE(47), 2,
      sym_item,
      aux_sym_document_repeat1,
    STATE(130), 2,
      sym_marker_task,
      sym_marker_property,
    ACTIONS(157), 3,
      sym__section_out,
      sym__section_sibling,
      sym__eof,
  [700] = 5,
    ACTIONS(161), 1,
      sym__dedent,
    STATE(108), 1,
      sym_marker,
    STATE(29), 2,
      sym_item,
      aux_sym_document_repeat1,
    STATE(130), 2,
      sym_marker_task,
      sym_marker_property,
    ACTIONS(159), 8,
      sym__section_in,
      sym__section_out,
      sym__section_sibling,
      sym__eof,
      sym_marker_task_pending,
      sym_marker_task_done,
      sym_marker_property_info,
      sym_marker_property_label,
  [725] = 6,
    STATE(108), 1,
      sym_marker,
    ACTIONS(163), 2,
      sym_marker_task_pending,
      sym_marker_task_done,
    ACTIONS(166), 2,
      sym_marker_property_info,
      sym_marker_property_label,
    STATE(29), 2,
      sym_item,
      aux_sym_document_repeat1,
    STATE(130), 2,
      sym_marker_task,
      sym_marker_property,
    ACTIONS(169), 5,
      sym__dedent,
      sym__section_in,
      sym__section_out,
      sym__section_sibling,
      sym__eof,
  [752] = 9,
    ACTIONS(3), 1,
      sym_section_header,
    ACTIONS(9), 1,
      sym__section_in,
    ACTIONS(171), 1,
      sym__eof,
    STATE(114), 1,
      sym_marker,
    ACTIONS(5), 2,
      sym_marker_task_pending,
      sym_marker_task_done,
    ACTIONS(7), 2,
      sym_marker_property_info,
      sym_marker_property_label,
    STATE(55), 2,
      sym_item,
      aux_sym_document_repeat1,
    STATE(78), 2,
      sym_section,
      aux_sym_document_repeat2,
    STATE(130), 2,
      sym_marker_task,
      sym_marker_property,
  [785] = 8,
    ACTIONS(23), 1,
      sym__section_in,
    STATE(104), 1,
      sym_section_children,
    STATE(116), 1,
      sym_marker,
    ACTIONS(5), 2,
      sym_marker_task_pending,
      sym_marker_task_done,
    ACTIONS(7), 2,
      sym_marker_property_info,
      sym_marker_property_label,
    STATE(33), 2,
      sym_item,
      aux_sym_document_repeat1,
    STATE(130), 2,
      sym_marker_task,
      sym_marker_property,
    ACTIONS(148), 3,
      sym__section_out,
      sym__section_sibling,
      sym__eof,
  [816] = 2,
    ACTIONS(175), 6,
      sym__indent,
      sym__dedent,
      sym__section_in,
      sym__section_out,
      sym__section_sibling,
      sym__eof,
    ACTIONS(173), 8,
      sym_marker_task_pending,
      sym_marker_task_done,
      sym_marker_property_info,
      sym_marker_property_label,
      sym__line,
      sym__newline,
      anon_sym_BQUOTE_BQUOTE_BQUOTE_LF,
      anon_sym_LF_BQUOTE_BQUOTE_BQUOTE,
  [835] = 8,
    ACTIONS(23), 1,
      sym__section_in,
    STATE(102), 1,
      sym_section_children,
    STATE(116), 1,
      sym_marker,
    ACTIONS(5), 2,
      sym_marker_task_pending,
      sym_marker_task_done,
    ACTIONS(7), 2,
      sym_marker_property_info,
      sym_marker_property_label,
    STATE(47), 2,
      sym_item,
      aux_sym_document_repeat1,
    STATE(130), 2,
      sym_marker_task,
      sym_marker_property,
    ACTIONS(177), 3,
      sym__section_out,
      sym__section_sibling,
      sym__eof,
  [866] = 2,
    ACTIONS(181), 6,
      sym__indent,
      sym__dedent,
      sym__section_in,
      sym__section_out,
      sym__section_sibling,
      sym__eof,
    ACTIONS(179), 8,
      sym_marker_task_pending,
      sym_marker_task_done,
      sym_marker_property_info,
      sym_marker_property_label,
      sym__line,
      sym__newline,
      anon_sym_BQUOTE_BQUOTE_BQUOTE_LF,
      anon_sym_LF_BQUOTE_BQUOTE_BQUOTE,
  [885] = 8,
    ACTIONS(23), 1,
      sym__section_in,
    STATE(97), 1,
      sym_section_children,
    STATE(116), 1,
      sym_marker,
    ACTIONS(5), 2,
      sym_marker_task_pending,
      sym_marker_task_done,
    ACTIONS(7), 2,
      sym_marker_property_info,
      sym_marker_property_label,
    STATE(47), 2,
      sym_item,
      aux_sym_document_repeat1,
    STATE(130), 2,
      sym_marker_task,
      sym_marker_property,
    ACTIONS(183), 3,
      sym__section_out,
      sym__section_sibling,
      sym__eof,
  [916] = 4,
    STATE(108), 1,
      sym_marker,
    STATE(29), 2,
      sym_item,
      aux_sym_document_repeat1,
    STATE(130), 2,
      sym_marker_task,
      sym_marker_property,
    ACTIONS(159), 9,
      sym__dedent,
      sym__section_in,
      sym__section_out,
      sym__section_sibling,
      sym__eof,
      sym_marker_task_pending,
      sym_marker_task_done,
      sym_marker_property_info,
      sym_marker_property_label,
  [939] = 8,
    ACTIONS(23), 1,
      sym__section_in,
    STATE(97), 1,
      sym_section_children,
    STATE(116), 1,
      sym_marker,
    ACTIONS(5), 2,
      sym_marker_task_pending,
      sym_marker_task_done,
    ACTIONS(7), 2,
      sym_marker_property_info,
      sym_marker_property_label,
    STATE(27), 2,
      sym_item,
      aux_sym_document_repeat1,
    STATE(130), 2,
      sym_marker_task,
      sym_marker_property,
    ACTIONS(183), 3,
      sym__section_out,
      sym__section_sibling,
      sym__eof,
  [970] = 2,
    ACTIONS(187), 6,
      sym__indent,
      sym__dedent,
      sym__section_in,
      sym__section_out,
      sym__section_sibling,
      sym__eof,
    ACTIONS(185), 7,
      sym_marker_task_pending,
      sym_marker_task_done,
      sym_marker_property_info,
      sym_marker_property_label,
      sym__line,
      anon_sym_BQUOTE_BQUOTE_BQUOTE_LF,
      anon_sym_LF_BQUOTE_BQUOTE_BQUOTE,
  [988] = 4,
    STATE(39), 1,
      aux_sym__lines,
    ACTIONS(189), 2,
      sym__line,
      sym__newline,
    ACTIONS(129), 3,
      sym__indent,
      sym__section_in,
      sym__eof,
    ACTIONS(124), 7,
      sym_section_header,
      sym_marker_task_pending,
      sym_marker_task_done,
      sym_marker_property_info,
      sym_marker_property_label,
      anon_sym_BQUOTE_BQUOTE_BQUOTE_LF,
      anon_sym_LF_BQUOTE_BQUOTE_BQUOTE,
  [1010] = 4,
    STATE(40), 1,
      aux_sym__lines,
    ACTIONS(192), 2,
      sym__line,
      sym__newline,
    ACTIONS(129), 4,
      sym__section_in,
      sym__section_out,
      sym__section_sibling,
      sym__eof,
    ACTIONS(124), 6,
      sym_marker_task_pending,
      sym_marker_task_done,
      sym_marker_property_info,
      sym_marker_property_label,
      anon_sym_BQUOTE_BQUOTE_BQUOTE_LF,
      anon_sym_LF_BQUOTE_BQUOTE_BQUOTE,
  [1032] = 4,
    STATE(115), 1,
      sym_marker,
    STATE(43), 2,
      sym_item,
      aux_sym_document_repeat1,
    STATE(130), 2,
      sym_marker_task,
      sym_marker_property,
    ACTIONS(159), 8,
      sym__dedent,
      sym__section_in,
      sym__eof,
      sym_section_header,
      sym_marker_task_pending,
      sym_marker_task_done,
      sym_marker_property_info,
      sym_marker_property_label,
  [1054] = 2,
    ACTIONS(175), 5,
      sym__indent,
      sym__section_in,
      sym__section_out,
      sym__section_sibling,
      sym__eof,
    ACTIONS(173), 8,
      sym_marker_task_pending,
      sym_marker_task_done,
      sym_marker_property_info,
      sym_marker_property_label,
      sym__line,
      sym__newline,
      anon_sym_BQUOTE_BQUOTE_BQUOTE_LF,
      anon_sym_LF_BQUOTE_BQUOTE_BQUOTE,
  [1072] = 6,
    STATE(115), 1,
      sym_marker,
    ACTIONS(163), 2,
      sym_marker_task_pending,
      sym_marker_task_done,
    ACTIONS(166), 2,
      sym_marker_property_info,
      sym_marker_property_label,
    STATE(43), 2,
      sym_item,
      aux_sym_document_repeat1,
    STATE(130), 2,
      sym_marker_task,
      sym_marker_property,
    ACTIONS(169), 4,
      sym__dedent,
      sym__section_in,
      sym__eof,
      sym_section_header,
  [1098] = 2,
    ACTIONS(181), 5,
      sym__indent,
      sym__section_in,
      sym__section_out,
      sym__section_sibling,
      sym__eof,
    ACTIONS(179), 8,
      sym_marker_task_pending,
      sym_marker_task_done,
      sym_marker_property_info,
      sym_marker_property_label,
      sym__line,
      sym__newline,
      anon_sym_BQUOTE_BQUOTE_BQUOTE_LF,
      anon_sym_LF_BQUOTE_BQUOTE_BQUOTE,
  [1116] = 5,
    ACTIONS(195), 1,
      sym__dedent,
    STATE(115), 1,
      sym_marker,
    STATE(43), 2,
      sym_item,
      aux_sym_document_repeat1,
    STATE(130), 2,
      sym_marker_task,
      sym_marker_property,
    ACTIONS(159), 7,
      sym__section_in,
      sym__eof,
      sym_section_header,
      sym_marker_task_pending,
      sym_marker_task_done,
      sym_marker_property_info,
      sym_marker_property_label,
  [1140] = 2,
    ACTIONS(181), 4,
      sym__indent,
      sym__dedent,
      sym__section_in,
      sym__eof,
    ACTIONS(179), 9,
      sym_section_header,
      sym_marker_task_pending,
      sym_marker_task_done,
      sym_marker_property_info,
      sym_marker_property_label,
      sym__line,
      sym__newline,
      anon_sym_BQUOTE_BQUOTE_BQUOTE_LF,
      anon_sym_LF_BQUOTE_BQUOTE_BQUOTE,
  [1158] = 6,
    STATE(116), 1,
      sym_marker,
    ACTIONS(163), 2,
      sym_marker_task_pending,
      sym_marker_task_done,
    ACTIONS(166), 2,
      sym_marker_property_info,
      sym_marker_property_label,
    STATE(47), 2,
      sym_item,
      aux_sym_document_repeat1,
    STATE(130), 2,
      sym_marker_task,
      sym_marker_property,
    ACTIONS(169), 4,
      sym__section_in,
      sym__section_out,
      sym__section_sibling,
      sym__eof,
  [1184] = 2,
    ACTIONS(175), 4,
      sym__indent,
      sym__dedent,
      sym__section_in,
      sym__eof,
    ACTIONS(173), 9,
      sym_section_header,
      sym_marker_task_pending,
      sym_marker_task_done,
      sym_marker_property_info,
      sym_marker_property_label,
      sym__line,
      sym__newline,
      anon_sym_BQUOTE_BQUOTE_BQUOTE_LF,
      anon_sym_LF_BQUOTE_BQUOTE_BQUOTE,
  [1202] = 2,
    ACTIONS(187), 4,
      sym__indent,
      sym__dedent,
      sym__section_in,
      sym__eof,
    ACTIONS(185), 8,
      sym_section_header,
      sym_marker_task_pending,
      sym_marker_task_done,
      sym_marker_property_info,
      sym_marker_property_label,
      sym__line,
      anon_sym_BQUOTE_BQUOTE_BQUOTE_LF,
      anon_sym_LF_BQUOTE_BQUOTE_BQUOTE,
  [1219] = 2,
    ACTIONS(181), 3,
      sym__indent,
      sym__section_in,
      sym__eof,
    ACTIONS(179), 9,
      sym_section_header,
      sym_marker_task_pending,
      sym_marker_task_done,
      sym_marker_property_info,
      sym_marker_property_label,
      sym__line,
      sym__newline,
      anon_sym_BQUOTE_BQUOTE_BQUOTE_LF,
      anon_sym_LF_BQUOTE_BQUOTE_BQUOTE,
  [1236] = 2,
    ACTIONS(181), 4,
      sym__section_in,
      sym__section_out,
      sym__section_sibling,
      sym__eof,
    ACTIONS(179), 8,
      sym_marker_task_pending,
      sym_marker_task_done,
      sym_marker_property_info,
      sym_marker_property_label,
      sym__line,
      sym__newline,
      anon_sym_BQUOTE_BQUOTE_BQUOTE_LF,
      anon_sym_LF_BQUOTE_BQUOTE_BQUOTE,
  [1253] = 2,
    ACTIONS(175), 3,
      sym__indent,
      sym__section_in,
      sym__eof,
    ACTIONS(173), 9,
      sym_section_header,
      sym_marker_task_pending,
      sym_marker_task_done,
      sym_marker_property_info,
      sym_marker_property_label,
      sym__line,
      sym__newline,
      anon_sym_BQUOTE_BQUOTE_BQUOTE_LF,
      anon_sym_LF_BQUOTE_BQUOTE_BQUOTE,
  [1270] = 2,
    ACTIONS(175), 4,
      sym__section_in,
      sym__section_out,
      sym__section_sibling,
      sym__eof,
    ACTIONS(173), 8,
      sym_marker_task_pending,
      sym_marker_task_done,
      sym_marker_property_info,
      sym_marker_property_label,
      sym__line,
      sym__newline,
      anon_sym_BQUOTE_BQUOTE_BQUOTE_LF,
      anon_sym_LF_BQUOTE_BQUOTE_BQUOTE,
  [1287] = 2,
    ACTIONS(187), 5,
      sym__indent,
      sym__section_in,
      sym__section_out,
      sym__section_sibling,
      sym__eof,
    ACTIONS(185), 7,
      sym_marker_task_pending,
      sym_marker_task_done,
      sym_marker_property_info,
      sym_marker_property_label,
      sym__line,
      anon_sym_BQUOTE_BQUOTE_BQUOTE_LF,
      anon_sym_LF_BQUOTE_BQUOTE_BQUOTE,
  [1304] = 6,
    STATE(114), 1,
      sym_marker,
    ACTIONS(163), 2,
      sym_marker_task_pending,
      sym_marker_task_done,
    ACTIONS(166), 2,
      sym_marker_property_info,
      sym_marker_property_label,
    STATE(55), 2,
      sym_item,
      aux_sym_document_repeat1,
    STATE(130), 2,
      sym_marker_task,
      sym_marker_property,
    ACTIONS(169), 3,
      sym__section_in,
      sym__eof,
      sym_section_header,
  [1329] = 2,
    ACTIONS(187), 3,
      sym__indent,
      sym__section_in,
      sym__eof,
    ACTIONS(185), 8,
      sym_section_header,
      sym_marker_task_pending,
      sym_marker_task_done,
      sym_marker_property_info,
      sym_marker_property_label,
      sym__line,
      anon_sym_BQUOTE_BQUOTE_BQUOTE_LF,
      anon_sym_LF_BQUOTE_BQUOTE_BQUOTE,
  [1345] = 3,
    ACTIONS(85), 1,
      sym__indent,
    STATE(62), 1,
      sym_children,
    ACTIONS(197), 9,
      sym__dedent,
      sym__section_in,
      sym__section_out,
      sym__section_sibling,
      sym__eof,
      sym_marker_task_pending,
      sym_marker_task_done,
      sym_marker_property_info,
      sym_marker_property_label,
  [1363] = 3,
    ACTIONS(102), 1,
      sym__indent,
    STATE(71), 1,
      sym_children,
    ACTIONS(197), 8,
      sym__dedent,
      sym__section_in,
      sym__eof,
      sym_section_header,
      sym_marker_task_pending,
      sym_marker_task_done,
      sym_marker_property_info,
      sym_marker_property_label,
  [1380] = 3,
    ACTIONS(141), 1,
      sym__indent,
    STATE(70), 1,
      sym_children,
    ACTIONS(197), 8,
      sym__section_in,
      sym__section_out,
      sym__section_sibling,
      sym__eof,
      sym_marker_task_pending,
      sym_marker_task_done,
      sym_marker_property_info,
      sym_marker_property_label,
  [1397] = 5,
    STATE(115), 1,
      sym_marker,
    ACTIONS(5), 2,
      sym_marker_task_pending,
      sym_marker_task_done,
    ACTIONS(7), 2,
      sym_marker_property_info,
      sym_marker_property_label,
    STATE(45), 2,
      sym_item,
      aux_sym_document_repeat1,
    STATE(130), 2,
      sym_marker_task,
      sym_marker_property,
  [1417] = 3,
    ACTIONS(152), 1,
      sym__indent,
    STATE(73), 1,
      sym_children,
    ACTIONS(197), 7,
      sym__section_in,
      sym__eof,
      sym_section_header,
      sym_marker_task_pending,
      sym_marker_task_done,
      sym_marker_property_info,
      sym_marker_property_label,
  [1433] = 1,
    ACTIONS(199), 9,
      sym__dedent,
      sym__section_in,
      sym__section_out,
      sym__section_sibling,
      sym__eof,
      sym_marker_task_pending,
      sym_marker_task_done,
      sym_marker_property_info,
      sym_marker_property_label,
  [1445] = 1,
    ACTIONS(197), 9,
      sym__dedent,
      sym__section_in,
      sym__section_out,
      sym__section_sibling,
      sym__eof,
      sym_marker_task_pending,
      sym_marker_task_done,
      sym_marker_property_info,
      sym_marker_property_label,
  [1457] = 5,
    STATE(108), 1,
      sym_marker,
    ACTIONS(5), 2,
      sym_marker_task_pending,
      sym_marker_task_done,
    ACTIONS(7), 2,
      sym_marker_property_info,
      sym_marker_property_label,
    STATE(28), 2,
      sym_item,
      aux_sym_document_repeat1,
    STATE(130), 2,
      sym_marker_task,
      sym_marker_property,
  [1477] = 5,
    STATE(115), 1,
      sym_marker,
    ACTIONS(5), 2,
      sym_marker_task_pending,
      sym_marker_task_done,
    ACTIONS(7), 2,
      sym_marker_property_info,
      sym_marker_property_label,
    STATE(41), 2,
      sym_item,
      aux_sym_document_repeat1,
    STATE(130), 2,
      sym_marker_task,
      sym_marker_property,
  [1497] = 5,
    STATE(108), 1,
      sym_marker,
    ACTIONS(5), 2,
      sym_marker_task_pending,
      sym_marker_task_done,
    ACTIONS(7), 2,
      sym_marker_property_info,
      sym_marker_property_label,
    STATE(36), 2,
      sym_item,
      aux_sym_document_repeat1,
    STATE(130), 2,
      sym_marker_task,
      sym_marker_property,
  [1517] = 1,
    ACTIONS(201), 8,
      sym__section_in,
      sym__section_out,
      sym__section_sibling,
      sym__eof,
      sym_marker_task_pending,
      sym_marker_task_done,
      sym_marker_property_info,
      sym_marker_property_label,
  [1528] = 1,
    ACTIONS(197), 8,
      sym__dedent,
      sym__section_in,
      sym__eof,
      sym_section_header,
      sym_marker_task_pending,
      sym_marker_task_done,
      sym_marker_property_info,
      sym_marker_property_label,
  [1539] = 1,
    ACTIONS(197), 8,
      sym__section_in,
      sym__section_out,
      sym__section_sibling,
      sym__eof,
      sym_marker_task_pending,
      sym_marker_task_done,
      sym_marker_property_info,
      sym_marker_property_label,
  [1550] = 1,
    ACTIONS(199), 8,
      sym__section_in,
      sym__section_out,
      sym__section_sibling,
      sym__eof,
      sym_marker_task_pending,
      sym_marker_task_done,
      sym_marker_property_info,
      sym_marker_property_label,
  [1561] = 1,
    ACTIONS(199), 8,
      sym__dedent,
      sym__section_in,
      sym__eof,
      sym_section_header,
      sym_marker_task_pending,
      sym_marker_task_done,
      sym_marker_property_info,
      sym_marker_property_label,
  [1572] = 1,
    ACTIONS(201), 7,
      sym__section_in,
      sym__eof,
      sym_section_header,
      sym_marker_task_pending,
      sym_marker_task_done,
      sym_marker_property_info,
      sym_marker_property_label,
  [1582] = 1,
    ACTIONS(199), 7,
      sym__section_in,
      sym__eof,
      sym_section_header,
      sym_marker_task_pending,
      sym_marker_task_done,
      sym_marker_property_info,
      sym_marker_property_label,
  [1592] = 1,
    ACTIONS(197), 7,
      sym__section_in,
      sym__eof,
      sym_section_header,
      sym_marker_task_pending,
      sym_marker_task_done,
      sym_marker_property_info,
      sym_marker_property_label,
  [1602] = 3,
    ACTIONS(203), 1,
      sym_section_header,
    STATE(76), 2,
      sym_section,
      aux_sym_section_children_repeat1,
    ACTIONS(205), 3,
      sym__section_out,
      sym__section_sibling,
      sym__eof,
  [1615] = 3,
    ACTIONS(207), 1,
      sym_section_header,
    STATE(76), 2,
      sym_section,
      aux_sym_section_children_repeat1,
    ACTIONS(210), 3,
      sym__section_out,
      sym__section_sibling,
      sym__eof,
  [1628] = 4,
    ACTIONS(212), 1,
      sym_section_header,
    ACTIONS(215), 1,
      sym__section_in,
    ACTIONS(218), 1,
      sym__eof,
    STATE(77), 2,
      sym_section,
      aux_sym_document_repeat2,
  [1642] = 4,
    ACTIONS(3), 1,
      sym_section_header,
    ACTIONS(9), 1,
      sym__section_in,
    ACTIONS(220), 1,
      sym__eof,
    STATE(77), 2,
      sym_section,
      aux_sym_document_repeat2,
  [1656] = 4,
    ACTIONS(3), 1,
      sym_section_header,
    ACTIONS(9), 1,
      sym__section_in,
    ACTIONS(171), 1,
      sym__eof,
    STATE(77), 2,
      sym_section,
      aux_sym_document_repeat2,
  [1670] = 3,
    STATE(91), 1,
      aux_sym__lines,
    STATE(120), 1,
      sym_code_block_content,
    ACTIONS(222), 2,
      sym__line,
      sym__newline,
  [1681] = 3,
    STATE(91), 1,
      aux_sym__lines,
    STATE(129), 1,
      sym_code_block_content,
    ACTIONS(222), 2,
      sym__line,
      sym__newline,
  [1692] = 3,
    STATE(91), 1,
      aux_sym__lines,
    STATE(131), 1,
      sym_code_block_content,
    ACTIONS(222), 2,
      sym__line,
      sym__newline,
  [1703] = 3,
    STATE(91), 1,
      aux_sym__lines,
    STATE(132), 1,
      sym_code_block_content,
    ACTIONS(222), 2,
      sym__line,
      sym__newline,
  [1714] = 3,
    ACTIONS(124), 1,
      anon_sym_LF_BQUOTE_BQUOTE_BQUOTE_LF,
    STATE(84), 1,
      aux_sym__lines,
    ACTIONS(224), 2,
      sym__line,
      sym__newline,
  [1725] = 3,
    STATE(91), 1,
      aux_sym__lines,
    STATE(127), 1,
      sym_code_block_content,
    ACTIONS(222), 2,
      sym__line,
      sym__newline,
  [1736] = 3,
    STATE(91), 1,
      aux_sym__lines,
    STATE(137), 1,
      sym_code_block_content,
    ACTIONS(222), 2,
      sym__line,
      sym__newline,
  [1747] = 3,
    STATE(91), 1,
      aux_sym__lines,
    STATE(140), 1,
      sym_code_block_content,
    ACTIONS(222), 2,
      sym__line,
      sym__newline,
  [1758] = 3,
    STATE(91), 1,
      aux_sym__lines,
    STATE(122), 1,
      sym_code_block_content,
    ACTIONS(222), 2,
      sym__line,
      sym__newline,
  [1769] = 1,
    ACTIONS(227), 4,
      sym__section_out,
      sym__section_sibling,
      sym__eof,
      sym_section_header,
  [1776] = 1,
    ACTIONS(229), 4,
      sym__section_out,
      sym__section_sibling,
      sym__eof,
      sym_section_header,
  [1783] = 3,
    ACTIONS(233), 1,
      anon_sym_LF_BQUOTE_BQUOTE_BQUOTE_LF,
    STATE(84), 1,
      aux_sym__lines,
    ACTIONS(231), 2,
      sym__line,
      sym__newline,
  [1794] = 1,
    ACTIONS(235), 4,
      sym__section_out,
      sym__section_sibling,
      sym__eof,
      sym_section_header,
  [1801] = 3,
    STATE(91), 1,
      aux_sym__lines,
    STATE(124), 1,
      sym_code_block_content,
    ACTIONS(222), 2,
      sym__line,
      sym__newline,
  [1812] = 3,
    STATE(91), 1,
      aux_sym__lines,
    STATE(123), 1,
      sym_code_block_content,
    ACTIONS(222), 2,
      sym__line,
      sym__newline,
  [1823] = 1,
    ACTIONS(237), 4,
      sym__section_out,
      sym__section_sibling,
      sym__eof,
      sym_section_header,
  [1830] = 1,
    ACTIONS(218), 3,
      sym__section_in,
      sym__eof,
      sym_section_header,
  [1836] = 1,
    ACTIONS(157), 3,
      sym__section_out,
      sym__section_sibling,
      sym__eof,
  [1842] = 1,
    ACTIONS(227), 3,
      sym__section_in,
      sym__eof,
      sym_section_header,
  [1848] = 2,
    ACTIONS(203), 1,
      sym_section_header,
    STATE(75), 2,
      sym_section,
      aux_sym_section_children_repeat1,
  [1856] = 1,
    ACTIONS(235), 3,
      sym__section_in,
      sym__eof,
      sym_section_header,
  [1862] = 1,
    ACTIONS(148), 3,
      sym__section_out,
      sym__section_sibling,
      sym__eof,
  [1868] = 1,
    ACTIONS(239), 3,
      sym__section_out,
      sym__section_sibling,
      sym__eof,
  [1874] = 1,
    ACTIONS(229), 3,
      sym__section_in,
      sym__eof,
      sym_section_header,
  [1880] = 1,
    ACTIONS(177), 3,
      sym__section_out,
      sym__section_sibling,
      sym__eof,
  [1886] = 1,
    ACTIONS(237), 3,
      sym__section_in,
      sym__eof,
      sym_section_header,
  [1892] = 1,
    ACTIONS(183), 3,
      sym__section_out,
      sym__section_sibling,
      sym__eof,
  [1898] = 1,
    ACTIONS(241), 3,
      sym__section_out,
      sym__section_sibling,
      sym__eof,
  [1904] = 2,
    ACTIONS(243), 1,
      sym__line,
    STATE(11), 1,
      sym_content,
  [1911] = 2,
    ACTIONS(245), 1,
      sym__line,
    STATE(118), 1,
      sym_code_block_language,
  [1918] = 2,
    ACTIONS(245), 1,
      sym__line,
    STATE(136), 1,
      sym_code_block_language,
  [1925] = 2,
    ACTIONS(245), 1,
      sym__line,
    STATE(135), 1,
      sym_code_block_language,
  [1932] = 2,
    ACTIONS(245), 1,
      sym__line,
    STATE(134), 1,
      sym_code_block_language,
  [1939] = 2,
    ACTIONS(245), 1,
      sym__line,
    STATE(133), 1,
      sym_code_block_language,
  [1946] = 2,
    ACTIONS(247), 1,
      sym__line,
    STATE(25), 1,
      sym_content,
  [1953] = 2,
    ACTIONS(249), 1,
      sym__line,
    STATE(14), 1,
      sym_content,
  [1960] = 2,
    ACTIONS(251), 1,
      sym__line,
    STATE(21), 1,
      sym_content,
  [1967] = 2,
    ACTIONS(3), 1,
      sym_section_header,
    STATE(96), 1,
      sym_section,
  [1974] = 1,
    ACTIONS(253), 1,
      anon_sym_LF,
  [1978] = 1,
    ACTIONS(255), 1,
      ts_builtin_sym_end,
  [1982] = 1,
    ACTIONS(257), 1,
      anon_sym_LF_BQUOTE_BQUOTE_BQUOTE_LF,
  [1986] = 1,
    ACTIONS(259), 1,
      anon_sym_LF,
  [1990] = 1,
    ACTIONS(261), 1,
      anon_sym_LF_BQUOTE_BQUOTE_BQUOTE_LF,
  [1994] = 1,
    ACTIONS(263), 1,
      anon_sym_LF_BQUOTE_BQUOTE_BQUOTE_LF,
  [1998] = 1,
    ACTIONS(265), 1,
      anon_sym_LF_BQUOTE_BQUOTE_BQUOTE_LF,
  [2002] = 1,
    ACTIONS(267), 1,
      sym__line,
  [2006] = 1,
    ACTIONS(269), 1,
      sym__line,
  [2010] = 1,
    ACTIONS(271), 1,
      anon_sym_LF_BQUOTE_BQUOTE_BQUOTE_LF,
  [2014] = 1,
    ACTIONS(273), 1,
      ts_builtin_sym_end,
  [2018] = 1,
    ACTIONS(275), 1,
      anon_sym_LF_BQUOTE_BQUOTE_BQUOTE_LF,
  [2022] = 1,
    ACTIONS(277), 1,
      sym__line,
  [2026] = 1,
    ACTIONS(279), 1,
      anon_sym_LF_BQUOTE_BQUOTE_BQUOTE_LF,
  [2030] = 1,
    ACTIONS(281), 1,
      anon_sym_LF_BQUOTE_BQUOTE_BQUOTE_LF,
  [2034] = 1,
    ACTIONS(283), 1,
      anon_sym_LF,
  [2038] = 1,
    ACTIONS(285), 1,
      anon_sym_LF,
  [2042] = 1,
    ACTIONS(287), 1,
      anon_sym_LF,
  [2046] = 1,
    ACTIONS(289), 1,
      anon_sym_LF,
  [2050] = 1,
    ACTIONS(291), 1,
      anon_sym_LF_BQUOTE_BQUOTE_BQUOTE_LF,
  [2054] = 1,
    ACTIONS(293), 1,
      ts_builtin_sym_end,
  [2058] = 1,
    ACTIONS(295), 1,
      ts_builtin_sym_end,
  [2062] = 1,
    ACTIONS(297), 1,
      anon_sym_LF_BQUOTE_BQUOTE_BQUOTE_LF,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(4)] = 0,
  [SMALL_STATE(5)] = 30,
  [SMALL_STATE(6)] = 60,
  [SMALL_STATE(7)] = 90,
  [SMALL_STATE(8)] = 119,
  [SMALL_STATE(9)] = 148,
  [SMALL_STATE(10)] = 177,
  [SMALL_STATE(11)] = 206,
  [SMALL_STATE(12)] = 241,
  [SMALL_STATE(13)] = 270,
  [SMALL_STATE(14)] = 299,
  [SMALL_STATE(15)] = 333,
  [SMALL_STATE(16)] = 361,
  [SMALL_STATE(17)] = 389,
  [SMALL_STATE(18)] = 417,
  [SMALL_STATE(19)] = 441,
  [SMALL_STATE(20)] = 469,
  [SMALL_STATE(21)] = 497,
  [SMALL_STATE(22)] = 531,
  [SMALL_STATE(23)] = 559,
  [SMALL_STATE(24)] = 582,
  [SMALL_STATE(25)] = 613,
  [SMALL_STATE(26)] = 646,
  [SMALL_STATE(27)] = 669,
  [SMALL_STATE(28)] = 700,
  [SMALL_STATE(29)] = 725,
  [SMALL_STATE(30)] = 752,
  [SMALL_STATE(31)] = 785,
  [SMALL_STATE(32)] = 816,
  [SMALL_STATE(33)] = 835,
  [SMALL_STATE(34)] = 866,
  [SMALL_STATE(35)] = 885,
  [SMALL_STATE(36)] = 916,
  [SMALL_STATE(37)] = 939,
  [SMALL_STATE(38)] = 970,
  [SMALL_STATE(39)] = 988,
  [SMALL_STATE(40)] = 1010,
  [SMALL_STATE(41)] = 1032,
  [SMALL_STATE(42)] = 1054,
  [SMALL_STATE(43)] = 1072,
  [SMALL_STATE(44)] = 1098,
  [SMALL_STATE(45)] = 1116,
  [SMALL_STATE(46)] = 1140,
  [SMALL_STATE(47)] = 1158,
  [SMALL_STATE(48)] = 1184,
  [SMALL_STATE(49)] = 1202,
  [SMALL_STATE(50)] = 1219,
  [SMALL_STATE(51)] = 1236,
  [SMALL_STATE(52)] = 1253,
  [SMALL_STATE(53)] = 1270,
  [SMALL_STATE(54)] = 1287,
  [SMALL_STATE(55)] = 1304,
  [SMALL_STATE(56)] = 1329,
  [SMALL_STATE(57)] = 1345,
  [SMALL_STATE(58)] = 1363,
  [SMALL_STATE(59)] = 1380,
  [SMALL_STATE(60)] = 1397,
  [SMALL_STATE(61)] = 1417,
  [SMALL_STATE(62)] = 1433,
  [SMALL_STATE(63)] = 1445,
  [SMALL_STATE(64)] = 1457,
  [SMALL_STATE(65)] = 1477,
  [SMALL_STATE(66)] = 1497,
  [SMALL_STATE(67)] = 1517,
  [SMALL_STATE(68)] = 1528,
  [SMALL_STATE(69)] = 1539,
  [SMALL_STATE(70)] = 1550,
  [SMALL_STATE(71)] = 1561,
  [SMALL_STATE(72)] = 1572,
  [SMALL_STATE(73)] = 1582,
  [SMALL_STATE(74)] = 1592,
  [SMALL_STATE(75)] = 1602,
  [SMALL_STATE(76)] = 1615,
  [SMALL_STATE(77)] = 1628,
  [SMALL_STATE(78)] = 1642,
  [SMALL_STATE(79)] = 1656,
  [SMALL_STATE(80)] = 1670,
  [SMALL_STATE(81)] = 1681,
  [SMALL_STATE(82)] = 1692,
  [SMALL_STATE(83)] = 1703,
  [SMALL_STATE(84)] = 1714,
  [SMALL_STATE(85)] = 1725,
  [SMALL_STATE(86)] = 1736,
  [SMALL_STATE(87)] = 1747,
  [SMALL_STATE(88)] = 1758,
  [SMALL_STATE(89)] = 1769,
  [SMALL_STATE(90)] = 1776,
  [SMALL_STATE(91)] = 1783,
  [SMALL_STATE(92)] = 1794,
  [SMALL_STATE(93)] = 1801,
  [SMALL_STATE(94)] = 1812,
  [SMALL_STATE(95)] = 1823,
  [SMALL_STATE(96)] = 1830,
  [SMALL_STATE(97)] = 1836,
  [SMALL_STATE(98)] = 1842,
  [SMALL_STATE(99)] = 1848,
  [SMALL_STATE(100)] = 1856,
  [SMALL_STATE(101)] = 1862,
  [SMALL_STATE(102)] = 1868,
  [SMALL_STATE(103)] = 1874,
  [SMALL_STATE(104)] = 1880,
  [SMALL_STATE(105)] = 1886,
  [SMALL_STATE(106)] = 1892,
  [SMALL_STATE(107)] = 1898,
  [SMALL_STATE(108)] = 1904,
  [SMALL_STATE(109)] = 1911,
  [SMALL_STATE(110)] = 1918,
  [SMALL_STATE(111)] = 1925,
  [SMALL_STATE(112)] = 1932,
  [SMALL_STATE(113)] = 1939,
  [SMALL_STATE(114)] = 1946,
  [SMALL_STATE(115)] = 1953,
  [SMALL_STATE(116)] = 1960,
  [SMALL_STATE(117)] = 1967,
  [SMALL_STATE(118)] = 1974,
  [SMALL_STATE(119)] = 1978,
  [SMALL_STATE(120)] = 1982,
  [SMALL_STATE(121)] = 1986,
  [SMALL_STATE(122)] = 1990,
  [SMALL_STATE(123)] = 1994,
  [SMALL_STATE(124)] = 1998,
  [SMALL_STATE(125)] = 2002,
  [SMALL_STATE(126)] = 2006,
  [SMALL_STATE(127)] = 2010,
  [SMALL_STATE(128)] = 2014,
  [SMALL_STATE(129)] = 2018,
  [SMALL_STATE(130)] = 2022,
  [SMALL_STATE(131)] = 2026,
  [SMALL_STATE(132)] = 2030,
  [SMALL_STATE(133)] = 2034,
  [SMALL_STATE(134)] = 2038,
  [SMALL_STATE(135)] = 2042,
  [SMALL_STATE(136)] = 2046,
  [SMALL_STATE(137)] = 2050,
  [SMALL_STATE(138)] = 2054,
  [SMALL_STATE(139)] = 2058,
  [SMALL_STATE(140)] = 2062,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(126),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(125),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(117),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(139),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(126),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(125),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(16),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(85),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(109),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(99),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(98),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(89),
  [29] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_body, 1, 0, 0),
  [31] = {.entry = {.count = 1, .reusable = false}}, SHIFT(6),
  [33] = {.entry = {.count = 1, .reusable = false}}, SHIFT(94),
  [35] = {.entry = {.count = 1, .reusable = false}}, SHIFT(110),
  [37] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_body, 1, 0, 0),
  [39] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_body_repeat1, 2, 0, 0),
  [41] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_body_repeat1, 2, 0, 0), SHIFT_REPEAT(5),
  [44] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_body_repeat1, 2, 0, 0), SHIFT_REPEAT(94),
  [47] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_body_repeat1, 2, 0, 0), SHIFT_REPEAT(110),
  [50] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_body_repeat1, 2, 0, 0),
  [52] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_body, 2, 0, 0),
  [54] = {.entry = {.count = 1, .reusable = false}}, SHIFT(5),
  [56] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_body, 2, 0, 0),
  [58] = {.entry = {.count = 1, .reusable = false}}, SHIFT(8),
  [60] = {.entry = {.count = 1, .reusable = false}}, SHIFT(83),
  [62] = {.entry = {.count = 1, .reusable = false}}, SHIFT(112),
  [64] = {.entry = {.count = 1, .reusable = false}}, SHIFT(9),
  [66] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_body_repeat1, 2, 0, 0), SHIFT_REPEAT(9),
  [69] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_body_repeat1, 2, 0, 0), SHIFT_REPEAT(83),
  [72] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_body_repeat1, 2, 0, 0), SHIFT_REPEAT(112),
  [75] = {.entry = {.count = 1, .reusable = false}}, SHIFT(12),
  [77] = {.entry = {.count = 1, .reusable = false}}, SHIFT(80),
  [79] = {.entry = {.count = 1, .reusable = false}}, SHIFT(111),
  [81] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_item, 2, 0, 0),
  [83] = {.entry = {.count = 1, .reusable = false}}, SHIFT(4),
  [85] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [87] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_item, 2, 0, 0),
  [89] = {.entry = {.count = 1, .reusable = false}}, SHIFT(13),
  [91] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_body_repeat1, 2, 0, 0), SHIFT_REPEAT(13),
  [94] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_body_repeat1, 2, 0, 0), SHIFT_REPEAT(80),
  [97] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_body_repeat1, 2, 0, 0), SHIFT_REPEAT(111),
  [100] = {.entry = {.count = 1, .reusable = false}}, SHIFT(10),
  [102] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [104] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_body_repeat1, 2, 0, 0), SHIFT_REPEAT(15),
  [107] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_body_repeat1, 2, 0, 0), SHIFT_REPEAT(87),
  [110] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_body_repeat1, 2, 0, 0), SHIFT_REPEAT(113),
  [113] = {.entry = {.count = 1, .reusable = false}}, SHIFT(20),
  [115] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_body_repeat1, 2, 0, 0), SHIFT_REPEAT(17),
  [118] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_body_repeat1, 2, 0, 0), SHIFT_REPEAT(85),
  [121] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_body_repeat1, 2, 0, 0), SHIFT_REPEAT(109),
  [124] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym__lines, 2, 0, 0),
  [126] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__lines, 2, 0, 0), SHIFT_REPEAT(18),
  [129] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__lines, 2, 0, 0),
  [131] = {.entry = {.count = 1, .reusable = false}}, SHIFT(22),
  [133] = {.entry = {.count = 1, .reusable = false}}, SHIFT(87),
  [135] = {.entry = {.count = 1, .reusable = false}}, SHIFT(113),
  [137] = {.entry = {.count = 1, .reusable = false}}, SHIFT(17),
  [139] = {.entry = {.count = 1, .reusable = false}}, SHIFT(7),
  [141] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [143] = {.entry = {.count = 1, .reusable = false}}, SHIFT(15),
  [145] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__lines, 2, 0, 0), SHIFT_REPEAT(23),
  [148] = {.entry = {.count = 1, .reusable = true}}, SHIFT(105),
  [150] = {.entry = {.count = 1, .reusable = false}}, SHIFT(19),
  [152] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [154] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__lines, 2, 0, 0), SHIFT_REPEAT(26),
  [157] = {.entry = {.count = 1, .reusable = true}}, SHIFT(90),
  [159] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_children, 2, 0, 0),
  [161] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [163] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(126),
  [166] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(125),
  [169] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0),
  [171] = {.entry = {.count = 1, .reusable = true}}, SHIFT(138),
  [173] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_code_block, 3, 0, 0),
  [175] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_code_block, 3, 0, 0),
  [177] = {.entry = {.count = 1, .reusable = true}}, SHIFT(103),
  [179] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_code_block, 5, 0, 0),
  [181] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_code_block, 5, 0, 0),
  [183] = {.entry = {.count = 1, .reusable = true}}, SHIFT(95),
  [185] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_content, 1, 0, 0),
  [187] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_content, 1, 0, 0),
  [189] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__lines, 2, 0, 0), SHIFT_REPEAT(39),
  [192] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__lines, 2, 0, 0), SHIFT_REPEAT(40),
  [195] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [197] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_item, 3, 0, 0),
  [199] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_item, 4, 0, 0),
  [201] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_children, 3, 0, 0),
  [203] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [205] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_section_children, 2, 0, 0),
  [207] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_section_children_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [210] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_section_children_repeat1, 2, 0, 0),
  [212] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat2, 2, 0, 0), SHIFT_REPEAT(2),
  [215] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat2, 2, 0, 0), SHIFT_REPEAT(117),
  [218] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_document_repeat2, 2, 0, 0),
  [220] = {.entry = {.count = 1, .reusable = true}}, SHIFT(128),
  [222] = {.entry = {.count = 1, .reusable = false}}, SHIFT(91),
  [224] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__lines, 2, 0, 0), SHIFT_REPEAT(84),
  [227] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_section, 2, 0, 0),
  [229] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_section, 4, 0, 0),
  [231] = {.entry = {.count = 1, .reusable = false}}, SHIFT(84),
  [233] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_code_block_content, 1, 0, 0),
  [235] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_section, 5, 0, 0),
  [237] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_section, 3, 0, 0),
  [239] = {.entry = {.count = 1, .reusable = true}}, SHIFT(100),
  [241] = {.entry = {.count = 1, .reusable = true}}, SHIFT(92),
  [243] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [245] = {.entry = {.count = 1, .reusable = true}}, SHIFT(121),
  [247] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [249] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [251] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [253] = {.entry = {.count = 1, .reusable = true}}, SHIFT(82),
  [255] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [257] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [259] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_code_block_language, 1, 0, 0),
  [261] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [263] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [265] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [267] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_marker_property, 1, 0, 0),
  [269] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_marker_task, 1, 0, 0),
  [271] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [273] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 3, 0, 0),
  [275] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [277] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_marker, 1, 0, 0),
  [279] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [281] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [283] = {.entry = {.count = 1, .reusable = true}}, SHIFT(86),
  [285] = {.entry = {.count = 1, .reusable = true}}, SHIFT(81),
  [287] = {.entry = {.count = 1, .reusable = true}}, SHIFT(88),
  [289] = {.entry = {.count = 1, .reusable = true}}, SHIFT(93),
  [291] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [293] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 2, 0, 0),
  [295] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 1, 0, 0),
  [297] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
};

enum ts_external_scanner_symbol_identifiers {
  ts_external_token__indent = 0,
  ts_external_token__dedent = 1,
  ts_external_token__section_in = 2,
  ts_external_token__section_out = 3,
  ts_external_token__section_sibling = 4,
  ts_external_token__eof = 5,
};

static const TSSymbol ts_external_scanner_symbol_map[EXTERNAL_TOKEN_COUNT] = {
  [ts_external_token__indent] = sym__indent,
  [ts_external_token__dedent] = sym__dedent,
  [ts_external_token__section_in] = sym__section_in,
  [ts_external_token__section_out] = sym__section_out,
  [ts_external_token__section_sibling] = sym__section_sibling,
  [ts_external_token__eof] = sym__eof,
};

static const bool ts_external_scanner_states[10][EXTERNAL_TOKEN_COUNT] = {
  [1] = {
    [ts_external_token__indent] = true,
    [ts_external_token__dedent] = true,
    [ts_external_token__section_in] = true,
    [ts_external_token__section_out] = true,
    [ts_external_token__section_sibling] = true,
    [ts_external_token__eof] = true,
  },
  [2] = {
    [ts_external_token__section_in] = true,
    [ts_external_token__eof] = true,
  },
  [3] = {
    [ts_external_token__section_in] = true,
    [ts_external_token__section_out] = true,
    [ts_external_token__section_sibling] = true,
    [ts_external_token__eof] = true,
  },
  [4] = {
    [ts_external_token__indent] = true,
    [ts_external_token__section_in] = true,
    [ts_external_token__section_out] = true,
    [ts_external_token__section_sibling] = true,
    [ts_external_token__eof] = true,
  },
  [5] = {
    [ts_external_token__indent] = true,
    [ts_external_token__dedent] = true,
    [ts_external_token__section_in] = true,
    [ts_external_token__eof] = true,
  },
  [6] = {
    [ts_external_token__indent] = true,
    [ts_external_token__section_in] = true,
    [ts_external_token__eof] = true,
  },
  [7] = {
    [ts_external_token__dedent] = true,
    [ts_external_token__section_in] = true,
    [ts_external_token__section_out] = true,
    [ts_external_token__section_sibling] = true,
    [ts_external_token__eof] = true,
  },
  [8] = {
    [ts_external_token__dedent] = true,
    [ts_external_token__section_in] = true,
    [ts_external_token__eof] = true,
  },
  [9] = {
    [ts_external_token__section_out] = true,
    [ts_external_token__section_sibling] = true,
    [ts_external_token__eof] = true,
  },
};

#ifdef __cplusplus
extern "C" {
#endif
void *tree_sitter_note_external_scanner_create(void);
void tree_sitter_note_external_scanner_destroy(void *);
bool tree_sitter_note_external_scanner_scan(void *, TSLexer *, const bool *);
unsigned tree_sitter_note_external_scanner_serialize(void *, char *);
void tree_sitter_note_external_scanner_deserialize(void *, const char *, unsigned);

#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_note(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .external_scanner = {
      &ts_external_scanner_states[0][0],
      ts_external_scanner_symbol_map,
      tree_sitter_note_external_scanner_create,
      tree_sitter_note_external_scanner_destroy,
      tree_sitter_note_external_scanner_scan,
      tree_sitter_note_external_scanner_serialize,
      tree_sitter_note_external_scanner_deserialize,
    },
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
